### ISSUE TITLE
Indexer.TokenBalance.Fetcher duplicated Token Balance error

### ISSUE THREAD

**Issue by amandasposito** [poanetwork/blockscout#1064]
The `token_balances` seems to be repeated in the list and it raises an exception:

```
[conflict_target: [:address_hash, :token_contract_address_hash, :block_number], on_conflict: #Ecto.Query<from t in Explorer.Chain.Address.TokenBalance, update: [set: [inserted_at: fragment("LEAST(EXCLUDED.inserted_at, ?)", t.inserted_at), updated_at: fragment("GREATEST(EXCLUDED.updated_at, ?)", t.updated_at), value: fragment("CASE WHEN EXCLUDED.value IS NOT NULL AND (? IS NULL OR EXCLUDED.value_fetched_at > ?) THEN\n       EXCLUDED.value\n     ELSE\n       ?\nEND\n", t.value_fetched_at, t.value_fetched_at, t.value), value_fetched_at: fragment("CASE WHEN EXCLUDED.value IS NOT NULL AND (? IS NULL OR EXCLUDED.value_fetched_at > ?) THEN\n       EXCLUDED.value_fetched_at\n     ELSE\n       ?\nEND\n", t.value_fetched_at, t.value_fetched_at, t.value_fetched_at)]]>, returning: true, timeout: 60000, timestamps: %{inserted_at: #DateTime<2018-11-07 15:45:46.430679Z>, updated_at: #DateTime<2018-11-07 15:45:46.430679Z>}]

Exception:

** (Postgrex.Error) ERROR 21000 (cardinality_violation): ON CONFLICT DO UPDATE command cannot affect row a second time
13:45:46.470 [error] Task #PID<0.31628.0> started from Indexer.TokenBalance.Fetcher terminating
** (Postgrex.Error) ERROR 21000 (cardinality_violation): ON CONFLICT DO UPDATE command cannot affect row a second time
    (explorer) lib/explorer/repo.ex:58: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain/import.ex:304: Explorer.Chain.Import.insert_changes_list/2
    (explorer) lib/explorer/chain/import/address/token_balances.ex:66: Explorer.Chain.Import.Address.TokenBalances.insert/2
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/chain/import.ex:132: Explorer.Chain.Import.all/1
    (indexer) lib/indexer/token_balance/fetcher.ex:92: Indexer.TokenBalance.Fetcher.import_token_balances/1
    (indexer) lib/indexer/token_balance/fetcher.ex:65: Indexer.TokenBalance.Fetcher.run/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.TokenBalance.Fetcher.run/2
```

### Steps to reproduce

Try to index using the `genoda` node.

**Comment by pasqu4le** [comment]
The problem described by this issue is now prevented because of #2270
