### ISSUE TITLE
Phoenix.HTML templates only support iodata, and not chardata

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1097]
```
 ** (ArgumentError) lists in Phoenix.HTML templates only support iodata, and not chardata. Integers may only represent bytes. It's likely you meant to pass a string with double quotes instead of a char list with single quotes.
        (phoenix_html) lib/phoenix_html/safe.ex:67: Phoenix.HTML.Safe.List.to_iodata/1
        (phoenix_html) lib/phoenix_html/safe.ex:49: Phoenix.HTML.Safe.List.to_iodata/1
        (block_scout_web) lib/block_scout_web/templates/transaction/overview.html.eex:136: anonymous fn/3 in BlockScoutWeb.TransactionView."overview.html"/1
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (block_scout_web) lib/block_scout_web/templates/transaction/overview.html.eex:115: BlockScoutWeb.TransactionView."overview.html"/1
        (block_scout_web) lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex:2: BlockScoutWeb.TransactionInternalTransactionView."index.html"/1
        (block_scout_web) lib/block_scout_web/templates/layout/app.html.eex:39: BlockScoutWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
```

### Environment

* Operating System: Linux
* Chain: ETH
* Transaction: 0x6fb842526018ca98869ee4ae5c94aafb2a697ef5de434eb2a2770c9c1677747a

### Steps to reproduce

1. View the transaction details page for tx 0x6fb842526018ca98869ee4ae5c94aafb2a697ef5de434eb2a2770c9c1677747a

**Comment by acravenho** [comment]
Resolved by #1119
