### ISSUE TITLE
Indexer.PendingTransaction.Fetcher.task does not handle {:error, :timeout}

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/blockscout#1216]
```
2018-12-12T14:38:14.226 fetcher=pending_transaction [error] Task #PID<0.6305.0> started from Indexer.PendingTransaction.Fetcher terminating
** (CaseClauseError) no case clause matching: {:error, :timeout}
    (indexer) lib/indexer/pending_transaction/fetcher.ex:107: Indexer.PendingTransaction.Fetcher.task/1
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<2.30162585/0 in Indexer.PendingTransaction.Fetcher.handle_info/2>
    Args: []
```

Noticed and fixed in #1185.  The fix needs to be ported out into a separate PR.

**Comment by Esmat330045** [comment]
thats ok
