### ISSUE TITLE
Uncataloged token transfers with nil block number

### ISSUE THREAD

**Issue by sabondano** [poanetwork/blockscout#1227]
```
2018-12-14T21:50:06.962 [error] Task #PID<0.30811.2868> started from Indexer.TokenTransfer.Uncataloged.Worker terminating
** (ArgumentError) ranges (first..last) expect both sides to be integers, got: nil..nil
    (elixir) lib/range.ex:55: Range.new/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:302: anonymous fn/2 in Indexer.Block.Catchup.Fetcher.push_front/1
    (elixir) lib/enum.ex:3281: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1968: Enum.reduce_while/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.push_front/1
    Args: [[nil, 8994229, 8994224, 8994213, 8856521, 8856513]]
```

**Comment by KronicDeth** [comment]
Not observed recently.
