### ISSUE TITLE
Explorer.Market.History.Cataloger cannot bulk insert in < 15 seconds for Eth Mainnet

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/blockscout#1236]
```
2018-12-17T07:25:57.645 application=db_connection [error] Postgrex.Protocol (#PID<0.1730.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1771.0> timed out because it queued and checked out the connection for longer than 15000ms
2018-12-17T07:25:57.649 [error] GenServer Explorer.Market.History.Cataloger terminating
** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
    (ecto_sql) lib/ecto/adapters/sql.ex:604: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:513: Ecto.Adapters.SQL.insert_all/8
    (ecto) lib/ecto/repo/schema.ex:56: Ecto.Repo.Schema.do_insert_all/6
    (explorer) lib/explorer/market/history/cataloger.ex:48: Explorer.Market.History.Cataloger.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {#Reference<0.1823911836.2190213123.203510>, {365, 1, {:ok, [%{closing_price: #Decimal<0>, date: ~D[2017-12-17], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-18], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-19], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-20], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-21], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-22], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-23], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-24], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-25], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-26], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-27], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-28], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-29], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-30], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2017-12-31], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-01], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-02], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-03], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-04], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-05], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-06], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-07], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-08], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-09], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-10], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-11], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-12], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-13], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-14], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-15], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-16], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-17], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-18], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-19], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-20], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-21], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-22], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-23], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-24], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-25], opening_price: #Decimal<0>}, %{closing_price: #Decimal<0>, date: ~D[2018-01-26], ...}, %{closing_price: #Decimal<0>, ...}, %{...}, ...]}}}
State: %{
````

### Steps to reproduce

Run on branch with #1229, #1230, #1233, and #1235 applied to eliminate other errors logged.

### Expected behaviour

Bulk insert succeeds and `Explorer.Market.History.Cataloger` does not crash

### Actual behaviour

DB timeout occurs and `Explorer.Market.History.Cataloger` crashes and restarts.

**Comment by KronicDeth** [comment]
MIsmerge of stash for ETH Mainnet 40 test DB eliminated `:timeout` override.  This does not happen with the proper timeout from the merged PRs.
