### ISSUE TITLE
DB Migration Error

### ISSUE THREAD

**Issue by dwalintukan** [poanetwork/blockscout#1286]
**Describe your issue here.**
Receiving the following error when trying to create & migrate (or drop, create, migrate) the databases on the master branch.

```
The database for Explorer.Repo has already been created
warning: :pool_timeout option no longer has an effect and has been replaced with an improved queuing system.
See "Queue config" in DBConnection.start_link/2 documentation for more information.

  (ecto_sql) lib/ecto/adapters/sql.ex:458: Ecto.Adapters.SQL.adapter_config/1
  (ecto_sql) lib/ecto/adapters/sql.ex:445: Ecto.Adapters.SQL.init/3
  (ecto) lib/ecto/repo/supervisor.ex:189: Ecto.Repo.Supervisor.init/1
  (stdlib) supervisor.erl:295: :supervisor.init/1
  (stdlib) gen_server.erl:374: :gen_server.init_it/2
  (stdlib) gen_server.erl:342: :gen_server.init_it/6
  (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

2018-12-30T11:21:55.502 application=db_connection [error] an exception was raised logging %DBConnection.LogEntry{call: :prepare_execute, connection_time: 357000, decode_time: 3783000, params: [], pool_time: 40177000, query: %Postgrex.Query{cache: :reference, columns: nil, name: "", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, result_formats: nil, result_oids: nil, result_types: nil, statement: ["CREATE TABLE ", "IF NOT EXISTS ", [34, "schema_migrations", 34], 32, 40, [[[], [[34, "version", 34], 32, "bigint", [[], []]], ", "], [34, "inserted_at", 34], 32, ["timestamp", "(0)"], [[], []]], [", ", "PRIMARY KEY (", [[], 34, "version", 34], ")"], 41, []], types: nil}, result: {:ok, %Postgrex.Query{cache: :reference, columns: nil, name: "", param_formats: [], param_oids: [], param_types: [], ref: #Reference<0.3698157424.65011713.34000>, result_formats: [], result_oids: nil, result_types: nil, statement: ["CREATE TABLE ", "IF NOT EXISTS ", [34, "schema_migrations", 34], 32, 40, [[[], [[34, "version", 34], 32, "bigint", [[], []]], ", "], [34, "inserted_at", 34], 32, ["timestamp", "(0)"], [[], []]], [", ", "PRIMARY KEY (", [[], 34, "version", 34], ")"], 41, []], types: {Postgrex.DefaultTypes, #Reference<0.3698157424.65142785.33956>}}, %Postgrex.Result{columns: nil, command: :create_table, connection_id: 59141, messages: [%{code: "42P07", file: "parse_utilcmd.c", line: "209", message: "relation \"schema_migrations\" already exists, skipping", routine: "transformCreateStmt", severity: "NOTICE", unknown: "NOTICE"}], num_rows: 0, rows: nil}}}: ** (ArgumentError) argument error
    (stdlib) :ets.lookup(:prometheus_histogram_table, {:default, :ecto_queue_duration_microseconds, [:ok], 1})
    src/metrics/prometheus_histogram.erl:196: :prometheus_histogram.observe/4
    lib/explorer/repo/prometheus_logger.ex:8: Explorer.Repo.PrometheusLogger.log/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (db_connection) lib/db_connection.ex:1311: DBConnection.log/5
    (postgrex) lib/postgrex.ex:182: Postgrex.query_prepare_execute/4
    (ecto_sql) lib/ecto/adapters/sql.ex:291: Ecto.Adapters.SQL.query!/4
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:691: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migrator.ex:485: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql) lib/ecto/migrator.ex:269: Ecto.Migrator.run/4
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:94: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) src/elixir_compiler.erl:71: :elixir_compiler.dispatch/4
    (elixir) src/elixir_compiler.erl:68: :elixir_compiler.compile/3
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
    (elixir) src/elixir_compiler.erl:23: :elixir_compiler.quoted/2

2018-12-30T11:21:55.521 application=db_connection [error] an exception was raised logging %DBConnection.LogEntry{call: :begin, connection_time: 299000, decode_time: nil, params: nil, pool_time: 27000, query: :begin, result: {:ok, %DBConnection{conn_mode: nil, conn_ref: #Reference<0.3698157424.65011713.34123>, pool_ref: {:pool_ref, #PID<0.347.0>, #Reference<0.3698157424.65142785.33807>, nil, #Reference<0.3698157424.65142785.33998>, #Reference<0.3698157424.65011713.34122>}}, %Postgrex.Result{columns: nil, command: :commit, connection_id: 59140, messages: [], num_rows: nil, rows: nil}}}: ** (ArgumentError) argument error
    (stdlib) :ets.lookup(:prometheus_histogram_table, {:default, :ecto_queue_duration_microseconds, [:ok], 1})
    src/metrics/prometheus_histogram.erl:196: :prometheus_histogram.observe/4
    lib/explorer/repo/prometheus_logger.ex:8: Explorer.Repo.PrometheusLogger.log/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (db_connection) lib/db_connection.ex:1311: DBConnection.log/5
    (db_connection) lib/db_connection.ex:772: DBConnection.transaction/3
    (ecto_sql) lib/ecto/adapters/sql.ex:707: Ecto.Adapters.SQL.lock_for_migrations/5
    (ecto_sql) lib/ecto/migrator.ex:317: Ecto.Migrator.lock_for_migrations/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:94: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) src/elixir_compiler.erl:71: :elixir_compiler.dispatch/4
    (elixir) src/elixir_compiler.erl:68: :elixir_compiler.compile/3
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
    (elixir) src/elixir_compiler.erl:23: :elixir_compiler.quoted/2
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/cli.ex:503: Kernel.CLI.wrapper/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2

2018-12-30T11:21:55.538 application=db_connection [error] an exception was raised logging %DBConnection.LogEntry{call: :prepare_execute, connection_time: 749000, decode_time: 7000, params: [], pool_time: nil, query: %Postgrex.Query{cache: :reference, columns: nil, name: "ecto_834", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, result_formats: nil, result_oids: nil, result_types: nil, statement: "SELECT s0.\"version\"::bigint FROM \"schema_migrations\" AS s0 FOR UPDATE", types: nil}, result: {:ok, %Postgrex.Query{cache: :reference, columns: ["version"], name: "ecto_834", param_formats: [], param_oids: [], param_types: [], ref: #Reference<0.3698157424.65011713.34172>, result_formats: [:binary], result_oids: [20], result_types: [Postgrex.Extensions.Int8], statement: "SELECT s0.\"version\"::bigint FROM \"schema_migrations\" AS s0 FOR UPDATE", types: {Postgrex.DefaultTypes, #Reference<0.3698157424.65142785.33956>}}, %Postgrex.Result{columns: ["version"], command: :select, connection_id: 59140, messages: [], num_rows: 41, rows: [[20180117221921], [20180117221922], [20180117221923], [20180212222309], [20180221001948], [20180424203101], [20180508183700], [20180508191045], [20180518221256], [20180522154252], [20180522154253], [20180606135149], [20180606135150], [20180626143840], [20180717204948], [20180817021704], [20180821142139], [20180917182319], [20180918200001], [20180919175123], [20181008195723], [20181011193212], [20181015173318], [20181015173319], [20181016163236], [20181017141409], [20181024141113], [20181024164623], [20181024172010], [20181026180921], [20181029174420], [20181106152300], [20181107164103], [...], ...]}}}: ** (ArgumentError) argument error
    (stdlib) :ets.lookup(:prometheus_histogram_table, {:default, :ecto_db_query_duration_microseconds, [:ok], 1})
    src/metrics/prometheus_histogram.erl:196: :prometheus_histogram.observe/4
    lib/explorer/repo/prometheus_logger.ex:8: Explorer.Repo.PrometheusLogger.log/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (db_connection) lib/db_connection.ex:1311: DBConnection.log/5
    (ecto_sql) lib/ecto/adapters/sql.ex:545: Ecto.Adapters.SQL.execute!/4
    (ecto_sql) lib/ecto/adapters/sql.ex:537: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
    (ecto_sql) lib/ecto/migrator.ex:317: anonymous fn/3 in Ecto.Migrator.lock_for_migrations/3
    (ecto_sql) lib/ecto/adapters/sql.ex:798: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1349: DBConnection.run_transaction/4
    (ecto_sql) lib/ecto/adapters/sql.ex:707: Ecto.Adapters.SQL.lock_for_migrations/5
    (ecto_sql) lib/ecto/migrator.ex:317: Ecto.Migrator.lock_for_migrations/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:94: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) src/elixir_compiler.erl:71: :elixir_compiler.dispatch/4

2018-12-30T11:21:55.548 application=ecto_sql [info] Already up
2018-12-30T11:21:55.596 application=db_connection [error] an exception was raised logging %DBConnection.LogEntry{call: :commit, connection_time: 43400000, decode_time: nil, params: nil, pool_time: nil, query: :commit, result: {:ok, %Postgrex.Result{columns: nil, command: :commit, connection_id: 59140, messages: [], num_rows: nil, rows: nil}}}: ** (ArgumentError) argument error
    (stdlib) :ets.lookup(:prometheus_histogram_table, {:default, :ecto_db_query_duration_microseconds, [:ok], 1})
    src/metrics/prometheus_histogram.erl:196: :prometheus_histogram.observe/4
    lib/explorer/repo/prometheus_logger.ex:8: Explorer.Repo.PrometheusLogger.log/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (db_connection) lib/db_connection.ex:1311: DBConnection.log/5
    (db_connection) lib/db_connection.ex:1371: DBConnection.run_transaction/4
    (ecto_sql) lib/ecto/adapters/sql.ex:707: Ecto.Adapters.SQL.lock_for_migrations/5
    (ecto_sql) lib/ecto/migrator.ex:317: Ecto.Migrator.lock_for_migrations/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:94: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) src/elixir_compiler.erl:71: :elixir_compiler.dispatch/4
    (elixir) src/elixir_compiler.erl:68: :elixir_compiler.compile/3
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
    (elixir) src/elixir_compiler.erl:23: :elixir_compiler.quoted/2
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/cli.ex:503: Kernel.CLI.wrapper/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating System: Mac OS Mojave 10.14.2

### Steps to reproduce

1. Pull latest master branch
2. Setup default config #3 step in README
3. Install dependencies #4 step
4. Create and migrate databases #5 step

### Expected behaviour

Expect for no errors when doing the migrations.

### Actual behaviour

A bunch of error messages pop up when migrating the DB.

**Comment by acravenho** [comment]
@dwalintukan Please take a look at the new `dev.secret.exs` file: https://github.com/poanetwork/blockscout/blob/master/apps/explorer/config/dev.secret.exs.example

## Before Ecto 3 upgrade:

```
use Mix.Config

# Configure your database
config :explorer, Explorer.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "explorer_dev",
  hostname: "localhost",
  username: "postgres",
  password: "<REPLACE WITH THE PASSWORD YOU CHOSE>",
  loggers: [Explorer.Repo.PrometheusLogger],
  pool_size: 20,
  pool_timeout: 60_000,
  timeout: 80_000
```

## After Ecto 3 Upgrade

```
use Mix.Config

# Configure your database
config :explorer, Explorer.Repo,
  database: "explorer_dev",
  hostname: "localhost",
  username: "postgres",
  password: "<REPLACE WITH THE PASSWORD YOU CHOSE>",
  pool_size: 20,
  timeout: 80_000
```

Notice that `adapter: Ecto.Adapters.Postgres,`, `pool_timeout: 60_000,`, and `loggers: [Explorer.Repo.PrometheusLogger],` were removed very recently. Simply update your `dev.secret.exs` file to reflect these removals.

**Comment by dwalintukan** [comment]
Removing the adapter, pool_timeout, and loggers fixed it. Cheers!

**Comment by acravenho** [comment]
@dwalintukan I'm glad that fixed the issue. If you're interested in adding your explorer URL to our README (https://github.com/poanetwork/blockscout#projects-utilizing-blockscout), please let me know. 👍

**Comment by dwalintukan** [comment]
@acravenho Will let you know when we are ready to be added! We are closed source currently for development and testing. Thanks!
