### ISSUE TITLE
recover_pub_key/2 error using Indexer.Block.Transform.Clique.transform

### ISSUE THREAD

**Issue by dwalintukan** [poanetwork/blockscout#1294]
Seems directly related to #1352.

*Describe your issue here.*

Receiving this error when trying to index with `Indexer.Block.Transform.Clique`.

```
2019-01-02T16:42:35.055 application=indexer fetcher=block_catchup first_block_number=6 last_block_number=0 [error] ** (MatchError) no match of right hand side value: {:error, 'ecdsa recovery problem'}
    (indexer) lib/indexer/block/util.ex:69: Indexer.Block.Util.recover_pub_key/2
    (indexer) lib/indexer/block/transform/clique.ex:12: Indexer.Block.Transform.Clique.transform/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (indexer) lib/indexer/block/fetcher.ex:105: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:183: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

It seems the signature param is an empty byte array:
```
# defp recover_pub_key(signature_hash, signature) do

# signature hash
<<4, 240, 110, 22, 162, 112, 68, 243, 32, 116, 195, 28, 110, 14, 66, 223, 6,
  136, 209, 210, 227, 48, 233, 128, 177, 131, 188, 71, 205, 19, 225, 209>>
# signature
<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating System: Mac OSX Mojave 10.14.2

### Steps to reproduce

Use `Indexer.Block.Transform.Clique` and index from scratch a POA network.

### Expected behaviour

No error messages.

### Actual behaviour

The error message pops up when indexing.

**Comment by dwalintukan** [comment]
So it looks like this is related to only the genesis block where the extra data parsing is different than other blocks.

Genesis block extraData:
```
0x000000000000000000000000000000000000000000000000000000000000000060afa8f21f3dba79f3dc9708bc890056c286e7a48102c0ecece895b8fefbddf42b95b7a20925b0c80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

Other block extraData:
```
0xd883010812846765746888676f312e31312e33856c696e75780000000000000080cb10695d8991ba60820ceaae01da8f08f051d5f3cfc919ddd5a9c059a26ced212957bef8687d9a130c51de8a7273d9f635b45be92fda60d8cc727b25ac7ab100
```

**Comment by dwalintukan** [comment]
It seems to have been fixed after I deleted and reinstalled my node modules. There was an issue with the keccak module which seems directly related to my issue. If any of you have any issues, delete and reinstall the node modules again and make sure you are running Node 9.

**Comment by acravenho** [comment]
Thank you for the update @dwalintukan. Most of us are running Node 10+ currently, but it appears 9 works as well. :+1:

**Comment by dwalintukan** [comment]
Sorry it appears to be still an issue. Looks like the error pops up when the indexer is doing `block_catchup`.

```
2019-01-03T10:12:31.892 application=indexer fetcher=block_catchup first_block_number=481493 last_block_number=0 missing_block_count=7 shrunk=false [info] Index had to catch up.
2019-01-03T10:12:31.892 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
2019-01-03T10:12:34.998 application=indexer fetcher=block_catchup first_block_number=6 last_block_number=0 [error] ** (MatchError) no match of right hand side value: {:error, 'ecdsa recovery problem'}
    (indexer) lib/indexer/block/util.ex:66: Indexer.Block.Util.recover_pub_key/2
    (indexer) lib/indexer/block/transform/clique.ex:12: Indexer.Block.Transform.Clique.transform/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (indexer) lib/indexer/block/fetcher.ex:105: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:183: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3


Retrying.
```

**Comment by dwalintukan** [comment]
Here is the stacktrace when I try to `npm install` using Node 10 for the explorer modules.

```
> keccak@1.4.0 install /Users/deric/coding/naka-explorer/apps/explorer/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild /Users/deric/coding/naka-explorer/apps/explorer/node_modules/keccak
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/keccak/src/addon.o
In file included from ../src/addon.cc:2:
../../nan/nan.h:1081:96: error: too many arguments to function call, expected at most 4, have 5
        length_ = string->WriteUtf8(v8::Isolate::GetCurrent(), str_, static_cast<int>(len), 0, flags);
                  ~~~~~~~~~~~~~~~~~                                                            ^~~~~
/Users/deric/.node-gyp/10.9.0/include/node/v8.h:2645:3: note: 'WriteUtf8' declared here
  int WriteUtf8(char* buffer,
  ^
1 error generated.
make: *** [Release/obj.target/keccak/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/deric/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/deric/.nvm/versions/node/v10.9.0/bin/node" "/Users/deric/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/deric/coding/naka-explorer/apps/explorer/node_modules/keccak
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deric/.npm/_logs/2019-01-03T18_15_16_127Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.
added 76 packages from 30 contributors and audited 91 packages in 4.363s
found 0 vulnerabilities
```

**Comment by vbaranov** [comment]
@dwalintukan Is this still relevant?

**Comment by dwalintukan** [comment]
@vbaranov let me test this on the latest release.

**Comment by vbaranov** [comment]
@dwalintukan how is it going? Are you still experiencing this issue?

**Comment by dwalintukan** [comment]
@vbaranov Sorry I haven’t had a chance to test this out. I’ll close it for now and when I get around to updating to the latest release I’ll reopen it if it persists. Thanks!
