### ISSUE TITLE
Explorer.Chain.Import.Runner.Address.CurrentTokenBalances lacks ordering before insert, so it can deadblock

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/blockscout#1295]
```
** (Postgrex.Error) ERROR 40P01 (deadlock_detected) deadlock detected

    hint: See server log for query details.

Process 99980 waits for ShareLock on transaction 5009099; blocked by process 99976.
Process 99976 waits for ShareLock on transaction 5009100; blocked by process 99980. 
    (ecto_sql) lib/ecto/adapters/sql.ex:604: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:513: Ecto.Adapters.SQL.insert_all/8
    (ecto) lib/ecto/repo/schema.ex:56: Ecto.Repo.Schema.do_insert_all/6
    (explorer) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain/import.ex:285: Explorer.Chain.Import.insert_changes_list/3
    (explorer) lib/explorer/chain/import/runner/address/current_token_balances.ex:64: Explorer.Chain.Import.Runner.Address.CurrentTokenBalances.insert/3
    (ecto) lib/ecto/multi.ex:580: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:564: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql) lib/ecto/adapters/sql.ex:798: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1349: DBConnection.run_transaction/4
    (ecto) lib/ecto/repo/transaction.ex:16: Ecto.Repo.Transaction.transaction/3
    (stdlib) timer.erl:197: :timer.tc/3
    (explorer) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer) lib/explorer/chain/import.ex:316: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
    (elixir) lib/enum.ex:3281: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1968: Enum.reduce_while/3
    (explorer) lib/explorer/chain/import.ex:315: Explorer.Chain.Import.import_transactions/2
```

### Steps to reproduce

* Indexer ETH Mainnet

### Expected behaviour

Changes lists are ordered before insert so row locks are taken in a consistent order that doesn't allow for deadlocks
 
### Actual behaviour

Deadlock

**Comment by KronicDeth** [comment]
It looks like the current `unique_token_balances` call was in there from the beginning of `CurrentTokenBalances`.
