### ISSUE TITLE
Chain sync fails on POA network with empty steps on:  entry_to_elixir function

### ISSUE THREAD

**Issue by 0x-genesys** [poanetwork/blockscout#1424]
*Describe your issue here.*

My chain is not syncing. it has emptySteps enabled. Im using Parity

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 21
* Operating System: Ubuntu 16.04

### Steps to reproduce

```
2019-02-08T12:48:04.611 fetcher=block_catchup first_block_number=1117 last_block_number=1108 [error] Task #PID<0.12463.0> started from #PID<0.12460.0> terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/block.ex:434: EthereumJSONRPC.Block.entry_to_elixir({"emptySteps", "[]"})
    (elixir) lib/map.ex:210: Map.new_transform/3
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:394: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer) lib/indexer/block/fetcher.ex:105: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:183: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<12.16898646/1 in Indexer.Block.Catchup.Fetcher.stream_fetch_and_import/2>, [1117..1108]]
2019-02-08T12:48:04.613 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({%FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :entry_to_elixir, kind: nil, module: EthereumJSONRPC.Block}, [{EthereumJSONRPC.Block, :entry_to_elixir, [{"emptySteps", "[]"}], [file: 'lib/ethereum_jsonrpc/block.ex', line: 434]}, {Map, :new_transform, 3, [file: 'lib/map.ex', line: 210]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1314]}, {EthereumJSONRPC.Blocks, :from_responses, 2, [file: 'lib/ethereum_jsonrpc/blocks.ex', line: 44]}, {EthereumJSONRPC, :fetch_blocks_by_params, 3, [file: 'lib/ethereum_jsonrpc.ex', line: 394]}, {Indexer.Block.Fetcher, :fetch_and_import_range, 2, [file: 'lib/indexer/block/fetcher.ex', line: 105]}, {Indexer.Block.Catchup.Fetcher, :fetch_and_import_range_from_sequence, 3, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 183]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}). Restarting
2019-02-08T12:48:04.615 [error] GenServer :block_catchup_sequencer terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Block.entry_to_elixir/1
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/block.ex:434: EthereumJSONRPC.Block.entry_to_elixir({"emptySteps", "[]"})
    (elixir) lib/map.ex:210: Map.new_transform/3
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/blocks.ex:44: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:394: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer) lib/indexer/block/fetcher.ex:105: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:183: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I saw this issue : https://github.com/poanetwork/blockscout/issues/1041

however the file has changed since then. cant find where to add necessary enum emptySteps

**Comment by 0x-genesys** [comment]
got this fixed by : 

 ```
 defp entry_to_elixir({key, _} = entry)
       when key in ~w(author extraData hash logsBloom miner mixHash nonce parentHash receiptsRoot sealFields sha3Uncles
                     signature stateRoot step transactionsRoot uncles emptySteps),
       do: entry
```

on line 443 of blockscout/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex


then dropping the database

and remigrating / index

Not sure why haven't blockscout devs fixed it yet so not submitting a PR
