### ISSUE TITLE
Geth archive node: required historical state unavailable (reexec=128)

### ISSUE THREAD

**Issue by brianmcmichael** [poanetwork/blockscout#1433]
Logs filling with `required historical state unavailable (reexec=128)` errors on Geth full archive node. CPU(s) are at 100% while this is happening. Application has been in this state for several days.

Errors appear in both `logs/dev/error.log` and `logs/dev/indexer.log`. Error as follows:

```
2019-02-11T21:02:06.179 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for transactions: [%{code: -32000, data: %{block_number: 141791, transaction_hash: "0xd0f4464005062d65b2b7aa3ae9139b08851d6ecdf38999c49fdaddeb3ad195ca", transaction_index: 4}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 142023, transaction_hash: "0x42686b531bfa7fd51ccfd5faac11d7a59ab3f1eb395bd5145b0301da6ccb1d4f", transaction_index: 10}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 142021, transaction_hash: "0xdcd7e2abcffc1baf19219353b1a07db8e07148d62b48d0c8760ec629eb8ef5de", transaction_index: 5}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 143151, transaction_hash: "0x6b4e208a8e615a37684c1072e42948ef2970209ca77515395f8cc502c3db6f71", transaction_index: 7}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 143150, transaction_hash: "0x6bb8a065ee3e90df03daf4ebb4bd7512eb8ddbfcf528b857f313f0767abb8f34", transaction_index: 1}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 141770, transaction_hash: "0x32ec7910f2faac5693ec2d443de7671aa02b9489eba6fce7f45266ea1e2f1650", transaction_index: 1}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 141789, transaction_hash: "0x4975ddc763b6bf0dfd463f1719f0daddd7b81b0cdc4965f1b685c8543922b190", transaction_index: 7}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 141796, transaction_hash: "0x941219030dd991254a6fc1936ef0afe904f844e98018a5e436c1911598c802cc", transaction_index: 0}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 141787, transaction_hash: "0x4d5a334c7586a4d2130a6ad428654e4ec0edcf1201255a487c775ceed9e9da4b", transaction_index: 6}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 141789, transaction_hash: "0x68c5677eb8b35ab4224176fd3f3159a2c78af4ae668b9cd622617330b80fc433", transaction_index: 9}, message: "required historical state unavailable (reexec=128)"}]
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 20)
```

* Operating System: `Ubuntu 18.04`

### Steps to reproduce

Using geth 1.8.22-stable with a clique network. Node should be operating in full mode with GC disabled. See head of `config.toml`:

```
geth@ooo-explorer-1:~$ head config.toml 
[Eth]
NetworkId = 180918
SyncMode = "full"
NoPruning = true
LightPeers = 100
DatabaseCache = 1024
TrieCleanCache = 512
TrieDirtyCache = 512
TrieTimeout = 3600000000000
MinerGasFloor = 8000000
```

### Expected behaviour

Blockchain is indexed. Minimal error messages.

### Actual behaviour

Everything seems to be working fine on the frontend, however, the backend is quite active and creating 100% cpu utilization. I'm not sure why the historical state is unavailable, and it's not clear if the application is attempting to retry getting the transaction information after the historical state is reconstructed. I'm not sure that the historical state check is an error in blockscout, but I'm also not sure what's happening behind the scenes that's causing all of the resource consumption.

**Comment by acravenho** [comment]
With Geth you can only fetch the last 128 blocks of archive history:

From the release notes:

"Tracing and pruning: By default, state for the last 128 blocks kept in memory. Most states are garbage collected. If you are running a block explorer or other service relying on transaction tracing without an archive node (--gcmode=archive), you need to trace within this window! "

**Comment by brianmcmichael** [comment]
I'm not sure what the indexer is doing in this case, we've been at 100% CPU for a week and I have to keep nuking the blockscout logs to keep from filling the disk. Seems like a geth issue (we are running `--gcmode=archive`) so maybe the indexer needs some handling preventing checks on older blocks. 

I need to confirm but it looks like geth may be initially throwing the reexec error but then rebuilding the block history anyways, so a subsequent request may get the transaction data, but I don't know how long it stays cached.

**Comment by brianmcmichael** [comment]
:tada: Wow, thanks for the fast turnaround!

**Comment by brianmcmichael** [comment]
Still seeing this error in indexer.log after update/upgrade to 1.3.5. I just noticed that there was a 1.3.6 release an hour ago though, not sure if it touched the issue.

```
...
2019-03-19T16:33:03.245 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for transactions: [%{code: -32000, data: %{block_number: 253136, transaction_hash: "0x9a3e2261ccbc0bcb8cf0e0544bcc6dd3b5c009c85679f24d23a488a7c0d1be8e", transaction_index: 0}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 227194, transaction_hash: "0xf1a92e17f5863d1d3b2aba7e14fedb28659887163ec354732a2707358e2f3c7b", transaction_index: 0}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 229484, transaction_hash: "0xa6ed5d8ccfd232dd8c54affc87512639da30c580d8fc07ff86b2b267a2d571a8", transaction_index: 0}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 227193, transaction_hash: "0xa4a7b25c32a92562a992a20f7aba5529239647a0703de719f25bb3e506ce7bfd", transaction_index: 0}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 167502, transaction_hash: "0x5a2cc8a05af9ceaa9bb7a7684412d60e6429ff015d00e4c2c4b44b17e4e49619", transaction_index: 0}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 203622, transaction_hash: "0x1f6fa4bfc316f67a2376db62fd3f21bf2e66361e1901a0a456c9a7fea2ade82e", transaction_index: 0}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 141766, transaction_hash: "0xcd75131b9a28cd5b9fd317e088a858f2589e41df407d274fc593aca3c2e74a3f", transaction_index: 2}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 107144, transaction_hash: "0xbc577a1ea0f450ce023e2ba126b6a79724a4b7ebc9f89f2eee9b76623668188f", transaction_index: 0}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 407537, transaction_hash: "0x8a6bdfcc170f03ae95d1ea075f9daef44fdb754dc771a533821e0b2e53656687", transaction_index: 0}, message: "required historical state unavailable (reexec=128)"}, %{code: -32000, data: %{block_number: 142023, transaction_hash: "0x0a12ee8e4d4b75817a2f07327dfe612a507d56361bbbef6cbf93bdb26b985ec7", transaction_index: 4}, message: "required historical state unavailable (reexec=128)"}]
2019-03-19T16:33:03.246 application=indexer fetcher=internal_transaction count=10 [debug] fetching internal transactions for transactions
...
```

**Comment by ayrat555** [comment]
@brianmcmichael are you still experiencing this issue?

**Comment by vbaranov** [comment]
@ayrat555 me too. The same error is in Rinkeby instance.

**Comment by ayrat555** [comment]
locally I reproduced this issue for Rinkeby only for new blocks. I think the problem is related to pending transactions or new/pending blocks. @brianmcmichael Are you seeing the error only on new blocks in your chain?

**Comment by bianchi2** [comment]
Weird, I do not see the fix in master anymore
Here's the fix: https://github.com/poanetwork/blockscout/pull/1487/files#diff-a50927a7856ff08c87590dbacff71d4dR34
and this is what's in master https://github.com/poanetwork/blockscout/blob/master/apps/indexer/lib/indexer/block/catchup/fetcher.ex#L37

**Comment by vbaranov** [comment]
@bianchi2 it is in master actually. That limit was moved to `apps/indexer/lib/indexer/block/fetcher.ex` in this commit https://github.com/poanetwork/blockscout/commit/f02e2d8841a48d6cfe6599f6c4b955093fb692c3#diff-b93311ed01a133c672770de1e9416565R70

**Comment by bianchi2** [comment]
@vbaranov thanks. I did see the described behavior though. Cannot reproduce now as I flushed local geth storage. I'll post more details if I encounter the error again.

**Comment by leovigna** [comment]
I have similar issues as well. My archival node is synced but doesn't seem to have all states stored.

**Comment by rrodriguezreche** [comment]
This is still happening

**Comment by bglmmz** [comment]
> debug.traceTransaction("0x2d7d0fb6b3b0a5f5e7f58f5a4fd46fdf2507daea16cae76ce4d19e6e40611c8f")
Error: required historical state unavailable (reexec=128)
    at web3.js:3456:20
    at web3.js:6304:15
    at web3.js:5410:36
    at <anonymous>:1:1

**Comment by ranyong321** [comment]
Hello friends, I have the same problem, the server has been printing this log like crazy, it should be solved over the weekend, please

**Comment by ranyong321** [comment]
Hello friends, I also have the same problem, the server has been printing this log like crazy, how can I solve it, please
