### ISSUE TITLE
value too long for type character varying(255)

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1497]
The `constructor_arguments` column in the `smart_contracts` table should be type `test` not `varchar(255)`. 

```
Request: POST /address/0x152d57780ff1da6fa08e2c4bc4c739ea6f001e8c/contract_verifications
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 22001 (string_data_right_truncation) value too long for type character varying(255)
        (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto) lib/ecto/repo/schema.ex:651: Ecto.Repo.Schema.apply/4
        (ecto) lib/ecto/repo/schema.ex:264: anonymous fn/15 in Ecto.Repo.Schema.do_insert/3
        (ecto) lib/ecto/multi.ex:580: Ecto.Multi.apply_operation/5
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/multi.ex:564: anonymous fn/5 in Ecto.Multi.apply_operations/5
        (ecto_sql) lib/ecto/adapters/sql.ex:814: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
        (db_connection) lib/db_connection.ex:1349: DBConnection.run_transaction/4
```

**Comment by acravenho** [comment]
This has been altered on `core` and now allows users to verify their smart contracts.
