### ISSUE TITLE
Cardinality violation while importing block_rewards

### ISSUE THREAD

**Issue by goodsoft** [poanetwork/blockscout#1584]
The following error appears in catchup fetcher for some blocks:
```
2019-03-17T21:47:50.958 application=explorer fetcher=block_catchup first_block_number=7374455 last_block_number=7374455 import_id=9154 transaction_id=196 [error] Could not insert all of chunk into Elixir.Explorer.Chain.Block.Reward using options because of error. 

Chunk Size: 3
Chunk:

[%{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<90, 11, 84, 213, 220, 23, 224, 170, 220, 56, 61, 45, 180, 59, 10, 13, 62, 2, 156, 76>>}, address_type: :validator, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<27, 111, 185, 154, 240, 181, 26, 246, 104, 90, 25, 27, 47, 123, 203, 166, 132, 248, 86, 86, 41, 191, 8, 76, 112, 178, 83, 4, 121, 64, 116, 85>>}, inserted_at: #DateTime<2019-03-17 19:47:50.793266Z>, reward: #Explorer.Chain.Wei<2152679121222061300>, updated_at: #DateTime<2019-03-17 19:47:50.793266Z>}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<234, 103, 79, 221, 231, 20, 253, 151, 157, 227, 237, 240, 245, 106, 169, 113, 107, 137, 142, 200>>}, address_type: :uncle, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<27, 111, 185, 154, 240, 181, 26, 246, 104, 90, 25, 27, 47, 123, 203, 166, 132, 248, 86, 86, 41, 191, 8, 76, 112, 178, 83, 4, 121, 64, 116, 85>>}, inserted_at: #DateTime<2019-03-17 19:47:50.793266Z>, reward: #Explorer.Chain.Wei<1750000000000000000>, updated_at: #DateTime<2019-03-17 19:47:50.793266Z>}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<234, 103, 79, 221, 231, 20, 253, 151, 157, 227, 237, 240, 245, 106, 169, 113, 107, 137, 142, 200>>}, address_type: :uncle, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<27, 111, 185, 154, 240, 181, 26, 246, 104, 90, 25, 27, 47, 123, 203, 166, 132, 248, 86, 86, 41, 191, 8, 76, 112, 178, 83, 4, 121, 64, 116, 85>>}, inserted_at: #DateTime<2019-03-17 19:47:50.793266Z>, reward: #Explorer.Chain.Wei<1500000000000000000>, updated_at: #DateTime<2019-03-17 19:47:50.793266Z>}]

Options:

[conflict_target: [:address_hash, :address_type, :block_hash], on_conflict: #Ecto.Query<from r0 in Explorer.Chain.Block.Reward, where: fragment("EXCLUDED.reward IS DISTINCT FROM ?", r0.reward), update: [set: [reward: fragment("EXCLUDED.reward")]]>, returning: true, timeout: 60000, timestamps: %{inserted_at: #DateTime<2019-03-17 19:47:50.793266Z>, updated_at: #DateTime<2019-03-17 19:47:50.793266Z>}]

Exception:

** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time

    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
    (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:529: Ecto.Adapters.SQL.insert_all/8
    (ecto) lib/ecto/repo/schema.ex:56: Ecto.Repo.Schema.do_insert_all/6
    (explorer) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain/import.ex:285: Explorer.Chain.Import.insert_changes_list/3
    (ecto) lib/ecto/multi.ex:580: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3

2019-03-17T21:47:50.961 application=indexer fetcher=block_catchup first_block_number=7374455 last_block_number=7374455 [error] ** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time

    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
    (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:529: Ecto.Adapters.SQL.insert_all/8
    (ecto) lib/ecto/repo/schema.ex:56: Ecto.Repo.Schema.do_insert_all/6
    (explorer) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain/import.ex:285: Explorer.Chain.Import.insert_changes_list/3
    (ecto) lib/ecto/multi.ex:580: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3


Retrying.
```

Beneficiaries in question:
```
%EthereumJSONRPC.FetchedBeneficiaries{
  errors: [],
  params_set: #MapSet<[
    %{
      address_hash: "0x5a0b54d5dc17e0aadc383d2db43b0a0d3e029c4c",
      address_type: :validator,
      block_hash: "0x1b6fb99af0b51af6685a191b2f7bcba684f8565629bf084c70b2530479407455",
      block_number: 7374455,
      reward: "0x1d7d843dc3b48000"
    },
    %{
      address_hash: "0xea674fdde714fd979de3edf0f56aa9716b898ec8", 
      address_type: :uncle,
      block_hash: "0x1b6fb99af0b51af6685a191b2f7bcba684f8565629bf084c70b2530479407455",
      block_number: 7374455,
      reward: "0x14d1120d7b160000"
    },
    %{
      address_hash: "0xea674fdde714fd979de3edf0f56aa9716b898ec8",
      address_type: :uncle,
      block_hash: "0x1b6fb99af0b51af6685a191b2f7bcba684f8565629bf084c70b2530479407455",
      block_number: 7374455,
      reward: "0x18493fba64ef0000"
    }
  ]>
}

```
Note the same address being rewarded for the two uncle blocks.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): `Elixir 1.8.0 (compiled with Erlang/OTP 21)`
* Operating System: Linux

### Steps to reproduce

Hardcode the block to fetch in `apps/indexer/lib/indexer/block/catchup/fetcher.ex`:
```
        first = 7374455
        last = 7374455
```

Run the indexer

### Expected behaviour

Blocks are successfully imported.

### Actual behaviour

The error above occurs.

**Comment by goodsoft** [comment]
By they way, the block itself is completely abandoned and unavailable on production website: https://blockscout.com/eth/mainnet/blocks/7374455/transactions

As for the reasons, the doc in `Explorer.Chain.Block.Reward` says:
```
  * `:block_hash` - Hash of the validated block
```
So, as far as I understand, we should have saved the hash of the uncle block this address validated, but in reality we save there the hash of the current, i.e. "nephew" block.

In this case we'll most probably need to re-fetch beneficiaries for all blocks, as incorrect hashes have been saved for their beneficiaries.

**Comment by goodsoft** [comment]
Looking more into this I discovered that `block_hash` is expected to be a hash of the "nephew" block, and there's another fetcher dedicated to rewards, which has [`reduce_uncle_rewards`](https://github.com/poanetwork/blockscout/blob/master/apps/indexer/lib/indexer/block/reward/fetcher.ex#L202-L232) function, which sums reward to same addresses.
Thus, the correct solution would be to use the same `reduce_uncle_rewards` in catchup fetcher.
