### ISSUE TITLE
(Bug) Realtime.Fetcher doesn't handle simple coins transfer with ganache

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1587]
```
2019-03-18T14:50:46.879 [error] Task #PID<0.983.0> started from Indexer.Block.Realtime.Fetcher terminating
** (BadMapError) expected a map, got: {"gas", 0}
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/geth.ex:81: anonymous fn/4 in EthereumJSONRPC.Geth.debug_trace_transaction_response_to_internal_transactions_params/2
    (elixir) lib/enum.ex:1331: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:3015: anonymous fn/3 in Enum.map/2
    (elixir) lib/stream.ex:1556: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir) lib/stream.ex:1047: anonymous fn/3 in Stream.with_index/2
    (elixir) lib/enum.ex:3350: Enumerable.Map.reduce_list/3
    (elixir) lib/stream.ex:1568: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:3015: Enum.map/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/geth.ex:80: EthereumJSONRPC.Geth.debug_trace_transaction_response_to_internal_transactions_params/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/geth.ex:68: EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:384: Indexer.Block.Realtime.Fetcher.internal_transactions/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:181: Indexer.Block.Realtime.Fetcher.import/2
    (indexer) lib/indexer/block/fetcher.ex:133: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:266: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:249: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [2, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, false]
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): `Elixir 1.8.1 (compiled with Erlang/OTP 21)`
* Operating System: `Mac OS Mojave 10.14.3 (18D109)`
* ganache-cli  version (`ganache-cli --version`): Ganache CLI v6.1.6 (ganache-core: 2.1.5)

### Steps to reproduce

Run Blockscout locally with `ganache-cli` from the master branch (This commit is the latest at the time of the issue reproduction: https://github.com/poanetwork/blockscout/commit/fdc94c8bb8e00ab856db3e004f5128f735333487)

```
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
export ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545
export ETHEREUM_JSONRPC_WS_URL=ws://localhost:8545
export ETHEREUM_JSONRPC_VARIANT=geth
```

Make a simple coins transfer from ganache acc1 to acc2 with Nifty Wallet or MetaMask.
As a result, you will see an aforementioned error. The transactions will not be displayed in the Blockscout.

### Expected behaviour

The error shouldn't arise. The transaction should display in Blockscout UI.

### Actual behaviour

The error exists. The transaction doesn't display in Blockscout UI.

**Comment by vbaranov** [comment]
@goodsoft 

I've attached geth to ganache with `geth attach http://127.0.0.1:8545`
My env vars set looks like:
```
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
export ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545
export ETHEREUM_JSONRPC_WS_URL=ws://localhost:8545
export ETHEREUM_JSONRPC_VARIANT=geth
export LOGO=/images/sokol_logo.svg
export NETWORK="(POA)"
export SUBNETWORK="Sokol Testnet"
export LINK_TO_OTHER_EXPLORERS=false
export COIN=POA
export NETWORK_ICON=_test_network_icon.html
export NETWORK_PATH=/
export BLOCKSCOUT_VERSION=v1.3.5-beta
export RELEASE_LINK=https://github.com/poanetwork/blockscout/releases/tag/v1.3.5-beta
export BLOCK_TRANSFORMER=base
unset VALIDATORS_CONTRACT
unset METADATA_CONTRACT
```

**Comment by vbaranov** [comment]
geth version:

```
MacBook-Pro-Viktor:BS keys viktor$ geth version
Geth
Version: 1.8.22-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.11.5/libexec
```

**Comment by goodsoft** [comment]
So the indexer is connected to Geth, which is in turn connected to Ganache?

**Comment by vbaranov** [comment]
>So the indexer is connected to Geth, which is in turn connected to Ganache?

Absolutely right
