### ISSUE TITLE
internal_transactions_indexed_at_blocks is already a member of the Ecto.Multi

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1680]
```
2019-03-28T21:18:48.251 fetcher=internal_transaction count=10 [error] Task #PID<0.15072.13> started from Indexer.InternalTransaction.Fetcher terminating
** (RuntimeError) :internal_transactions_indexed_at_blocks is already a member of the Ecto.Multi:
%Ecto.Multi{names: #MapSet<[:internal_transactions, :internal_transactions_indexed_at_blocks, :internal_transactions_indexed_at_transactions]>, operations: [internal_transactions_indexed_at_blocks: {:run, #Function<5.83565048/2 in Explorer.Chain.Import.Runner.InternalTransactions.run/3>}, internal_transactions_indexed_at_transactions: {:run, #Function<4.83565048/2 in Explorer.Chain.Import.Runner.InternalTransactions.run/3>}, internal_transactions: {:run, #Function<3.83565048/2 in Explorer.Chain.Import.Runner.InternalTransactions.run/3>}]}
    (ecto) lib/ecto/multi.ex:513: Ecto.Multi.add_operation/3
    (explorer) lib/explorer/chain/import/stage/address_referencing.ex:43: anonymous fn/3 in Explorer.Chain.Import.Stage.AddressReferencing.multis/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain/import/stage/address_referencing.ex:34: Explorer.Chain.Import.Stage.AddressReferencing.multis/2
    (elixir) lib/enum.ex:1075: anonymous fn/3 in Enum.flat_map_reduce/3
    (elixir) lib/enum.ex:3317: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1074: Enum.flat_map_reduce/3
    (explorer) lib/explorer/chain/import.ex:267: Explorer.Chain.Import.runner_to_changes_list_to_multis/2
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [2890657, 2891098, 2890891, 2890942, 2891158, 2890666, 2890379, 1939318, 1939193, 2891181], callback_module: Indexer.InternalTransaction.Fetcher, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "https://dai-trace-ws.blockscout.com", method_to_url: [eth_getBalance: "https://dai-trace-ws.blockscout.com", trace_block: "https://dai-trace-ws.blockscout.com", trace_replayTransaction: "https://dai-trace-ws.blockscout.com"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], metadata: [fetcher: :internal_transaction]}]
```

**Comment by goodsoft** [comment]
Seems awfully like a merge artifact.

**Comment by goodsoft** [comment]
Yes, I see [my commit](https://github.com/poanetwork/blockscout/commit/8cbafd2cedb3296edc34ad928954f13e6c36bed6) not applied properly to [`internal_transactions.ex`](https://github.com/poanetwork/blockscout/blob/production-xdai/apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex)

**Comment by vbaranov** [comment]
Indeed, it was broken merging. Thanks for pointing me out. Deployed with the updated version.
