### ISSUE TITLE
Internal server error for Accounts page

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1839]
https://blockscout.com/aerum/mainnet/accounts

```
019-04-25T11:50:46.173 [error] #PID<0.20424.13> running BlockScoutWeb.Endpoint (connection #PID<0.20422.13>, stream id 1) terminated
Server: aerum-um9od2.blockscout.com:80 (http)
Request: GET /accounts
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Decimal.new/1
        (decimal) lib/decimal.ex:1057: Decimal.new(nil)
        (block_scout_web) lib/block_scout_web/views/address_view.ex:117: BlockScoutWeb.AddressView.balance_percentage/2
        (block_scout_web) lib/block_scout_web/templates/address/_tile.html.eex:41: BlockScoutWeb.AddressView."_tile.html"/1
        (block_scout_web) lib/block_scout_web/templates/address/index.html.eex:13: anonymous fn/3 in BlockScoutWeb.AddressView."index.html"/1
        (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
        (block_scout_web) lib/block_scout_web/templates/address/index.html.eex:12: BlockScoutWeb.AddressView."index.html"/1
        (block_scout_web) lib/block_scout_web/templates/layout/app.html.eex:43: BlockScoutWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
```

**Comment by saneery** [comment]
@vbaranov can we close this?

**Comment by vbaranov** [comment]
@saneery  I suppose we cannot until we install an update to all affected chains.
