### ISSUE TITLE
502 Bad Gateway after restarting vm

### ISSUE THREAD

**Issue by bellaj** [poanetwork/blockscout#1854]
I am installing Blockscout on Ubuntu 16.04 VM on azure using this [script ](https://github.com/bellaj/blockscout/blob/master/install_blockscout.sh), everything goes fine and the exporer works. However, once we restart the VM we keep getting **502 Bad Gateway**
 error. We've tried to restart nginx and blockscout service  but still we have the same error. 
` sudo systemctl status blockscout.service`
returns :
![errorr](https://user-images.githubusercontent.com/16008163/56864092-a5549f80-69be-11e9-9b47-96e6826f8c1b.PNG)

**Comment by bellaj** [comment]
`elixir --detached -e "File.write! 'pid', :os.getpid" -S mix phx.server
`then restarting the service fixed the issue.

**Comment by vbaranov** [comment]
@bellaj could you attach error log from `./apps/logs/prod/error.log` ?

**Comment by bellaj** [comment]
nginx's error log doesn't give much information. However, the syslog gives these messages !

```

May  1 11:58:22 VMclient1 mix[5915]: State: :ok
May  1 11:58:22 VMclient1 mix[5915]: 2019-05-01T11:58:22.879 application=db_connection [error] Postgrex.Protocol (#PID<0.443.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1030.0> exited
May  1 11:58:22 VMclient1 mix[5915]: 2019-05-01T11:58:22.880 application=db_connection [error] Postgrex.Protocol (#PID<0.439.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1029.0> exited
May  1 11:58:22 VMclient1 mix[5915]: 2019-05-01T11:58:22.899 [error] GenServer Indexer.Block.UncatalogedRewards.Processor terminating
May  1 11:58:22 VMclient1 mix[5915]: ** (FunctionClauseError) no function clause matching in Keyword.fetch!/2
May  1 11:58:22 VMclient1 mix[5915]:     (elixir) lib/keyword.ex:383: Keyword.fetch!(nil, :variant)
May  1 11:58:22 VMclient1 mix[5915]:     (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:208: EthereumJSONRPC.fetch_beneficiaries/2
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:43: Indexer.Block.UncatalogedRewards.Importer.fetch_beneficiaries/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:25: anonymous fn/2 in Indexer.Block.UncatalogedRewards.Importer.fetch_and_import_rewards/1
May  1 11:58:22 VMclient1 mix[5915]:     (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:23: Indexer.Block.UncatalogedRewards.Importer.fetch_and_import_rewards/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/processor.ex:34: Indexer.Block.UncatalogedRewards.Processor.import_or_try_later/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/processor.ex:28: Indexer.Block.UncatalogedRewards.Processor.handle_info/2
May  1 11:58:22 VMclient1 mix[5915]: Last message: :import_batch
May  1 11:58:22 VMclient1 mix[5915]: State: :ok
May  1 11:58:22 VMclient1 mix[5915]: 2019-05-01T11:58:22.917 [error] GenServer Indexer.Block.UncatalogedRewards.Processor terminating
May  1 11:58:22 VMclient1 mix[5915]: ** (FunctionClauseError) no function clause matching in Keyword.fetch!/2
May  1 11:58:22 VMclient1 mix[5915]:     (elixir) lib/keyword.ex:383: Keyword.fetch!(nil, :variant)
May  1 11:58:22 VMclient1 mix[5915]:     (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:208: EthereumJSONRPC.fetch_beneficiaries/2
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:43: Indexer.Block.UncatalogedRewards.Importer.fetch_beneficiaries/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:25: anonymous fn/2 in Indexer.Block.UncatalogedRewards.Importer.fetch_and_import_rewards/1
May  1 11:58:22 VMclient1 mix[5915]:     (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:23: Indexer.Block.UncatalogedRewards.Importer.fetch_and_import_rewards/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/processor.ex:34: Indexer.Block.UncatalogedRewards.Processor.import_or_try_later/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/processor.ex:28: Indexer.Block.UncatalogedRewards.Processor.handle_info/2
May  1 11:58:22 VMclient1 mix[5915]: Last message: :import_batch
May  1 11:58:22 VMclient1 mix[5915]: State: :ok
May  1 11:58:22 VMclient1 mix[5915]: 2019-05-01T11:58:22.940 [error] GenServer Indexer.Block.UncatalogedRewards.Processor terminating
May  1 11:58:22 VMclient1 mix[5915]: ** (FunctionClauseError) no function clause matching in Keyword.fetch!/2
May  1 11:58:22 VMclient1 mix[5915]:     (elixir) lib/keyword.ex:383: Keyword.fetch!(nil, :variant)
May  1 11:58:22 VMclient1 mix[5915]:     (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:208: EthereumJSONRPC.fetch_beneficiaries/2
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:43: Indexer.Block.UncatalogedRewards.Importer.fetch_beneficiaries/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:25: anonymous fn/2 in Indexer.Block.UncatalogedRewards.Importer.fetch_and_import_rewards/1
May  1 11:58:22 VMclient1 mix[5915]:     (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:23: Indexer.Block.UncatalogedRewards.Importer.fetch_and_import_rewards/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/processor.ex:34: Indexer.Block.UncatalogedRewards.Processor.import_or_try_later/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/processor.ex:28: Indexer.Block.UncatalogedRewards.Processor.handle_info/2
May  1 11:58:22 VMclient1 mix[5915]: Last message: :import_batch
May  1 11:58:22 VMclient1 mix[5915]: State: :ok
May  1 11:58:22 VMclient1 mix[5915]: 2019-05-01T11:58:22.968 [error] GenServer Indexer.Block.UncatalogedRewards.Processor terminating
May  1 11:58:22 VMclient1 mix[5915]: ** (FunctionClauseError) no function clause matching in Keyword.fetch!/2
May  1 11:58:22 VMclient1 mix[5915]:     (elixir) lib/keyword.ex:383: Keyword.fetch!(nil, :variant)
May  1 11:58:22 VMclient1 mix[5915]:     (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:208: EthereumJSONRPC.fetch_beneficiaries/2
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:43: Indexer.Block.UncatalogedRewards.Importer.fetch_beneficiaries/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:25: anonymous fn/2 in Indexer.Block.UncatalogedRewards.Importer.fetch_and_import_rewards/1
May  1 11:58:22 VMclient1 mix[5915]:     (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/importer.ex:23: Indexer.Block.UncatalogedRewards.Importer.fetch_and_import_rewards/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/processor.ex:34: Indexer.Block.UncatalogedRewards.Processor.import_or_try_later/1
May  1 11:58:22 VMclient1 mix[5915]:     (indexer) lib/indexer/block/uncataloged_rewards/processor.ex:28: Indexer.Block.UncatalogedRewards.Processor.handle_info/2
May  1 11:58:22 VMclient1 mix[5915]: Last message: :import_batch
May  1 11:58:22 VMclient1 mix[5915]: State: :ok
May  1 11:58:22 VMclient1 mix[5915]: 2019-05-01T11:58:22.969 application=db_connection [error] Postgrex.Protocol (#PID<0.438.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1050.0> exited
May  1 11:58:22 VMclient1 mix[5915]: 2019-05-01T11:58:22.971 application=db_connection [error] Postgrex.Protocol (#PID<0.436.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1049.0> exited
May  1 11:58:22 VMclient1 mix[5915]: 2019-05-01T11:58:22.973 [info] Application indexer exited: shutdown
May  1 11:58:27 VMclient1 mix[5915]: =SUPERVISOR REPORT==== 1-May-2019::11:58:27.009033 ===
May  1 11:58:27 VMclient1 mix[5915]:     supervisor: {local,ssl_sup}
May  1 11:58:27 VMclient1 mix[5915]:     errorContext: shutdown_error
May  1 11:58:27 VMclient1 mix[5915]:     reason: killed
May  1 11:58:27 VMclient1 mix[5915]:     offender: [{pid,<0.114.0>},
May  1 11:58:27 VMclient1 mix[5915]:                {id,ssl_connection_sup},
May  1 11:58:27 VMclient1 mix[5915]:                {mfargs,{ssl_connection_sup,start_link,[]}},
May  1 11:58:27 VMclient1 mix[5915]:                {restart_type,permanent},
May  1 11:58:27 VMclient1 mix[5915]:                {shutdown,4000},
May  1 11:58:27 VMclient1 mix[5915]:                {child_type,supervisor}]
May  1 11:58:27 VMclient1 mix[5915]: =SUPERVISOR REPORT==== 1-May-2019::11:58:27.009521 ===
May  1 11:58:27 VMclient1 mix[5915]:     supervisor: {local,tls_connection_sup}
May  1 11:58:27 VMclient1 mix[5915]:     errorContext: shutdown_error
May  1 11:58:27 VMclient1 mix[5915]:     reason: killed
May  1 11:58:27 VMclient1 mix[5915]:     offender: [{nb_children,3},
May  1 11:58:27 VMclient1 mix[5915]:                {id,undefined},
May  1 11:58:27 VMclient1 mix[5915]:                {mfargs,{tls_connection,start_link,[]}},
May  1 11:58:27 VMclient1 mix[5915]:                {restart_type,temporary},
May  1 11:58:27 VMclient1 mix[5915]:                {shutdown,4000},
May  1 11:58:27 VMclient1 mix[5915]:                {child_type,worker}]
May  1 11:58:28 VMclient1 mix[5915]: {"Kernel pid terminated",application_controller,"{application_terminated,indexer,shutdown}"}
May  1 11:58:28 VMclient1 mix[5915]: Kernel pid terminated (application_controller) ({application_terminated,indexer,shutdown})
May  1 11:58:28 VMclient1 mix[5915]: #015
May  1 11:58:28 VMclient1 mix[5915]: Crash dump is being written to: erl_crash.dump...
May  1 11:58:28 VMclient1 systemd[1]: blockscout.service: Main process exited, code=exited, status=1/FAILURE
May  1 11:58:28 VMclient1 systemd[1]: blockscout.service: Unit entered failed state.
May  1 11:58:28 VMclient1 systemd[1]: blockscout.service: Failed with result 'exit-code'.
May  1 11:58:28 VMclient1 systemd[1]: blockscout.service: Service hold-off time over, scheduling restart.
May  1 11:58:28 VMclient1 systemd[1]: Stopped Blockscout Web App.
May  1 11:58:28 VMclient1 systemd[1]: Started Blockscout Web App.
```

**Comment by bellaj** [comment]
After long investigations i figured out that elixir version was the problem.
