### ISSUE TITLE
RSK eth_getUncleByBlockHashAndIndex error

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1912]
There are a lot of errors that flood the archive node:
```
2019-05-08-09:46:26.690 ERROR [panic]  Stack Trace:
java.lang.Throwable: null
	at co.rsk.panic.PanicProcessor.panic(PanicProcessor.java:33)
	at org.ethereum.core.Block.checkExpectedRoot(Block.java:525)
	at org.ethereum.core.Block.<init>(Block.java:158)
	at org.ethereum.core.Block.<init>(Block.java:133)
	at org.ethereum.core.Block.<init>(Block.java:100)
	at org.ethereum.rpc.Web3Impl.eth_getUncleByBlockHashAndIndex(Web3Impl.java:812)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:516)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:357)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:288)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleArray(JsonRpcBasicServer.java:307)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:287)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:256)
	at co.rsk.rpc.netty.JsonRpcWeb3ServerHandler.channelRead0(JsonRpcWeb3ServerHandler.java:63)
	at co.rsk.rpc.netty.JsonRpcWeb3ServerHandler.channelRead0(JsonRpcWeb3ServerHandler.java:41)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at co.rsk.rpc.netty.Web3HttpMethodFilterHandler.channelRead0(Web3HttpMethodFilterHandler.java:31)
	at co.rsk.rpc.netty.Web3HttpMethodFilterHandler.channelRead0(Web3HttpMethodFilterHandler.java:25)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at co.rsk.rpc.netty.JsonRpcWeb3FilterHandler.channelRead0(JsonRpcWeb3FilterHandler.java:96)
	at co.rsk.rpc.netty.JsonRpcWeb3FilterHandler.channelRead0(JsonRpcWeb3FilterHandler.java:21)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:66)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1304)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:921)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:135)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2019-05-08-09:46:26.691 DEBUG [c.g.j.JsonRpcBasicServer]  Invoked method: eth_getUncleByBlockHashAndIndex, result BlockResult{number='0x794fe', hash='0xc1c1003e5b85c693fb4b8b1c0d335c6bf9a14c73b5f6980304de48b6939d8e57', parentHash='0x1a2b32518d2a9fba1095f6a7240bf02668783c6a5c650cf0657e9cbfa1c59443', sha3Uncles='0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347', logsBloom='0x00000000000000000000000000000808000000080000000000022000000000000010000000000000000000000000000000020004000000000000000000008081000000000000001000002000000802002000000000000000000000000000000000000000010000000000000000800000200020000000000000000000000000020000000000000001008a004000402000000000000000200008000020004000000000000100001000200a0000200000000000001000000000001000000000000000000001000000000000000000001000000020000000000600200000100000002004000000000000008004040008000000020000000000000000008400000000', transactionsRoot='0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421', stateRoot='0xccdcfa5bdaf0ab7ddd06278303ce68251ac728fa83372f79813c505814e16ef7', receiptsRoot='0xb441891d708e6262fa96f299c22ef854a8e578257b887abbaf82b7d2f0b38da9', miner='0x32dfc7a84f24b10a5dded1d8b24f48b96ab77373', difficulty='0x02f75b1d7e800998d9', totalDifficulty='0x0', extraData='0x00', size='0x42e', gasLimit='0x67c280', minimumGasPrice='183000000', gasUsed='0x176e0', timestamp='0x5b252fb6', transactions=[], uncles=[]}
```

**Comment by vbaranov** [comment]
The error is disappeared with the install of 2.0.0.
