### ISSUE TITLE
Cannot run Indexer on not-secure websocket rpc endpoint

### ISSUE THREAD

**Issue by JuliusBrain** [poanetwork/blockscout#1924]
Hello,

I'm trying to run Blockcscout on my custom rpc endpoint (based on geth) but indexer fails to connect to a unsecure websocket. I'm following `README.md` getting started steps and I can't make it run.

In configs below, I didn't post actual url where my rpc is deployed due to a security concerns, but the real version is very similar.

### Environment

* Elixir & Erlang/OTP versions (1.8.1`):
* Operating System: MacOs Mojave

### Steps to reproduce

1. Config in `apps/explorer/config/dev/geth.exs`:
```use Mix.Config

config :explorer,
  json_rpc_named_arguments: [
    transport: EthereumJSONRPC.HTTP,
    transport_options: [
      http: EthereumJSONRPC.HTTP.HTTPoison,
      url: System.get_env("ETHEREUM_JSONRPC_HTTP_URL") || "https://user:password@rpc.my.network",
      http_options: [recv_timeout: :timer.minutes(1), timeout: :timer.minutes(1), hackney: [pool: :ethereum_jsonrpc]]
    ],
    variant: EthereumJSONRPC.Geth
  ],
  subscribe_named_arguments: [
    transport: EthereumJSONRPC.WebSocket,
    transport_options: [
      web_socket: EthereumJSONRPC.WebSocket.WebSocketClient,
      url: System.get_env("ETHEREUM_JSONRPC_WS_URL") || "ws://user:password@rpc.my.network/ws"
    ],
    variant: EthereumJSONRPC.Geth
  ]
``` 
2. Config in `apps/indexer/config/dev/geth.exs`
```use Mix.Config

config :indexer,
  block_interval: :timer.seconds(5),
  json_rpc_named_arguments: [
    transport: EthereumJSONRPC.HTTP,
    transport_options: [
      http: EthereumJSONRPC.HTTP.HTTPoison,
      url: System.get_env("ETHEREUM_JSONRPC_HTTP_URL") || "https://user:password@rpc.my.network",
      http_options: [recv_timeout: :timer.minutes(1), timeout: :timer.minutes(1), hackney: [pool: :ethereum_jsonrpc]]
    ],
    variant: EthereumJSONRPC.Geth
  ],
  subscribe_named_arguments: [
    transport: EthereumJSONRPC.WebSocket,
    transport_options: [
      web_socket: EthereumJSONRPC.WebSocket.WebSocketClient,
      url: System.get_env("ETHEREUM_JSONRPC_WS_URL") || "ws://user:password@rpc.my.network"
    ]
  ]
```

3. In `apps/explorer/config/dev.exs` and `apps/indexer/config/dev.exs` I have removed `ganache` to  a `geth`.

4. Running all commands from number 4-10 from a `Readme.md`

### Expected behaviour

*Tell us what should happen.*
It should index all bloks and transactions

### Actual behaviour

I'm getting this error:
```
2019-05-10T12:11:05.961 fetcher=block_realtime [error] GenServer Indexer.Block.Realtime.Fetcher terminating
** (stop) exited in: GenServer.call(Indexer.Block.Realtime.WebSocket, {:subscribe, "newHeads", []}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (indexer) lib/indexer/block/realtime/fetcher.ex:138: Indexer.Block.Realtime.Fetcher.subscribe_to_new_heads/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:71: Indexer.Block.Realtime.Fetcher.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, {:init, [transport: EthereumJSONRPC.WebSocket, transport_options: %EthereumJSONRPC.WebSocket{url: "ws://user:passwordt@rpc.my.network", web_socket: EthereumJSONRPC.WebSocket.WebSocketClient, web_socket_options: %EthereumJSONRPC.WebSocket.WebSocketClient.Options{event: nil, params: nil, web_socket: Indexer.Block.Realtime.WebSocket}}]}}
State: %Indexer.Block.Realtime.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "https://user:passwordt@rpc.my.network", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, max_number_seen: nil, previous_number: nil, subscription: nil, timer: nil}
2019-05-10T12:11:10.965 fetcher=block_realtime [error] GenServer Indexer.Block.Realtime.Fetcher terminating
```
---
In the meantime, I referred to this issue #1110  and this one #624 . I didn't remove code responsible for secure web sockets as it was stated in some comment, functionality for unsecured WebSocket connections should be already added on one PR.

**Comment by vbaranov** [comment]
Hello @JuliusBrain 

Which version of Blockscout are you using? Comparing with the latest version of those files it looks like you are using some old version. I recommend you to use the latest released version: https://github.com/poanetwork/blockscout/releases.

In the latest versions, we have a native support of geth-based chains. You don't need to change something in configs. You can manage connection with env vars https://forum.poa.network/t/faq-environment-variables/1814:

```
export ETHEREUM_JSONRPC_HTTP_URL=...
export ETHEREUM_JSONRPC_TRACE_URL=...
export ETHEREUM_JSONRPC_WS_URL=...
export ETHEREUM_JSONRPC_VARIANT=geth
```

**Comment by JuliusBrain** [comment]
Hi @vbaranov,

I was using latest version from master.

I downloaded latest relaese and did what you told me. Even when I exported `ETHEREUM_JSONRPC_HTTP_URL` and `ETHEREUM_JSONRPC_WS_URL` I had this error.

```2019-05-13T21:34:37.300 application=indexer fetcher=block_catchup first_block_number=1863267 last_block_number=1863258 [error] ** (KeyError) key 74 not found in: %{0 => %{number: 1863267}, 1 => %{number: 1863266}, 2 => %{number: 1863265}, 3 => %{number: 1863264}, 4 => %{number: 1863263}, 5 => %{number: 1863262}, 6 => %{number: 1863261}, 7 => %{number: 1863260}, 8 => %{number: 1863259}, 9 => %{number: 1863258}}
    (stdlib) :maps.get(74, %{0 => %{number: 1863267}, 1 => %{number: 1863266}, 2 => %{number: 1863265}, 3 => %{number: 1863264}, 4 => %{number: 1863263}, 5 => %{number: 1863262}, 6 => %{number: 1863261}, 7 => %{number: 1863260}, 8 => %{number: 1863259}, 9 => %{number: 1863258}})
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/block.ex:84: EthereumJSONRPC.Block.from_response/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/blocks.ex:35: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:439: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer) lib/indexer/block/fetcher.ex:126: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:187: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3```

Apart from exporting variables, like you told me, what else should I do? Where can I find up-to-date docs for running blockscout for the private ethereum geth node?

Thank you for your help!

**Comment by vbaranov** [comment]
@JuliusBrain 

Here is the local deployment guide https://forum.poa.network/t/manual-blockscout-deployment/2458
The required environment variables are listed here: https://forum.poa.network/t/faq-environment-variables/1814

**Comment by JuliusBrain** [comment]
@vbaranov I've followed your advice and exported env variables:
```
echo $ETHEREUM_JSONRPC_VARIANT
geth
echo $ETHEREUM_JSONRPC_HTTP_URL
http://user:password@rpc.my.network
``` 
Didn't set more variables.

I followed the instructions from the https://forum.poa.network/t/manual-blockscout-deployment/2458. and I worked on a cloned repo and switched to a `origin/v1.3.12-beta` branch.

This is the output from the `mix phx.server` after doing all the steps detailed in the instruction.

```mix phx.server
2019-05-14T14:43:18.842 application=tzdata [info] tzdata release in place is from a file last modified Thu, 03 May 2018 23:55:14 GMT. Release file onserver was last modified Tue, 26 Mar 2019 05:40:14 GMT.
2019-05-14T14:43:20.337 [error] GenServer Tzdata.EtsHolder terminating
** (MatchError) no match of right hand side value: {:error, :cannot_create_table}
    (tzdata) lib/tzdata/ets_holder.ex:59: Tzdata.EtsHolder.load_ets_table/1
    (tzdata) lib/tzdata/ets_holder.ex:52: Tzdata.EtsHolder.load_release/0
    (tzdata) lib/tzdata/ets_holder.ex:23: Tzdata.EtsHolder.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :new_release_has_been_downloaded}
State: "2018e"
warning: deprecated time unit: :microseconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
  (explorer) lib/explorer/repo/prometheus_logger.ex:8: Explorer.Repo.PrometheusLogger.log/1
  (telemetry) /Users/juliusbrain/Work/LivePlanet/blockExplorer/blockscout/deps/telemetry/src/telemetry.erl:113: anonymous fn/4 in :telemetry.execute/3
  (stdlib) lists.erl:1338: :lists.foreach/2
  (ecto_sql) lib/ecto/adapters/sql.ex:786: Ecto.Adapters.SQL.log/4
  (db_connection) lib/db_connection.ex:1311: DBConnection.log/5
  (ecto_sql) lib/ecto/adapters/sql.ex:561: Ecto.Adapters.SQL.execute!/4
  (ecto_sql) lib/ecto/adapters/sql.ex:553: Ecto.Adapters.SQL.execute/5
  (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
  (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
  (explorer) lib/explorer/counters/average_block_time.ex:75: Explorer.Counters.AverageBlockTime.refresh_timestamps/0
  (explorer) lib/explorer/counters/average_block_time.ex:46: Explorer.Counters.AverageBlockTime.init/1
  (stdlib) gen_server.erl:374: :gen_server.init_it/2
  (stdlib) gen_server.erl:342: :gen_server.init_it/6
  (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

2019-05-14T14:43:22.290 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.6.1 at https://localhost:4001
2019-05-14T14:43:22.292 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.6.1 at https://localhost:4001
2019-05-14T14:43:22.929 application=indexer fetcher=block_catchup first_block_number=1878934 last_block_number=1878925 [error] ** (KeyError) key 74 not found in: %{0 => %{number: 1878934}, 1 => %{number: 1878933}, 2 => %{number: 1878932}, 3 => %{number: 1878931}, 4 => %{number: 1878930}, 5 => %{number: 1878929}, 6 => %{number: 1878928}, 7 => %{number: 1878927}, 8 => %{number: 1878926}, 9 => %{number: 1878925}}
    (stdlib) :maps.get(74, %{0 => %{number: 1878934}, 1 => %{number: 1878933}, 2 => %{number: 1878932}, 3 => %{number: 1878931}, 4 => %{number: 1878930}, 5 => %{number: 1878929}, 6 => %{number: 1878928}, 7 => %{number: 1878927}, 8 => %{number: 1878926}, 9 => %{number: 1878925}})
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/block.ex:84: EthereumJSONRPC.Block.from_response/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/blocks.ex:35: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:439: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer) lib/indexer/block/fetcher.ex:126: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:187: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3


Retrying.
2019-05-14T14:43:23.240 application=indexer fetcher=block_catchup first_block_number=1878914 last_block_number=1878905 [error] ** (KeyError) key 74 not found in: %{0 => %{number: 1878914}, 1 => %{number: 1878913}, 2 => %{number: 1878912}, 3 => %{number: 1878911}, 4 => %{number: 1878910}, 5 => %{number: 1878909}, 6 => %{number: 1878908}, 7 => %{number: 1878907}, 8 => %{number: 1878906}, 9 => %{number: 1878905}}
    (stdlib) :maps.get(74, %{0 => %{number: 1878914}, 1 => %{number: 1878913}, 2 => %{number: 1878912}, 3 => %{number: 1878911}, 4 => %{number: 1878910}, 5 => %{number: 1878909}, 6 => %{number: 1878908}, 7 => %{number: 1878907}, 8 => %{number: 1878906}, 9 => %{number: 1878905}})
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/block.ex:84: EthereumJSONRPC.Block.from_response/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/blocks.ex:35: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:439: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer) lib/indexer/block/fetcher.ex:126: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:187: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Using `wscat -c ws://rpc.my.network/ws --auth=user:password` and curl on RPC http endpoint works correctly.

**Comment by vbaranov** [comment]
You should export `ETHEREUM_JSONRPC_TRACE_URL` and `ETHEREUM_JSONRPC_WS_URL` too

**Comment by JuliusBrain** [comment]
@vbaranov 
```
brew install erlang
Error: erlang 21.3.7 is already installed
To upgrade to 21.3.7.1, run `brew upgrade erlang`.
elixir --version
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.8.1 (compiled with Erlang/OTP 21)
pg_ctl --version
pg_ctl (PostgreSQL) 11.2
gmp 6.1.2_2
gcc 8.3.0_2
node v10.5.0
libtool 2.4.6_1```

**Comment by JuliusBrain** [comment]
I did export `ETHEREUM_JSONRPC_WS_URL` it's in this format : `ws://user:password@rpc.my.network/ws`

I didn't export `ETHEREUM_JSONRPC_TRACE_URL` because I'm using GETH client

**Comment by JuliusBrain** [comment]
I will try running it again. I noticed I had node version set to `8.14` instead of `10.5.0`. Maybe that will help.

Also in files `blockscout/apps/indexer/config/dev.exs` line 26 and in `blockscout/apps/explorer/config/dev.exs` line 25 I changed `ganache` to `geth` as per instruction.

**Comment by vbaranov** [comment]
>I didn't export ETHEREUM_JSONRPC_TRACE_URL because I'm using GETH client

You should set it for Geth too. As Geth client has those tracing methods, that we are using to get internal transactions. I've updated description for this var in the env vars list to eliminate confusionю

>I will try running it again. I noticed I had node version set to 8.14 instead of 10.5.0. Maybe that will help.

Yes, Node 10+ is the requirement

>Also in files blockscout/apps/indexer/config/dev.exs line 26 and in blockscout/apps/explorer/config/dev.exs line 25 I changed ganache to geth as per instruction.

What instruction do you mean?

**Comment by JuliusBrain** [comment]
I meant per point number 10 from https://forum.poa.network/t/manual-blockscout-deployment/2458.

**Comment by JuliusBrain** [comment]
Ok, I see that points 10/11 are not needed.

**Comment by vbaranov** [comment]
>Ok, I see that points 10/11 are not needed.

Yes, if you have set `ETHEREUM_JSONRPC_VARIANT` those steps are unnecessary. We will update it in the instruction.

**Comment by JuliusBrain** [comment]
@vbaranov 

Now I'm getting this error while running webpack in production in node version 10.5.0
```
juliusbrain@Adrians-MacBook:~/Work/LivePlanet/blockExplorer/blockscout/apps/block_scout_web/assets$ node_modules/webpack/bin/webpack.js --mode production
Hash: 49080d527d2c5d15d7e812660e31a4e3b29f4ec2
Version: webpack 4.31.0
Child
    Hash: 49080d527d2c5d15d7e8
    Time: 17052ms
    Built at: 05/14/2019 3:45:07 PM
                                    Asset     Size  Chunks                    Chunk Names
    address_contract/code_highlighting.js  786 KiB       0  [emitted]  [big]  main
    Entrypoint main [big] = address_contract/code_highlighting.js
      [0] ./js/view_specific/address_contract/code_highlighting.js 664 bytes {0} [built]
    [190] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 189 hidden modules

    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets:
      address_contract/code_highlighting.js (786 KiB)

    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      main (786 KiB)
          address_contract/code_highlighting.js


    WARNING in webpack performance recommendations:
    You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
    For more info visit https://webpack.js.org/guides/code-splitting/
Child
    Hash: 12660e31a4e3b29f4ec2
    Time: 24955ms
    Built at: 05/14/2019 3:45:15 PM
     1 asset
    Entrypoint main = app.js
     [35] ./js/lib/async_listing_load.js 8.06 KiB {0} [built]
     [56] ./js/lib/currency.js 3.3 KiB {0} [built]
    [135] ./js/locale.js 508 bytes {0} [built]
    [267] ./js/lib/token_balance_dropdown.js 1.05 KiB {0} [built]
    [269] ./js/lib/from_now.js 1.77 KiB {0} [built]
    [271] ./js/lib/market_history_chart.js 6.7 KiB {0} [built]
    [273] ./js/app.js 1.24 KiB {0} [built]
    [460] /Users/juliusbrain/Work/LivePlanet/blockExplorer/blockscout/deps/phoenix_html/priv/static/phoenix_html.js 2.14 KiB {0} [built]
    [465] ./js/pages/address.js 6.04 KiB {0} [built]
    [469] ./js/pages/address/coin_balances.js 2.9 KiB {0} [built]
    [476] ./js/pages/address/transactions.js 3.63 KiB {0} [built]
    [477] ./js/pages/address/validations.js 2.7 KiB {0} [built]
    [478] ./js/pages/address/internal_transactions.js 4.18 KiB {0} [built]
    [479] ./js/pages/blocks.js 4.8 KiB {0} [built]
    [480] ./js/pages/chain.js 13.4 KiB {0} [built]
        + 489 hidden modules

    ERROR in ./css/app.scss
    Module build failed (from ./node_modules/css-loader/index.js):
    ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

      font-weight: $font-weight-bolder; // Add the correct font weight in Chrome, Edge, and Safari
                  ^
          Undefined variable: "$font-weight-bolder".```

Previously I was getting this error but I followed instructions from this ticket. https://github.com/poanetwork/blockscout/issues/675

**Comment by vbaranov** [comment]
Remove all created folders and files from your previous launch (with node 8.x) with
`./rel/commands/clear_build.sh -f` and start the building procedure again. If you follow all prerequisites, there shouldn't be the error.

**Comment by JuliusBrain** [comment]
I downloaded source code file from the release tab just to have a clean version and I did everything instructions says. I'm on node 10.5.0, I doubled checked that. All ENV vars you mentioned are set. After running `mix phx.server` I get the following error I got before.

```2019-05-14T18:40:21.650 application=indexer fetcher=block_catchup first_block_number=1875255 last_block_number=1875246 [error] ** (KeyError) key 74 not found in: %{0 => %{number: 1875255}, 1 => %{number: 1875254}, 2 => %{number: 1875253}, 3 => %{number: 1875252}, 4 => %{number: 1875251}, 5 => %{number: 1875250}, 6 => %{number: 1875249}, 7 => %{number: 1875248}, 8 => %{number: 1875247}, 9 => %{number: 1875246}}
    (stdlib) :maps.get(74, %{0 => %{number: 1875255}, 1 => %{number: 1875254}, 2 => %{number: 1875253}, 3 => %{number: 1875252}, 4 => %{number: 1875251}, 5 => %{number: 1875250}, 6 => %{number: 1875249}, 7 => %{number: 1875248}, 8 => %{number: 1875247}, 9 => %{number: 1875246}})
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/block.ex:84: EthereumJSONRPC.Block.from_response/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/blocks.ex:35: EthereumJSONRPC.Blocks.from_responses/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:439: EthereumJSONRPC.fetch_blocks_by_params/3
    (indexer) lib/indexer/block/fetcher.ex:126: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:187: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3


Retrying.```

**Comment by JuliusBrain** [comment]
Values for the env vars. Maybe I've set something wrong or in a different format?
```
ETHEREUM_JSONRPC_VARIANT=geth
ETHEREUM_JSONRPC_HTTP_URL=http://user:password@rpc.my.network
ETHEREUM_JSONRPC_TRACE_URL=http://user:password@rpc.my.network
ETHEREUM_JSONRPC_WS_URL=ws://user:password@rpc.my.network/ws
```

**Comment by JuliusBrain** [comment]
also I'm getting this error during second npm install at `apps/explorer`
```
cd apps/explorer && npm install; cd -

> keccak@1.4.0 install /Users/juliusbrain/Work/blockExplorer/blkscout/blockscout-1.3.12-beta/apps/explorer/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild /Users/juliusbrain/Work/blockExplorer/blkscout/blockscout-1.3.12-beta/apps/explorer/node_modules/keccak
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/keccak/src/addon.o
In file included from ../src/addon.cc:2:
../../nan/nan.h:1081:96: error: too many arguments to function call, expected at most 4, have 5
        length_ = string->WriteUtf8(v8::Isolate::GetCurrent(), str_, static_cast<int>(len), 0, flags);
                  ~~~~~~~~~~~~~~~~~                                                            ^~~~~
/Users/juliusbrain/.node-gyp/10.5.0/include/node/v8.h:2622:3: note: 'WriteUtf8' declared here
  int WriteUtf8(char* buffer,
  ^
1 error generated.
make: *** [Release/obj.target/keccak/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/juliusbrain/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/juliusbrain/.nvm/versions/node/v10.5.0/bin/node" "/Users/juliusbrain/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/juliusbrain/Work/blockExplorer/blkscout/blockscout-1.3.12-beta/apps/explorer/node_modules/keccak
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juliusbrain/.npm/_logs/2019-05-14T17_16_29_953Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.
added 76 packages from 30 contributors and audited 91 packages in 5.108s
found 0 vulnerabilities
```

but this command fixes this `sudo xcode-select --switch /Library/Developer/CommandLineTools`

**Comment by vbaranov** [comment]
We cannot reproduce your issue. Please provide spec of your chain and paramaters to launch the node.

**Comment by vbaranov** [comment]
@JuliusBrain the latest versions of BlockScout https://github.com/poanetwork/blockscout/releases (current release is https://github.com/poanetwork/blockscout/releases/tag/v3.1.2-beta) support Node 12 - it should fix the issues with front-end building.

Regarding WebSocket issue, you can safely unset `ETHEREUM_JSONRPC_WS_URL` environment variable. In this case, Blockscout should retrieve the current block by polling the node with `eth_blockNumber` request.
