### ISSUE TITLE
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.WebSocket.WebSocketClient.start_link/1

### ISSUE THREAD

**Issue by Genysys** [poanetwork/blockscout#1945]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System: RHEL /CentOS 7.5

### Steps to reproduce

```
COIN=DAI \
ETHEREUM_JSONRPC_VARIANT=parity  \
ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545 \
ETHEREUM_JSONRPC_WS_URL=http://localhost:8546 \
ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545 \
make start
```

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

Blockscout starts

### Actual behaviour

*Tell us what happens instead.*

The indexers does not start

```2019-05-14T06:50:00.544 application=tzdata [info] tzdata release in place is from a file last modified Thu, 03 May 2018 23:55:14 GMT. Release file on server was last modified Tue, 26 Mar 2019 05:40:14 GMT.
2019-05-14T06:50:02.099 [error] GenServer Tzdata.EtsHolder terminating
** (MatchError) no match of right hand side value: {:error, :cannot_create_table}
    (tzdata) lib/tzdata/ets_holder.ex:59: Tzdata.EtsHolder.load_ets_table/1
    (tzdata) lib/tzdata/ets_holder.ex:52: Tzdata.EtsHolder.load_release/0
    (tzdata) lib/tzdata/ets_holder.ex:23: Tzdata.EtsHolder.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :new_release_has_been_downloaded}
State: "2018e"
warning: deprecated time unit: :microseconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
  (explorer) lib/explorer/repo/prometheus_logger.ex:8: Explorer.Repo.PrometheusLogger.log/1
  (telemetry) /opt/app/deps/telemetry/src/telemetry.erl:113: anonymous fn/4 in :telemetry.execute/3
  (stdlib) lists.erl:1338: :lists.foreach/2
  (ecto_sql) lib/ecto/adapters/sql.ex:786: Ecto.Adapters.SQL.log/4

2019-05-14T06:50:03.901 [info] Application indexer exited: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.Supervisor
    ** (EXIT) shutdown: failed to start child: Indexer.Block.Realtime.Supervisor
        ** (EXIT) shutdown: failed to start child: EthereumJSONRPC.WebSocket.WebSocketClient
            ** (EXIT) an exception was raised:
                ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.WebSocket.WebSocketClient.start_link/1
                    (ethereum_jsonrpc) lib/ethereum_jsonrpc/web_socket/web_socket_client.ex:53: EthereumJSONRPC.WebSocket.WebSocketClient.start_link(["http://localhost:8546", [keepalive: 150000], [name: Indexer.Block.Realtime.WebSocket]])
                    (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
                    (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
                    (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
                    (stdlib) supervisor.erl:1157: :supervisor.children_map/4
                    (stdlib) supervisor.erl:315: :supervisor.init_children/2
                    (stdlib) gen_server.erl:374: :gen_server.init_it/2
                    (stdlib) gen_server.erl:342: :gen_server.init_it/6
** (Mix) Could not start application indexer: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.Supervisor
    ** (EXIT) shutdown: failed to start child: Indexer.Block.Realtime.Supervisor
        ** (EXIT) shutdown: failed to start child: EthereumJSONRPC.WebSocket.WebSocketClient
            ** (EXIT) an exception was raised:
                ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.WebSocket.WebSocketClient.start_link/1
                    (ethereum_jsonrpc) lib/ethereum_jsonrpc/web_socket/web_socket_client.ex:53: EthereumJSONRPC.WebSocket.WebSocketClient.start_link(["http://localhost:8546", [keepalive: 150000], [name: Indexer.Block.Realtime.WebSocket]])
                    (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
                    (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
                    (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
                    (stdlib) supervisor.erl:1157: :supervisor.children_map/4
                    (stdlib) supervisor.erl:315: :supervisor.init_children/2
                    (stdlib) gen_server.erl:374: :gen_server.init_it/2
                    (stdlib) gen_server.erl:342: :gen_server.init_it/6
make: *** [start] Error 1
```

**Comment by vbaranov** [comment]
It looks like an incorrect link is indicated for web sockets. Instead of `http://localhost:8546` it should be `ws://localhost:8546` for `ETHEREUM_JSONRPC_WS_URL` environment variable.
