### ISSUE TITLE
Error when I try to verify with the `latest` version of compiler

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1962]
Choosing of `latest` version of compiler every time causes the timeout error, that appear almost immediately after pressing "Verify" button:

```
exited in: GenServer.call(Explorer.SmartContract.SolcDownloader, {:ensure_exists, "latest"}, 60000) ** (EXIT) an exception was raised: ** (HTTPoison.Error) :timeout (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5 (explorer) lib/explorer/smart_contract/solc_downloader.ex:89: Explorer.SmartContract.SolcDownloader.download/1 (explorer) lib/explorer/smart_contract/solc_downloader.ex:48: Explorer.SmartContract.SolcDownloader.handle_call/3 (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4 (stdlib) gen_server.erl:690: :gen_server.handle_msg/6 (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by zachdaniel** [comment]
I'm not able to reproduce this issue locally, or on the POA Sokol testnet. Is this issue happening on ethereum stg/mainnet? I'd like to take a look at some logs for it, if possible. We should also confirm that the issue is still happening.

**Comment by vbaranov** [comment]
I am unable to reproduce it again. Tested on stg server. Going to close it.

**Comment by zachdaniel** [comment]
I actually saw this issue locally as well. It appears to be very rare, but it can happen. I fixes it so that my tests would pass correctly in https://github.com/poanetwork/blockscout/pull/1966
