### ISSUE TITLE
Error when starting the Dockerfile

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [poanetwork/blockscout#1979]
*Describe your issue here.*
I am trying to run the provided Dockerfile into a `docker-compose` config, however I encountered this issue:

```
 Server: localhost:4001 (http)
explorer_1     | Request: GET /recent_transactions
explorer_1     | ** (exit) an exception was raised:
explorer_1     |     ** (UndefinedFunctionError) function :keccakf1600.hash/2 is undefined (module :keccakf1600 is not available)
explorer_1     |         (keccakf1600) :keccakf1600.hash(:sha3_256, "10503ba12956babfe8cfa57c21dee0deedcac375")
explorer_1     |         (explorer) lib/explorer/chain/address.ex:161: Explorer.Chain.Address.stream_every_four_bytes_of_sha256/1
explorer_1     |         (explorer) lib/explorer/chain/address.ex:135: Explorer.Chain.Address.checksum/2
explorer_1     |         (block_scout_web) lib/block_scout_web/templates/address/_responsive_hash.html.eex:1: BlockScoutWeb.AddressView."_responsive_hash.html"/1
explorer_1     |         (block_scout_web) lib/block_scout_web/templates/address/_link.html.eex:3: BlockScoutWeb.AddressView."_link.html"/1
explorer_1     |         (block_scout_web) lib/block_scout_web/templates/transaction/_tile.html.eex:23: BlockScoutWeb.TransactionView."_tile.html"/1
explorer_1     |         (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
explorer_1     |         (phoenix) lib/phoenix/view.ex:406: Phoenix.View.render_to_string/3
explorer_1     | 2019-05-19T12:29:33.668 [warn] The on_load function for module keccakf1600 returned:
explorer_1     | {:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /app/_build/prod/lib/keccakf1600/priv/keccakf1600.so: Exec format error\''}}
explorer_1     | 
explorer_1     | 2019-05-19T12:29:33.841 [error] GenServer #PID<0.8637.0> terminating
explorer_1     | ** (UndefinedFunctionError) function :keccakf1600.hash/2 is undefined (module :keccakf1600 is not available)
explorer_1     |     (keccakf1600) :keccakf1600.hash(:sha3_256, "7389a7497fbe32d6142573306b014f36d33329f2")
explorer_1     |     (explorer) lib/explorer/chain/address.ex:161: Explorer.Chain.Address.stream_every_four_bytes_of_sha256/1
explorer_1     |     (explorer) lib/explorer/chain/address.ex:135: Explorer.Chain.Address.checksum/2
explorer_1     |     (block_scout_web) lib/block_scout_web/templates/address/_responsive_hash.html.eex:1: BlockScoutWeb.AddressView."_responsive_hash.html"/1
explorer_1     |     (block_scout_web) lib/block_scout_web/templates/address/_link.html.eex:3: BlockScoutWeb.AddressView."_link.html"/1
explorer_1     |     (block_scout_web) lib/block_scout_web/templates/block/_tile.html.eex:37: BlockScoutWeb.BlockView."_tile.html"/1
explorer_1     |     (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
explorer_1     |     (phoenix) lib/phoenix/view.ex:406: Phoenix.View.render_to_string/3
explorer_1     | Last message: %Phoenix.Socket.Broadcast{event: "new_block", payload: %{average_block_time: #<Duration(P)>, block: %Explorer.Chain.Block{__meta__: #Ecto.Schema.Metadata<:loaded, "blocks">, consensus: true, difficulty: #Decimal<340282366920938463463374607431768211454>, gas_limit: #Decimal<8000000>, gas_used: #Decimal<0>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<114, 145, 211, 25, 236, 139, 170, 241, 246, 108, 125, 150, 91, 118, 156, 219, 135, 61, 196, 7, 37, 49, 129, 203, 175, 126, 193, 245, 225, 9, 78, 86>>}, inserted_at: #DateTime<2019-05-19 12:29:31.031131Z>, internal_transactions_indexed_at: nil, miner: %Explorer.Chain.Address{__meta__: #Ecto.Schema.Metadata<:loaded, "addresses">, contract_code: nil, contracts_creation_internal_transaction: #Ecto.Association.NotLoaded<association :contracts_creation_internal_transaction is not loaded>, contracts_creation_transaction: #Ecto.Association.NotLoaded<association :contracts_creation_transaction is not loaded>, decompiled_smart_contracts: #Ecto.Association.NotLoaded<association :decompiled_smart_contracts is not loaded>, fetched_coin_balance: #Explorer.Chain.Wei<0>, fetched_coin_balance_block_number: 47328, has_decompiled_code?: nil, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<115, 137, 167, 73, 127, 190, 50, 214, 20, 37, 115, 48, 107, 1, 79, 54, 211, 51, 41, 242>>}, inserted_at: #DateTime<2019-05-19 12:28:48.725858Z>, names: [], nonce: nil, smart_contract: #Ecto.Association.NotLoaded<association :smart_contract is not loaded>, token: #Ecto.Association.NotLoaded<association :token is not loaded>, updated_at: #DateTime<2019-05-19 12:28:48.725858Z>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<115, 137, 167, 73, 127, 190, 50, 214, 20, 37, 115, 48, 107, 1, 79, 54, 211, 51, 41, 242>>}, nephew_relations: #Ecto.Association.NotLoaded<association :nephew_relations is not loaded>, nephews: #Ecto.Association.NotLoaded<association :nephews is not loaded>, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<0, 0, 0, 0, 0, 0, 0, 0>>}, number: 47328, parent: #Ecto.Association.NotLoaded<association :parent is not loaded>, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<75, 176, 223, 63, 35, 73, 233, 103, 169, 77, 99, 36, 244, 248, 228, 94, 236, 42, 235, 200, 65, 80, 195, 20, 197, 167, 117, 45, ...>>}, rewards: [], size: 587, timestamp: #DateTime<2019-05-19 12:29:30.000000Z>, total_difficulty: #Decimal<16104883861634175598794593420530725600219518>, transaction_forks: #Ecto.Association.NotLoaded<association :transaction_forks is not loaded>, transactions: [], uncle_relations: #Ecto.Association.NotLoaded<association :uncle_relations is not loaded>, uncles: #Ecto.Association.NotLoaded<association :uncles is not loaded>, updated_at: #DateTime<2019-05-19 12:29:31.031131Z>}}, topic: "blocks:new_block"}
explorer_1     | State: %Phoenix.Socket{assigns: %{locale: "en"}, channel: BlockScoutWeb.BlockChannel, channel_pid: #PID<0.8637.0>, endpoint: BlockScoutWeb.Endpoint, handler: BlockScoutWeb.UserSocket, id: nil, join_ref: "3", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: BlockScoutWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "blocks:new_block", transport: :websocket, transport_pid: #PID<0.8428.0>}
explorer_1     | 2019-05-19T12:29:34.845 application=phoenix [info] JOIN "blocks:new_block" to BlockScoutWeb.BlockChannel
explorer_1     |   Transport:  :websocket
explorer_1     |   Serializer: Phoenix.Socket.V2.JSONSerializer
explorer_1     |   Parameters: %{}
explorer_1     | 2019-05-19T12:29:34.845 application=phoenix [info] Replied blocks:new_block :ok
explorer_1     | 2019-05-19T12:29:35.893 [warn] The on_load function for module keccakf1600 returned:
explorer_1     | {:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /app/_build/prod/lib/keccakf1600/priv/keccakf1600.so: Exec format error\''}}
explorer_1     | 
explorer_1     | 2019-05-19T12:29:35.899 [error] GenServer #PID<0.9365.0> terminating
explorer_1     | ** (UndefinedFunctionError) function :keccakf1600.hash/2 is undefined (module :keccakf1600 is not available)
explorer_1     |     (keccakf1600) :keccakf1600.hash(:sha3_256, "cd92348f89b4c191601b42d135eef0c6d73e77e1")
explorer_1     |     (explorer) lib/explorer/chain/address.ex:161: Explorer.Chain.Address.stream_every_four_bytes_of_sha256/1
explorer_1     |     (explorer) lib/explorer/chain/address.ex:135: Explorer.Chain.Address.checksum/2
explorer_1     |     (block_scout_web) lib/block_scout_web/templates/address/_responsive_hash.html.eex:1: BlockScoutWeb.AddressView."_responsive_hash.html"/1
explorer_1     |     (block_scout_web) lib/block_scout_web/templates/address/_link.html.eex:3: BlockScoutWeb.AddressView."_link.html"/1
explorer_1     |     (block_scout_web) lib/block_scout_web/templates/block/_tile.html.eex:37: BlockScoutWeb.BlockView."_tile.html"/1
explorer_1     |     (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
explorer_1     |     (phoenix) lib/phoenix/view.ex:406: Phoenix.View.render_to_string/3
explorer_1     | Last message: %Phoenix.Socket.Broadcast{event: "new_block", payload: %{average_block_time: #<Duration(P)>, block: %Explorer.Chain.Block{__meta__: #Ecto.Schema.Metadata<:loaded, "blocks">, consensus: true, difficulty: #Decimal<340282366920938463463374607431768211454>, gas_limit: #Decimal<8000000>, gas_used: #Decimal<0>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<155, 228, 55, 11, 37, 12, 91, 162, 251, 69, 222, 155, 65, 242, 36, 254, 224, 169, 117, 219, 224, 245, 93, 13, 73, 78, 92, 185, 186, 12, 202, 142>>}, inserted_at: #DateTime<2019-05-19 12:29:35.560514Z>, internal_transactions_indexed_at: nil, miner: %Explorer.Chain.Address{__meta__: #Ecto.Schema.Metadata<:loaded, "addresses">, contract_code: nil, contracts_creation_internal_transaction: #Ecto.Association.NotLoaded<association :contracts_creation_internal_transaction is not loaded>, contracts_creation_transaction: #Ecto.Association.NotLoaded<association :contracts_creation_transaction is not loaded>, decompiled_smart_contracts: #Ecto.Association.NotLoaded<association :decompiled_smart_contracts is not loaded>, fetched_coin_balance: #Explorer.Chain.Wei<0>, fetched_coin_balance_block_number: 47329, has_decompiled_code?: nil, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<205, 146, 52, 143, 137, 180, 193, 145, 96, 27, 66, 209, 53, 238, 240, 198, 215, 62, 119, 225>>}, inserted_at: #DateTime<2019-05-19 12:28:48.725858Z>, names: [], nonce: nil, smart_contract: #Ecto.Association.NotLoaded<association :smart_contract is not loaded>, token: #Ecto.Association.NotLoaded<association :token is not loaded>, updated_at: #DateTime<2019-05-19 12:28:48.725858Z>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<205, 146, 52, 143, 137, 180, 193, 145, 96, 27, 66, 209, 53, 238, 240, 198, 215, 62, 119, 225>>}, nephew_relations: #Ecto.Association.NotLoaded<association :nephew_relations is not loaded>, nephews: #Ecto.Association.NotLoaded<association :nephews is not loaded>, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<0, 0, 0, 0, 0, 0, 0, 0>>}, number: 47329, parent: #Ecto.Association.NotLoaded<association :parent is not loaded>, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<114, 145, 211, 25, 236, 139, 170, 241, 246, 108, 125, 150, 91, 118, 156, 219, 135, 61, 196, 7, 37, 49, 129, 203, 175, 126, 193, 245, ...>>}, rewards: [], size: 587, timestamp: #DateTime<2019-05-19 12:29:35.000000Z>, total_difficulty: #Decimal<16105224144001096537258056795138157368430972>, transaction_forks: #Ecto.Association.NotLoaded<association :transaction_forks is not loaded>, transactions: [], uncle_relations: #Ecto.Association.NotLoaded<association :uncle_relations is not loaded>, uncles: #Ecto.Association.NotLoaded<association :uncles is not loaded>, updated_at: #DateTime<2019-05-19 12:29:35.560514Z>}}, topic: "blocks:new_block"}
explorer_1     | State: %Phoenix.Socket{assigns: %{locale: "en"}, channel: BlockScoutWeb.BlockChannel, channel_pid: #PID<0.9365.0>, endpoint: BlockScoutWeb.Endpoint, handler: BlockScoutWeb.UserSocket, id: nil, join_ref: "6", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: BlockScoutWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "blocks:new_block", transport: :websocket, transport_pid: #PID<0.8428.0>}
explorer_1     | 2019-05-19T12:29:36.917 application=phoenix [info] JOIN "blocks:new_block" to BlockScoutWeb.BlockChannel
explorer_1     |   Transport:  :websocket
explorer_1     |   Serializer: Phoenix.Socket.V2.JSONSerializer
explorer_1     |   Parameters: %{}
explorer_1     | 2019-05-19T12:29:36.927 application=phoenix [info] Replied blocks:new_block :ok
explorer_1     | 2019-05-19T12:29:40.955 [warn] The on_load function for module keccakf1600 returned:
explorer_1     | {:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /app/_build/prod/lib/keccakf1600/priv/keccakf1600.so: Exec format error\''}}
explorer_1     | 
explorer_1     | 2019-05-19T12:29:40.959 [error] GenServer #PID<0.9582.0> terminating
explorer_1     | ** (UndefinedFunctionError) function :keccakf1600.hash/2 is undefined (module :keccakf1600 is not available)
explorer_1     |     (keccakf1600) :keccakf1600.hash(:sha3_256, "7389a7497fbe32d6142573306b014f36d33329f2")
explorer_1     |     (explorer) lib/explorer/chain/address.ex:161: Explorer.Chain.Address.stream_every_four_bytes_of_sha256/1
explorer_1     |     (explorer) lib/explorer/chain/address.ex:135: Explorer.Chain.Address.checksum/2
explorer_1     |     (block_scout_web) lib/block_scout_web/templates/address/_responsive_hash.html.eex:1: BlockScoutWeb.AddressView."_responsive_hash.html"/1
explorer_1     |     (block_scout_web) lib/block_scout_web/templates/address/_link.html.eex:3: BlockScoutWeb.AddressView."_link.html"/1
explorer_1     |     (block_scout_web) lib/block_scout_web/templates/block/_tile.html.eex:37: BlockScoutWeb.BlockView."_tile.html"/1
explorer_1     |     (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
explorer_1     |     (phoenix) lib/phoenix/view.ex:406: Phoenix.View.render_to_string/3
explorer_1     | Last message: %Phoenix.Socket.Broadcast{event: "new_block", payload: %{average_block_time: #<Duration(P)>, block: %Explorer.Chain.Block{__meta__: #Ecto.Schema.Metadata<:loaded, "blocks">, consensus: true, difficulty: #Decimal<340282366920938463463374607431768211454>, gas_limit: #Decimal<8000000>, gas_used: #Decimal<0>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<98, 157, 227, 13, 226, 180, 189, 103, 132, 68, 150, 202, 21, 132, 65, 141, 171, 163, 235, 44, 87, 206, 250, 3, 137, 101, 72, 217, 177, 135, 163, 162>>}, inserted_at: #DateTime<2019-05-19 12:29:40.617720Z>, internal_transactions_indexed_at: nil, miner: %Explorer.Chain.Address{__meta__: #Ecto.Schema.Metadata<:loaded, "addresses">, contract_code: nil, contracts_creation_internal_transaction: #Ecto.Association.NotLoaded<association :contracts_creation_internal_transaction is not loaded>, contracts_creation_transaction: #Ecto.Association.NotLoaded<association :contracts_creation_transaction is not loaded>, decompiled_smart_contracts: #Ecto.Association.NotLoaded<association :decompiled_smart_contracts is not loaded>, fetched_coin_balance: #Explorer.Chain.Wei<0>, fetched_coin_balance_block_number: 47330, has_decompiled_code?: nil, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<115, 137, 167, 73, 127, 190, 50, 214, 20, 37, 115, 48, 107, 1, 79, 54, 211, 51, 41, 242>>}, inserted_at: #DateTime<2019-05-19 12:28:48.725858Z>, names: [], nonce: nil, smart_contract: #Ecto.Association.NotLoaded<association :smart_contract is not loaded>, token: #Ecto.Association.NotLoaded<association :token is not loaded>, updated_at: #DateTime<2019-05-19 12:28:48.725858Z>}, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<115, 137, 167, 73, 127, 190, 50, 214, 20, 37, 115, 48, 107, 1, 79, 54, 211, 51, 41, 242>>}, nephew_relations: #Ecto.Association.NotLoaded<association :nephew_relations is not loaded>, nephews: #Ecto.Association.NotLoaded<association :nephews is not loaded>, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<0, 0, 0, 0, 0, 0, 0, 0>>}, number: 47330, parent: #Ecto.Association.NotLoaded<association :parent is not loaded>, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<155, 228, 55, 11, 37, 12, 91, 162, 251, 69, 222, 155, 65, 242, 36, 254, 224, 169, 117, 219, 224, 245, 93, 13, 73, 78, 92, 185, ...>>}, rewards: [], size: 587, timestamp: #DateTime<2019-05-19 12:29:40.000000Z>, total_difficulty: #Decimal<16105564426368017475721520169745589136642426>, transaction_forks: #Ecto.Association.NotLoaded<association :transaction_forks is not loaded>, transactions: [], uncle_relations: #Ecto.Association.NotLoaded<association :uncle_relations is not loaded>, uncles: #Ecto.Association.NotLoaded<association :uncles is not loaded>, updated_at: #DateTime<2019-05-19 12:29:40.617720Z>}}, topic: "blocks:new_block"}
explorer_1     | State: %Phoenix.Socket{assigns: %{locale: "en"}, channel: BlockScoutWeb.BlockChannel, channel_pid: #PID<0.9582.0>, endpoint: BlockScoutWeb.Endpoint, handler: BlockScoutWeb.UserSocket, id: nil, join_ref: "7", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: BlockScoutWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "blocks:new_block", transport: :websocket, transport_pid: #PID<0.8428.0>}
explorer_1     | 2019-05-19T12:29:41.964 application=phoenix [info] JOIN "blocks:new_block" to BlockScoutWeb.BlockChannel
explorer_1     |   Transport:  :websocket
explorer_1     |   Serializer: Phoenix.Socket.V2.JSONSerializer
explorer_1     |   Parameters: %{}
explorer_1     | 2019-05-19T12:29:41.970 application=phoenix [info] Replied blocks:new_block :ok
explorer_1     | 2019-05-19T12:29:42.746 [warn] The on_load function for module keccakf1600 returned:
explorer_1     | {:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /app/_build/prod/lib/keccakf1600/priv/keccakf1600.so: Exec format error\''}}
explorer_1     | 
explorer_1     | 2019-05-19T12:29:43.077 count=1 [error] Task #PID<0.10383.0> started from Indexer.Fetcher.TokenBalance terminating
explorer_1     | ** (FunctionClauseError) no function clause matching in Exception.message/1
explorer_1     |     (elixir) lib/exception.ex:56: Exception.message(nil)
explorer_1     |     (ethereum_jsonrpc) lib/ethereum_jsonrpc/contract.ex:93: EthereumJSONRPC.Contract.format_error/1
explorer_1     |     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
explorer_1     |     (explorer) lib/explorer/token/balance_reader.ex:36: Explorer.Token.BalanceReader.get_balances_of/1
explorer_1     |     (indexer) lib/indexer/token_balances.ex:38: Indexer.TokenBalances.fetch_token_balances_from_blockchain/1
explorer_1     |     (indexer) lib/indexer/fetcher/token_balance.ex:100: Indexer.Fetcher.TokenBalance.fetch_from_blockchain/1
explorer_1     |     (indexer) lib/indexer/fetcher/token_balance.ex:85: Indexer.Fetcher.TokenBalance.run/2
explorer_1     |     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
explorer_1     | Function: &Indexer.BufferedTask.log_run/1
explorer_1     |     Args: [%{batch: [{<<218, 138, 6, 241, 201, 16, 202, 177, 138, 209, 135, 190, 31, 170, 43, 134, 6, 194, 236, 134>>, <<81, 181, 138, 213, 233, 160, 167, 66, 22, 67, 97, 0, 20, 221, 200, 158, 30, 251, 82, 178>>, 3795, 0}], callback_module: Indexer.Fetcher.TokenBalance, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://node0:8545", method_to_url: [eth_getBalance: "http://node0:8545", trace_block: "http://node0:8545", trace_replayTransaction: "http://node0:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], metadata: []}]
explorer_1     | 2019-05-19T12:29:43.614 count=1 [error] Task #PID<0.10560.0> started from Indexer.Fetcher.TokenBalance terminating
explorer_1     | ** (FunctionClauseError) no function clause matching in Exception.message/1
explorer_1     |     (elixir) lib/exception.ex:56: Exception.message(nil)
explorer_1     |     (ethereum_jsonrpc) lib/ethereum_jsonrpc/contract.ex:93: EthereumJSONRPC.Contract.format_error/1
explorer_1     |     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
explorer_1     |     (explorer) lib/explorer/token/balance_reader.ex:36: Explorer.Token.BalanceReader.get_balances_of/1
explorer_1     |     (indexer) lib/indexer/token_balances.ex:38: Indexer.TokenBalances.fetch_token_balances_from_blockchain/1
explorer_1     |     (indexer) lib/indexer/fetcher/token_balance.ex:100: Indexer.Fetcher.TokenBalance.fetch_from_blockchain/1
explorer_1     |     (indexer) lib/indexer/fetcher/token_balance.ex:85: Indexer.Fetcher.TokenBalance.run/2
explorer_1     |     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
explorer_1     | Function: &Indexer.BufferedTask.log_run/1
explorer_1     |     Args: [%{batch: [{<<218, 138, 6, 241, 201, 16, 202, 177, 138, 209, 135, 190, 31, 170, 43, 134, 6, 194, 236, 134>>, <<81, 181, 138, 213, 233, 160, 167, 66, 22, 67, 97, 0, 20, 221, 200, 158, 30, 251, 82, 178>>, 3795, 0}], callback_module: Indexer.Fetcher.TokenBalance, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://node0:8545", method_to_url: [eth_getBalance: "http://node0:8545", trace_block: "http://node0:8545", trace_replayTransaction: "http://node0:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], metadata: []}]
explorer_1     | 2019-05-19T12:29:43.615 [warn] The on_load function for module keccakf1600 returned:
explorer_1     | {:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /app/_build/prod/lib/keccakf1600/priv/keccakf1600.so: Exec format error\''}}
explorer_1     | 
explorer_1     | 2019-05-19T12:29:44.122 [warn] The on_load function for module keccakf1600 returned:
explorer_1     | {:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /app/_build/prod/lib/keccakf1600/priv/keccakf1600.so: Exec format error\''}}
explorer_1     | 
explorer_1     | 2019-05-19T12:29:44.127 count=1 [error] Task #PID<0.10640.0> started from Indexer.Fetcher.TokenBalance terminating
explorer_1     | ** (FunctionClauseError) no function clause matching in Exception.message/1
explorer_1     |     (elixir) lib/exception.ex:56: Exception.message(nil)
explorer_1     |     (ethereum_jsonrpc) lib/ethereum_jsonrpc/contract.ex:93: EthereumJSONRPC.Contract.format_error/1
explorer_1     |     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
explorer_1     |     (explorer) lib/explorer/token/balance_reader.ex:36: Explorer.Token.BalanceReader.get_balances_of/1
explorer_1     |     (indexer) lib/indexer/token_balances.ex:38: Indexer.TokenBalances.fetch_token_balances_from_blockchain/1
explorer_1     |     (indexer) lib/indexer/fetcher/token_balance.ex:100: Indexer.Fetcher.TokenBalance.fetch_from_blockchain/1
explorer_1     |     (indexer) lib/indexer/fetcher/token_balance.ex:85: Indexer.Fetcher.TokenBalance.run/2
explorer_1     |     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
explorer_1     | Function: &Indexer.BufferedTask.log_run/1
explorer_1     |     Args: [%{batch: [{<<218, 138, 6, 241, 201, 16, 202, 177, 138, 209, 135, 190, 31, 170, 43, 134, 6, 194, 236, 134>>, <<81, 181, 138, 213, 233, 160, 167, 66, 22, 67, 97, 0, 20, 221, 200, 158, 30, 251, 82, 178>>, 3795, 0}], callback_module: Indexer.Fetcher.TokenBalance, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://node0:8545", method_to_url: [eth_getBalance: "http://node0:8545", trace_block: "http://node0:8545", trace_replayTransaction: "http://node0:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], metadata: []}]
explorer_1     | 2019-05-19T12:29:44.407 [warn] The on_load function for module keccakf1600 returned:
explorer_1     | {:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /app/_build/prod/lib/keccakf1600/priv/keccakf1600.so: Exec format error\''}}
explorer_1     | 
explorer_1     | 2019-05-19T12:29:44.415 count=1 [error] Task #PID<0.10693.0> started from Indexer.Fetcher.TokenBalance terminating
explorer_1     | ** (FunctionClauseError) no function clause matching in Exception.message/1
explorer_1     |     (elixir) lib/exception.ex:56: Exception.message(nil)
explorer_1     |     (ethereum_jsonrpc) lib/ethereum_jsonrpc/contract.ex:93: EthereumJSONRPC.Contract.format_error/1
explorer_1     |     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
explorer_1     |     (explorer) lib/explorer/token/balance_reader.ex:36: Explorer.Token.BalanceReader.get_balances_of/1
explorer_1     |     (indexer) lib/indexer/token_balances.ex:38: Indexer.TokenBalances.fetch_token_balances_from_blockchain/1
explorer_1     |     (indexer) lib/indexer/fetcher/token_balance.ex:100: Indexer.Fetcher.TokenBalance.fetch_from_blockchain/1
explorer_1     |     (indexer) lib/indexer/fetcher/token_balance.ex:85: Indexer.Fetcher.TokenBalance.run/2
explorer_1     |     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
explorer_1     | Function: &Indexer.BufferedTask.log_run/1
explorer_1     |     Args: [%{batch: [{<<218, 138, 6, 241, 201, 16, 202, 177, 138, 209, 135, 190, 31, 170, 43, 134, 6, 194, 236, 134>>, <<81, 181, 138, 213, 233, 160, 167, 66, 22, 67, 97, 0, 20, 221, 200, 158, 30, 251, 82, 178>>, 3795, 0}], callback_module: Indexer.Fetcher.TokenBalance, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://node0:8545", method_to_url: [eth_getBalance: "http://node0:8545", trace_block: "http://node0:8545", trace_replayTransaction: "http://node0:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], metadata: []}]
explorer_1     | 2019-05-19T12:29:44.797 [warn] The on_load function for module keccakf1600 returned:
explorer_1     | {:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /app/_build/prod/lib/keccakf1600/priv/keccakf1600.so: Exec format error\''}}
explorer_1     | 
``` 

### Environment

My Dockerfile is:
```
FROM bitwalker/alpine-elixir-phoenix
RUN apk --no-cache --update add alpine-sdk gmp-dev automake libtool inotify-tools autoconf python

EXPOSE 4000

ENV PORT=4000 \
    MIX_ENV="prod" \
    SECRET_KEY_BASE="RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5"

# Cache elixir deps
ADD mix.exs mix.lock ./
ADD apps/block_scout_web/mix.exs ./apps/block_scout_web/
ADD apps/explorer/mix.exs ./apps/explorer/
ADD apps/ethereum_jsonrpc/mix.exs ./apps/ethereum_jsonrpc/
ADD apps/indexer/mix.exs ./apps/indexer/

# RUN mix do local.hex --force, local.rebar --force
RUN mix do deps.get, deps.compile

ADD . .

ARG COIN
RUN if [ "$COIN" != "" ]; then sed -i s/"POA"/"${COIN}"/g apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po; fi

# Run forderground build and phoenix digest
RUN mix compile

# Add blockscout npm deps
RUN cd apps/block_scout_web/assets/ && \
    npm install && \
    npm rebuild node-sass && \
    npm run deploy && \
    cd -

RUN cd apps/explorer/ && \
    npm install && \
    apk del --force-broken-world alpine-sdk gmp-dev automake libtool inotify-tools autoconf python
```

And I am running this script on start:
```
#!/bin/bash
set -e

mix do ecto.drop --force, ecto.create, ecto.migrate
echo " Launching Phoenix web server..."
mix phx.server
```

### Steps to reproduce

I am running `docker-compose up`

### Actual behaviour

<img width="1176" alt="Screenshot 2019-05-19 at 15 42 35" src="https://user-images.githubusercontent.com/12232750/57982349-d28bef00-7a4c-11e9-85b1-5929101bdeef.png">

**Comment by Daniel-K-Ivanov** [comment]
I have successfully linked the database. No trouble with that, however I think that the `keccakf1600` module is causing trouble.

**Comment by Daniel-K-Ivanov** [comment]
I've managed to fix the problem. The docker was using the binaries from my MacOS build library and this was causing the error. I've deleted the binary and force compiled it in the docker.
