### ISSUE TITLE
Failed to decode Ethereum JSONRPC response in debug_traceTransaction

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2085]
```
2019-06-03T08:53:32.864 fetcher=internal_transaction count=10 [error] Task #PID<0.20408.48> started from Indexer.Fetcher.InternalTransaction terminating
** (FunctionClauseError) no function clause matching in EthereumJSONRPC.Geth.Call.elixir_to_internal_transaction_params/1
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/geth/call.ex:320: EthereumJSONRPC.Geth.Call.elixir_to_internal_transaction_params(%{"blockNumber" => 584340, "callType" => "staticcall", "error" => "execution reverted", "from" => "0x3858636f27e269d23db2ef1fcca5f93dcaa564cd", "gas" => 6468087, "gasUsed" => 5300, "index" => 6, "input" => "0x09d10a5e00000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000002", "to" => "0x79073fc2117dd054fcedacad1e7018c9cbe3ec0b", "traceAddress" => [1, 3], "transactionHash" => "0xbc38745b826f058ed2f6c93fa5b145323857f06bbb5230b6a6a50e09e0915857", "transactionIndex" => 0, "type" => "call", "value" => 0})
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/geth.ex:168: EthereumJSONRPC.Geth.debug_trace_transaction_response_to_internal_transactions_params/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/geth.ex:110: EthereumJSONRPC.Geth.debug_trace_transaction_responses_to_internal_transactions_params/3
    (indexer) lib/indexer/fetcher/internal_transaction.ex:175: Indexer.Fetcher.InternalTransaction.run/2
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [{703508, <<172, 87, 70, 4, 166, 175, 182, 186, 170, 150, 159, 243, 10, 82, 176, 46, 205, 59, 88, 9, 244, 83, 27, 114, 241, 193, 248, 153, 197, 249, 191, 62>>, 0}, {703641, <<1, 77, 180, 230, 116, 153, 95, 219, 150, 65, 32, 125, 148, 133, 254, 91, 114, 120, 16, 123, 173, 113, 169, 71, 14, 174, 95, 183, 33, 201, 186, 249>>, 0}, {703610, <<209, 246, 209, 7, 24, 89, 221, 173, 59, 21, 155, 182, 254, 127, 24, 138, 84, 231, 190, 253, 76, 136, 207, 210, 220, 203, 251, 210, 101, 88, 46, 176>>, 0}, {703626, <<13, 65, 252, 103, 20, 46, 211, 1, 196, 185, 40, 30, 19, 189, 133, 175, 124, 241, 126, 109, 86, 128, 96, 239, 149, 47, 1, 21, 151, 183, 33, 227>>, 0}, {703339, <<112, 28, 128, 108, 228, 32, 164, 131, 68, 187, 212, 108, 31, 73, 96, 6, 255, 249, 200, 58, 239, 14, 91, 161, 224, 225, 119, 169, 168, 97, 99, 157>>, 1}, {703226, <<24, 232, 44, 163, 74, 8, 217, 245, 90, 156, 80, 221, 0, 152, 30, 180, 253, 165, 212, 91, 231, 150, 217, 185, 245, 143, 169, 73, 14, 108, 61, 136>>, 2}, {703624, <<171, 27, 196, 104, 235, 176, 43, 21, 139, 12, 208, 108, 41, 209, 215, 1, 69, 199, 141, 105, 189, 120, 167, 124, 89, 165, 128, 140, 88, 68, 44, 41>>, 0}, {584340, <<188, 56, 116, 91, 130, 111, 5, 142, 210, 246, 201, 63, 165, 177, 69, 50, 56, 87, 240, 107, 187, 82, 48, 182, 166, 165, 14, 9, 224, 145, 88, 87>>, 0}, {703260, <<174, 104, 96, 254, 193, 106, 194, 196, 104, 52, 42, 102, 224, 205, 75, 74, 19, 143, 33, 4, 217, 187, 77, 139, 83, 196, 91, 227, 135, 25, 156, 4>>, 0}, {703252, <<8, 216, 207, 41, 139, 177, 209, 170, 59, 202, 7, 33, 6, 73, 164, 30, 61, 197, 202, 65, 125, 230, 247, 4, 127, 223, 205, 79, 203, 250, 79, 180>>, 0}], callback_module: Indexer.Fetcher.InternalTransaction, callback_module_state: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://XXX", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], metadata: [fetcher: :internal_transaction]}]
2019-06-03T08:53:37.104 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for transactions: [%{data: %{block_number: 188681, transaction_hash: "0xdf9c1ee1491daddec829010934495388abbcdb46d7d13d5a2e67800366dc251a", transaction_index: 0}, message: :timeout}, %{data: %{block_number: 280711, transaction_hash: "0xa2617863c4c0a99e45fc9adad82b4d6888ed34d1acfe0790998b90ffc8fdf2ae", transaction_index: 0}, message: :timeout}, %{data: %{block_number: 247179, transaction_hash: "0xea02485b56042f3bf1dfe0fb754fad0c65cf7a11c1a24a52ade418488cd655d5", transaction_index: 0}, message: :timeout}]
```

**Comment by saneery** [comment]
@vbaranov 
Looks like relate to https://github.com/poanetwork/blockscout/issues/2084. Same error.
