### ISSUE TITLE
function Plug.Cowboy.Translator.translate/4 is undefined

### ISSUE THREAD

**Issue by SlightlyCyborg** [poanetwork/blockscout#2153]
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```
* Operating System:
`5.1.8-arch1-1-ARCH #1 SMP PREEMPT Sun Jun 9 20:28:28 UTC 2019 x86_64 GNU/Linux`

### Steps to reproduce
This happens when running `mix phx.server`

### Expected behaviour
Should start properly

### Actual behaviour

```
2019-06-13T03:23:43.311 [error] Failure while translating Erlang's logger event
** (UndefinedFunctionError) function Plug.Cowboy.Translator.translate/4 is undefined (module Plug.Cowboy.Translator is not available)
    (plug_cowboy) Plug.Cowboy.Translator.translate(:debug, :error, :report, {{:erl_prim_loader, :file_error}, 'File operation error: emfile. Target: /home/alex/hacks/block-scout_transactions-per-day-graph/fork2/_build/dev/lib/ecto/ebin/Elixir.Ecto.Repo.Schema.beam. Function: get_file. Process: code_server.'})
    (logger) lib/logger/erlang_handler.ex:104: Logger.ErlangHandler.translate/6
    (logger) lib/logger/erlang_handler.ex:97: Logger.ErlangHandler.translate/5
    (logger) lib/logger/erlang_handler.ex:27: anonymous fn/3 in Logger.ErlangHandler.log/2
    (logger) lib/logger.ex:867: Logger.normalize_message/2
    (logger) lib/logger.ex:690: Logger.__do_log__/3
    (kernel) logger_backend.erl:51: :logger_backend.call_handlers/3
    (kernel) logger_backend.erl:38: :logger_backend.log_allowed/2
    (kernel) logger_server.erl:279: :logger_server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by vbaranov** [comment]
@SlightlyCyborg is this still actual? If yes, try to reinstall `inotify-tools`. Btw, what version of Blockscout are you using?

**Comment by SlightlyCyborg** [comment]
Nope. It was a problem with kerl, so I just uninstalled everything elixir and erlang and then reinstalled from source.
