### ISSUE TITLE
ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time on block_uncle insert

### ISSUE THREAD

**Issue by APshenkin** [poanetwork/blockscout#2154]
Got an error on mainnet sync

```
iex(1)> 2019-06-13T05:57:47.629 application=explorer fetcher=block_uncle count=10 import_id=11169026 transaction_id=11169090 [error] Could not insert all of chunk into Elixir.Explorer.Chain.Block using options because of error.
Chunk Size: 10
Chunk:
[%{consensus: false, difficulty: #Decimal<1963985851093218>, gas_limit: #Decimal<8000029>, gas_used: #Decimal<7991624>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<251, 235, 96, 68, 130, 4, 96, 166, 158, 197, 245, 166, 163, 3, 209, 83, 156, 111, 101, 125, 39, 46, 108, 27, 254, 217, 100, 205, 114, 38, 122, 229>>}, inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<143, 206, 30, 242, 127, 58, 221, 20, 17, 199, 169, 155, 228, 2, 222, 89, 138, 211, 131, 137>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<229, 237, 87, 50, 47, 220, 171, 165>>}, number: 7947776, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<105, 163, 255, 251, 204, 24, 37, 57, 177, 83, 48, 180, 2, 189, 133, 147, 228, 186, 142, 113, 121, 208, 231, 251, 80, 199, 215, 165, 165, 194, 255, 152>>}, size: 33138, timestamp: #DateTime<2019-06-13 02:57:45.000000Z>, total_difficulty: #Decimal<10585287418777719232817>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}, %{consensus: false, difficulty: #Decimal<1963985851093218>, gas_limit: #Decimal<8000029>, gas_used: #Decimal<7991624>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<251, 235, 96, 68, 130, 4, 96, 166, 158, 197, 245, 166, 163, 3, 209, 83, 156, 111, 101, 125, 39, 46, 108, 27, 254, 217, 100, 205, 114, 38, 122, 229>>}, inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<143, 206, 30, 242, 127, 58, 221, 20, 17, 199, 169, 155, 228, 2, 222, 89, 138, 211, 131, 137>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<229, 237, 87, 50, 47, 220, 171, 165>>}, number: 7947776, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<105, 163, 255, 251, 204, 24, 37, 57, 177, 83, 48, 180, 2, 189, 133, 147, 228, 186, 142, 113, 121, 208, 231, 251, 80, 199, 215, 165, 165, 194, 255, 152>>}, size: 33138, timestamp: #DateTime<2019-06-13 02:57:45.000000Z>, total_difficulty: #Decimal<10585287418777719232817>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}, %{consensus: false, difficulty: #Decimal<1963985985310946>, gas_limit: #Decimal<8000000>, gas_used: #Decimal<7994379>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<174, 200, 188, 175, 92, 145, 132, 9, 21, 144, 82, 91, 139, 46, 75, 171, 249, 52, 216, 239, 137, 30, 47, 219, 12, 164, 83, 62, 49, 172, 148, 153>>}, inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<234, 103, 79, 221, 231, 20, 253, 151, 157, 227, 237, 240, 245, 106, 169, 113, 107, 137, 142, 200>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<40, 183, 171, 32, 0, 126, 136, 79>>}, number: 7947777, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<220, 238, 125, 247, 252, 185, 135, 133, 237, 26, 117, 182, 48, 14, 148, 150, 141, 102, 189, 84, 104, 173, 132, 200, 92, 173, 196, 67, 213, 57, 11, 102>>}, size: 42759, timestamp: #DateTime<2019-06-13 02:57:59.000000Z>, total_difficulty: #Decimal<10585289382763704543763>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}, %{consensus: false, difficulty: #Decimal<1960140922200413>, gas_limit: #Decimal<8007776>, gas_used: #Decimal<8006739>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<96, 190, 239, 170, 184, 224, 238, 149, 84, 14, 66, 91, 94, 21, 216, 43, 75, 34, 34, 254, 132, 189, 80, 11, 28, 72, 216, 206, 159, 137, 130, 197>>}, inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<90, 11, 84, 213, 220, 23, 224, 170, 220, 56, 61, 45, 180, 59, 10, 13, 62, 2, 156, 76>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<247, 28, 5, 144, 2, 105, 148, 84>>}, number: 7947796, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<164, 252, 102, 8, 102, 150, 212, 138, 220, 58, 27, 85, 252, 47, 217, 92, 37, 62, 250, 129, 19, 34, 192, 23, 88, 165, 17, 180, 229, 27, 121, 61>>}, size: 37385, timestamp: #DateTime<2019-06-13 03:02:49.000000Z>, total_difficulty: #Decimal<10585326686946398756549>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}, %{consensus: false, difficulty: #Decimal<1961097225621633>, gas_limit: #Decimal<8000029>, gas_used: #Decimal<7982719>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<82, 98, 71, 131, 32, 15, 82, 101, 237, 222, 221, 85, 119, 181, 3, 62, 160, 189, 207, 2, 222, 200, 242, 254, 212, 234, 178, 74, 17, 86, 78, 37>>}, inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<178, 147, 11, 53, 132, 74, 35, 15, 0, 229, 20, 49, 172, 174, 150, 254, 84, 58, 3, 71>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<151, 105, 82, 188, 252, 197, 133, 121>>}, number: 7947804, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<142, 165, 189, 23, 229, 80, 31, 148, 78, 226, 224, 204, 77, 231, 125, 132, 135, 50, 115, 173, 230, 66, 177, 127, 120, 54, 135, 132, 48, 165, 64, 25>>}, size: 28742, timestamp: #DateTime<2019-06-13 03:04:25.000000Z>, total_difficulty: #Decimal<10585342377643998698015>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}, %{consensus: false, difficulty: #Decimal<1968771607050847>, gas_limit: #Decimal<8000000>, gas_used: #Decimal<3786293>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<244, 106, 131, 250, 231, 18, 71, 37, 44, 108, 135, 149, 172, 236, 158, 178, 35, 230, 154, 141, 85, 51, 85, 127, 250, 9, 248, 108, 202, 43, 106, 60>>}, inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<0, 25, 47, 177, 13, 243, 124, 159, 178, 104, 41, 235, 44, 198, 35, 205, 27, 245, 153, 232>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<43, 172, 179, 192, 0, 113, 178, 190>>}, number: 7947813, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<116, 249, 150, 66, 80, 13, 233, 157, 205, 79, 30, 90, 195, 130, 241, 23, 103, 102, 68, 42, 15, 254, 7, 9, 184, 116, 254, 205, 24, 34, 103, 172>>}, size: 16377, timestamp: #DateTime<2019-06-13 03:05:22.000000Z>, total_difficulty: #Decimal<10585360069702468637536>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}, %{consensus: false, difficulty: #Decimal<1970692153795919>, gas_limit: #Decimal<8000029>, gas_used: #Decimal<7984674>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<42, 181, 209, 221, 80, 6, 241, 137, 194, 118, 71, 87, 36, 228, 74, 242, 214, 30, 94, 155, 19, 22, 8, 170, 164, 151, 49, 181, 149, 71, 23, 38>>}, inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<157, 109, 73, 43, 213, 0, 218, 91, 51, 207, 149, 165, 214, 16, 167, 51, 96, 252, 170, 160>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<15, 35, 83, 17, 76, 47, 76, 137>>}, number: 7947822, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<246, 212, 23, 49, 76, 82, 8, 196, 251, 150, 93, 10, 212, 77, 28, 232, 144, 61, 4, 142, 65, 70, 112, 136, 220, 19, 215, 54, 14, 230, 179, 106>>}, size: 11464, timestamp: #DateTime<2019-06-13 03:07:12.000000Z>, total_difficulty: #Decimal<10585377790548359063875>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}, %{consensus: false, difficulty: #Decimal<1974543777908467>, gas_limit: #Decimal<8000029>, gas_used: #Decimal<7979985>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<103, 153, 206, 127, 195, 5, 23, 133, 162, 30, 109, 119, 97, 209, 168, 139, 145, 105, 52, 200, 77, 191, 143, 112, 148, 48, 108, 12, 172, 189, 249, 212>>}, inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<82, 188, 68, 213, 55, 131, 9, 238, 42, 191, 21, 57, 191, 113, 222, 27, 125, 123, 227, 181>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<189, 27, 60, 152, 7, 85, 164, 138>>}, number: 7947831, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<81, 175, 94, 253, 243, 218, 250, 105, 212, 94, 33, 217, 93, 218, 12, 165, 96, 109, 38, 193, 19, 181, 59, 199, 64, 210, 227, 39, 210, 27, 86, 143>>}, size: 37113, timestamp: #DateTime<2019-06-13 03:08:47.000000Z>, total_difficulty: #Decimal<10585395563377563169250>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}, %{consensus: false, difficulty: #Decimal<1976472782585493>, gas_limit: #Decimal<8007840>, gas_used: #Decimal<7557724>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<190, 164, 145, 209, 219, 83, 142, 17, 108, 133, 212, 84, 237, 150, 149, 241, 37, 32, 100, 131, 107, 139, 74, 159, 181, 188, 165, 144, 106, 148, 187, 248>>}, inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<130, 155, 216, 36, 176, 22, 50, 106, 64, 29, 8, 59, 51, 208, 146, 41, 51, 51, 168, 48>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<197, 117, 6, 200, 1, 13, 118, 110>>}, number: 7947833, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<229, 65, 19, 212, 219, 65, 234, 44, 59, 210, 20, 254, 81, 28, 86, 173, 46, 169, 116, 71, 242, 116, 10, 84, 52, 25, 102, 90, 12, 121, 113, 207>>}, size: 31463, timestamp: #DateTime<2019-06-13 03:09:05.000000Z>, total_difficulty: #Decimal<10585399515358390584994>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}, %{consensus: false, difficulty: #Decimal<1965859753639376>, gas_limit: #Decimal<8000000>, gas_used: #Decimal<7980240>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<38, 41, 238, 231, 122, 41, 138, 103, 12, 169, 202, 91, 16, 227, 18, 222, 48, 242, 52, 237, 13, 76, 235, 155, 50, 104, 86, 225, 208, 28, 75, 107>>}, inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<234, 103, 79, 221, 231, 20, 253, 151, 157, 227, 237, 240, 245, 106, 169, 113, 107, 137, 142, 200>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<80, 20, 110, 176, 3, 7, 101, 9>>}, number: 7947864, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<107, 200, 158, 30, 90, 66, 169, 249, 152, 242, 120, 47, 145, 163, 162, 7, 131, 142, 206, 1, 202, 209, 194, 104, 187, 5, 205, 250, 106, 54, 218, 68>>}, size: 33941, timestamp: #DateTime<2019-06-13 03:17:51.000000Z>, total_difficulty: #Decimal<10585460671088467256227>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}]
Options:
[conflict_target: :hash, on_conflict: #Ecto.Query<from b0 in Explorer.Chain.Block, where: fragment("EXCLUDED.consensus <> ?", b0.consensus) or fragment("EXCLUDED.difficulty <> ?", b0.difficulty) or fragment("EXCLUDED.gas_limit <> ?", b0.gas_limit) or fragment("EXCLUDED.gas_used <> ?", b0.gas_used) or fragment("EXCLUDED.miner_hash <> ?", b0.miner_hash) or fragment("EXCLUDED.nonce <> ?", b0.nonce) or fragment("EXCLUDED.number <> ?", b0.number) or fragment("EXCLUDED.parent_hash <> ?", b0.parent_hash) or fragment("EXCLUDED.size <> ?", b0.size) or fragment("EXCLUDED.timestamp <> ?", b0.timestamp) or fragment("EXCLUDED.total_difficulty <> ?", b0.total_difficulty) or fragment("EXCLUDED.internal_transactions_indexed_at <> ?", b0.internal_transactions_indexed_at), update: [set: [consensus: fragment("EXCLUDED.consensus"), difficulty: fragment("EXCLUDED.difficulty"), gas_limit: fragment("EXCLUDED.gas_limit"), gas_used: fragment("EXCLUDED.gas_used"), internal_transactions_indexed_at: fragment("EXCLUDED.internal_transactions_indexed_at"), miner_hash: fragment("EXCLUDED.miner_hash"), nonce: fragment("EXCLUDED.nonce"), number: fragment("EXCLUDED.number"), parent_hash: fragment("EXCLUDED.parent_hash"), size: fragment("EXCLUDED.size"), timestamp: fragment("EXCLUDED.timestamp"), total_difficulty: fragment("EXCLUDED.total_difficulty"), inserted_at: fragment("LEAST(?, EXCLUDED.inserted_at)", b0.inserted_at), updated_at: fragment("GREATEST(?, EXCLUDED.updated_at)", b0.updated_at)]]>, returning: true, timeout: 60000, timestamps: %{inserted_at: #DateTime<2019-06-13 05:57:47.605791Z>, updated_at: #DateTime<2019-06-13 05:57:47.605791Z>}]
Exception:
** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time
    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
    (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:529: Ecto.Adapters.SQL.insert_all/8
    (ecto) lib/ecto/repo/schema.ex:56: Ecto.Repo.Schema.do_insert_all/6
    (explorer) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain/import.ex:285: Explorer.Chain.Import.insert_changes_list/3
    (ecto) lib/ecto/multi.ex:580: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
iex(1)> 2019-06-13T05:57:47.631 fetcher=block_uncle count=10 [error] Task #PID<0.12192.37> started from Indexer.Fetcher.UncleBlock terminating
** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time
    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
    (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:529: Ecto.Adapters.SQL.insert_all/8
    (ecto) lib/ecto/repo/schema.ex:56: Ecto.Repo.Schema.do_insert_all/6
    (explorer) lib/explorer/repo.ex:45: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain/import.ex:285: Explorer.Chain.Import.insert_changes_list/3
    (ecto) lib/ecto/multi.ex:580: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
Function: &Indexer.BufferedTask.log_run/1
    Args: [%{batch: [{<<174, 200, 188, 175, 92, 145, 132, 9, 21, 144, 82, 91, 139, 46, 75, 171, 249, 52, 216, 239, 137, 30, 47, 219, 12, 164, 83, 62, 49, 172, 148, 153>>, 0}, {<<164, 240, 163, 103, 115, 65, 199, 231, 189, 95, 76, 238, 209, 176, 6, 135, 34, 254, 23, 192, 46, 24, 105, 181, 206, 210, 14, 22, 240, 162, 225, 48>>, 0}, {<<140, 217, 92, 229, 19, 23, 213, 243, 26, 43, 48, 23, 127, 20, 75, 89, 224, 107, 94, 223, 170, 141, 216, 60, 143, 21, 230, 168, 184, 131, 251, 153>>, 0}, {<<195, 11, 121, 226, 9, 244, 130, 28, 26, 131, 10, 165, 185, 125, 179, 166, 61, 96, 47, 4, 140, 242, 21, 2, 248, 132, 206, 160, 219, 29, 225, 118>>, 0}, {<<138, 21, 8, 24, 252, 223, 17, 200, 168, 183, 65, 210, 93, 79, 174, 85, 93, 0, 144, 43, 172, 6, 104, 150, 20, 49, 62, 43, 177, 85, 252, 253>>, 0}, {<<185, 210, 237, 9, 151, 217, 177, 164, 67, 254, 6, 102, 20, 222, 248, 52, 5, 12, 10, 181, 69, 222, 142, 129, 139, 24, 132, 8, 24, 219, 140, 182>>, 0}, {<<58, 168, 232, 117, 108, 216, 173, 158, 70, 133, 114, 8, 19, 143, 85, 98, 75, 131, 29, 165, 78, 5, 51, 228, 191, 165, 89, 57, 193, 163, 175, 176>>, 0}, {<<229, 65, 19, 212, 219, 65, 234, 44, 59, 210, 20, 254, 81, 28, 86, 173, 46, 169, 116, 71, 242, 116, 10, 84, 52, 25, 102, 90, 12, 121, 113, 207>>, 0}, {<<91, 80, 151, 42, 80, 237, 188, 47, 77, 36, 227, 136, 197, 206, 12, 45, 253, 192, 219, 0, 245, 31, 110, 191, 141, 81, 143, 58, 91, 133, 85, 139>>, 0}, {<<176, 220, 57, 243, 85, 254, 171, 245, 62, 128, 235, 132, 19, 165, 141, 85, 126, 236, 251, 141, 122, 148, 64, 204, 102, 218, 97, 234, 58, 160, 127, 213>>, 0}], callback_module: Indexer.Fetcher.UncleBlock, callback_module_state: %Indexer.Block.Fetcher{broadcast: :uncle, callback_module: Indexer.Fetcher.UncleBlock, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://10.136.20.6:8545", method_to_url: [eth_getBalance: "http://10.136.20.6:8545", trace_block: "http://10.136.20.6:8545", trace_replayTransaction: "http://10.136.20.6:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, metadata: [fetcher: :block_uncle]}]
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 21 [erts-10.3.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```
* Operating System: Alpine Linux v3.9

* Blockscout version: 1.3.13

### Steps to reproduce
This error appeared during realtime fetch (all previous blocks were already synced). After Blockscout restart error disappeared.

**Comment by pasqu4le** [comment]
Hey @APshenkin apparently the Block Uncles Fetcher can sometimes try to push the same value to the database twice at the same time.

I'm not exactly clear on what the root cause is at the moment, but I prepared a PR that solves the problem anyway.
