### ISSUE TITLE
Blockscout reports too many error logs

### ISSUE THREAD

**Issue by rjl493456442** [poanetwork/blockscout#2308]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:

### Steps to reproduce

Attach blockscout to a goerli node.

### Actual behaviour

Lots of error logs

```
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://localhost:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 10, memory_monitor: Indexer.Memory.Monitor}]
2019-07-08T05:38:46.038 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({{:badmatch, {:error, :econnrefused}}, [{Indexer.Block.Catchup.Fetcher, :task, 1, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 75]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}). Restarting
2019-07-08T05:38:46.038 fetcher=block_catchup [error] Task #PID<0.16351.1> started from Indexer.Block.Catchup.BoundIntervalSupervisor terminating
** (MatchError) no match of right hand side value: {:error, :econnrefused}
    (indexer) lib/indexer/block/catchup/fetcher.ex:75: Indexer.Block.Catchup.Fetcher.task/1
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by vbaranov** [comment]
@rjl493456442 what is your setup? Seems, there is no fully synchronized archive node on `http://localhost:8545`

**Comment by rjl493456442** [comment]
Yes. The node is still syncing.

Btw I ran the blockscout in the docker, and there are lots of logs like

```
Function: &:erlang.apply/2
    Args: [#Function<9.87331822/1 in Ecto.Repo.Preloader.maybe_pmap/4>, [{{:assoc, %Ecto.Association.BelongsTo{cardinality: :one, defaults: [], field: :miner, on_cast: nil, on_repl
ace: :raise, owner: Explorer.Chain.Block, owner_key: :miner_hash, queryable: Explorer.Chain.Address, related: Explorer.Chain.Address, related_key: :hash, relationship: :parent, uni
que: true, where: []}, {0, :hash}}, nil, nil, [names: {nil, nil, []}]}]]
2019-07-08T08:55:15.299 [error] Task #PID<0.28301.5> started from #PID<0.27863.5> terminating
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 128ms. You can configure how long requests wait in the queue using :queue_target
 and :queue_interval. See DBConnection.start_link/2 for more information
    (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:553: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
    (ecto) lib/ecto/repo/preloader.ex:188: Ecto.Repo.Preloader.fetch_query/8
    (ecto) lib/ecto/repo/preloader.ex:119: Ecto.Repo.Preloader.preload_assoc/10
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
Function: &:erlang.apply/2
```

The container can restart some times. Not sure the error can cause panic.

Is there any env I can config the `request frequency` to reduce the db connection?

**Comment by karalabe** [comment]
Our use case is to start a docker container with a Geth node from scratch, doing an archive sync on Goerli, and a Blockscout node indexing Geth. For some reason, blockscout seems to spit out a ton of errors (non stop, tens per second), and after a while (1 minute) tears itself down.

**Comment by karalabe** [comment]
I've created a repro for you via docker at https://github.com/karalabe/blockscout-goerli-repro.

```
$ cd /tmp && git clone https://github.com/karalabe/blockscout-goerli-repro
$ cd /tmp/blockscout-goerli-repro && docker build --tag=repro --no-cache --pull .
$ docker run -p 4000:4000 goerli
```

And here's a sample crash: https://gist.github.com/karalabe/db9fb1ac76e896e337f360de4207175b

**Comment by karalabe** [comment]
Btw, I can confirm that if I wait until Geth is in sync and only afterwards start up blockscout, then everything seems to work ok. Still, this is a bit of a problem, because it indicates that if Geth restarts and reimports a batch of blocks, that might murder blockscout for whatever reason. Imho a fast moving chain should not cause bs to die.

**Comment by vbaranov** [comment]
Thank you for the details. Let us reproduce the mentioned behaviour.

**Comment by ayrat555** [comment]
I could reproduce your issue. It's caused by a large amount of new blocks transferred through a web socket connection from the node. Can you please try this pr (https://github.com/poanetwork/blockscout/pull/2358) ?

**Comment by rjl493456442** [comment]
@ayrat555 Hi, I try the PR you offered, but unfortunately blockscout still has lots of error and a crash happens immediately.

Check the crash log here https://gist.github.com/rjl493456442/32d7b1597228f0c0f3c932679cddcec7

**Comment by ayrat555** [comment]
Btw I saw you're configuring postgres in the elixir docker. I think it may be error-prone. I tested my PR on a docker-compose with posgres started  in a separate docker. I used official postgres docker.

**Comment by ayrat555** [comment]
please take a look https://github.com/ayrat555/blockscout/commit/c96d6357c662477e13c963ee8bdce84a0bc89551.

Also, I think `geth` also can be started from a separate docker

**Comment by rjl493456442** [comment]
@ayrat555 Hi, I try the compose version. Here is a compose demo https://github.com/rjl493456442/blockscout_explorer_docker/tree/blockscout-compose

Unfortunately the same error occurs which can eventually lead to a crash.

The `rjl493456442/blockscout` image is built upon https://github.com/poanetwork/blockscout/pull/2358

**Comment by ayrat555** [comment]
I'll take a look at this now. Thanks

**Comment by ayrat555** [comment]
@rjl493456442 
1. You have an error in your `docker-compose` file - `DockerfilePostgres` -> `DockerfileExplorer` 
2. I ran blockscout for a while with your configuration. Everything's ok so it may depend on a machine. You can try increasing WebSocket timeout from 60s to 120s - https://github.com/poanetwork/blockscout/pull/2358/files#diff-2b79eddc1d44c927db36ab82f726d0ddR39

**Comment by rjl493456442** [comment]
@ayrat555 Thanks for pointing out the error in compose file.

What does the `WebSocket timeout` mean? I configure it to 120s

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 0088f49..b33966b 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -22,12 +22,13 @@ services:
   explorer:
     build:
       context: .
-      dockerfile: DockerfilePostgres
+      dockerfile: DockerfileExplorer
     restart: "always"
     environment:
       - DATABASE_URL=ecto://postgres:@postgres/explorer?ssl=false
       - ETHEREUM_JSONRPC_HTTP_URL=http://geth:8545
       - ETHEREUM_JSONRPC_WS_URL=ws://geth:8546
+      - WS_BLOCK_PERIOD=120000
     ports:
       - "4000:4000"
     depends_on:
```

But it still has db connnection errors. 

```
explorer_1  | Retrying.
explorer_1  | 2019-07-18T02:16:17.877 [error] Task #PID<0.18667.0> started from #PID<0.15647.0> terminating
explorer_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 104ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
explorer_1  |     (ecto_sql) lib/ecto/adapters/sql.ex:620: Ecto.Adapters.SQL.raise_sql_call_error/1
explorer_1  |     (ecto_sql) lib/ecto/adapters/sql.ex:553: Ecto.Adapters.SQL.execute/5
explorer_1  |     (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
explorer_1  |     (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
explorer_1  |     (ecto) lib/ecto/repo/preloader.ex:188: Ecto.Repo.Preloader.fetch_query/8
explorer_1  |     (ecto) lib/ecto/repo/preloader.ex:119: Ecto.Repo.Preloader.preload_assoc/10
explorer_1  |     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
explorer_1  |     (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
explorer_1  | Function: &:erlang.apply/2
explorer_1  |     Args: [#Function<9.87331822/1 in Ecto.Repo.Preloader.maybe_pmap/4>, [{{:assoc, %Ecto.Association.BelongsTo{cardinality: :one, defaults: [], field: :block, on_cast: nil, on_replace: :raise, owner: Explorer.Chain.Transaction, owner_key: :block_hash, queryable: Explorer.Chain.Block, related: Explorer.Chain.Block, related_key: :hash, relationship: :parent, unique: true, where: []}, {0, :hash}}, nil, nil, []}]]
explorer_1  | 2019-07-18T02:16:17.879 [error] Task #PID<0.18669.0> started from #PID<0.15647.0> terminating
```

But the interval becomes a bit longer(seems 120s?)

**Comment by rjl493456442** [comment]
```
$ docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                 NAMES
0bec8918b001        blockscout_explorer_docker_explorer   "/bin/sh -c ./start_…"   28 minutes ago      Up 9 minutes        0.0.0.0:4000->4000/tcp                blockscout_explorer_docker_explorer_1
95e67935772b        ethereum/client-go:latest             "geth --goerli --syn…"   16 hours ago        Up 28 minutes       8545-8546/tcp, 30303/tcp, 30303/udp   blockscout_explorer_docker_geth_1
8a503bf5fdb9        postgres:10.9-alpine                  "docker-entrypoint.s…"   16 hours ago        Up 28 minutes       5432/tcp                              blockscout_explorer_docker_postgres_1
```

The blockscout container can still crash. 

Can we somehow limit the request rate to db? Probably it's the root cause of the issue.

**Comment by ayrat555** [comment]
@rjl493456442 
1. Initially, docker was crashing because there were too many blocks sent from geth webscoket and blockscout couldn't process them all.
WS_BLOCK_PERIOD=120000 means that blockscout will process one block in 120 s
2. Please set  `queue_target` to `5_000`. Db connections are dropped after 100ms by default.
```
config :explorer, Explorer.Repo,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: String.equivalent?(System.get_env("ECTO_USE_SSL") || "true", "true"),
  prepare: :unnamed,
  timeout: :timer.seconds(60),
  queue_target: 5000
```

**Comment by ayrat555** [comment]
> Does it mean: If blockscout can't process new block in 120s, then the system will crash?

No, it just limits the number of blocks that we'll process from websocket connection

**Comment by ayrat555** [comment]
We don't have a `requestQueue`. Does your docker keep crashing? or you're only seeing errros in logs?

**Comment by rjl493456442** [comment]
Yes. Since the explorer container restarted

**Comment by ayrat555** [comment]
do you run docker locally? what are the specs of your machine?

**Comment by rjl493456442** [comment]
Yes, I ran docker locally before. Yesterday I deployed the container in one of my server, now no crash happens for the last 14hours but still lots of error logs.

**Comment by hadv** [comment]
I have the same issue with latest release version `BlockScout v3.3.2-beta`, the very old version of blockscout worked without the issue.

**Comment by hadv** [comment]
@rjl493456442 Do you think that the error logs due to **debug_traceTransaction** call was timeout on the etheruem node?

```
WARN [10-13|03:41:06.198] Served debug_traceTransaction            conn=159.89.200:xxx:42127 reqid=29 t=5.243270583s  err="execution timeout"
WARN [10-13|03:41:07.312] Served debug_traceTransaction            conn=159.89.200.xxx:52711 reqid=49 t=5.248376171s  err="execution timeout"
```

**Comment by rjl493456442** [comment]
@hadv Yes, the call is timeout. Perhaps you can increase the timeout by the traceConfig parameter. Not sure how to do it in the blockscout.

Btw I will close this issue here.

**Comment by royki** [comment]
I am getting similar error in new blockscout version - `v3.5.1-beta`

```shell
blockscout_1  | 
blockscout_1  |   1. Tracking down slow queries and making sure they are running fast enough
blockscout_1  |   2. Increasing the pool_size (albeit it increases resource consumption)
blockscout_1  |   3. Allowing requests to wait longer by increasing :queue_target and :queue_interval
blockscout_1  | 
blockscout_1  | See DBConnection.start_link/2 for more information
blockscout_1  | 
blockscout_1  |     (db_connection 2.3.1) lib/db_connection.ex:852: DBConnection.transaction/3
blockscout_1  |     (ecto 3.5.5) lib/ecto/repo/transaction.ex:20: Ecto.Repo.Transaction.transaction/4
blockscout_1  |     (stdlib 3.13.2) timer.erl:197: :timer.tc/3
blockscout_1  |     (explorer 0.0.1) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
blockscout_1  |     (explorer 0.0.1) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
blockscout_1  |     (explorer 0.0.1) lib/explorer/chain/import.ex:330: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
blockscout_1  |     (elixir 1.11.0) lib/enum.ex:3764: Enumerable.List.reduce/3
blockscout_1  |     (elixir 1.11.0) lib/enum.ex:2231: Enum.reduce_while/3
blockscout_1  | Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
blockscout_1  |     Args: [385196, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://parity:8545", method_to_url: [eth_getBalance: "http://parity:8545", trace_block: "http://parity:8545", trace_replayTransaction: "http://parity:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, false]
blockscout_1  | 2021-01-22T17:26:59.370 [error] Task #PID<0.4505.0> started from Indexer.Block.Realtime.Fetcher terminating
blockscout_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 352ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
blockscout_1  | 
blockscout_1  |   1. Tracking down slow queries and making sure they are running fast enough
blockscout_1  |   2. Increasing the pool_size (albeit it increases resource consumption)
blockscout_1  |   3. Allowing requests to wait longer by increasing :queue_target and :queue_interval
```

@rjl493456442 How did you resolve this? Can you please tell me.
