### ISSUE TITLE
Credo 1.0.0 incompatible with Elixir 1.9

### ISSUE THREAD

**Issue by SlightlyCyborg** [poanetwork/blockscout#2426]
I am having trouble running credo 1.0.0 (what blockscout currently has in its deps) with Elixir 1.9.0

[When searching for a solution I found that credo needs to be 1.1.0 to work with Elixir 1.9.0](https://github.com/rrrene/credo/issues/667)

I am getting the following error when running credo:

```
[alex@ScratchTop blockscout]$ mix credo
Checking 376 source files (this might take a while) ...
Error while running Elixir.Credo.Check.Design.DuplicatedCode

04:51:46.497 [error] Task #PID<0.491.0> started from #PID<0.90.0> terminating
** (FunctionClauseError) no function clause matching in Inspect.Algebra.to_doc/2
    (elixir) lib/inspect/algebra.ex:276: Inspect.Algebra.to_doc({:defmodule, [], [{:__aliases__, [], [:BlockScoutWeb, :AdminRouter]}, [do: {:__block__, [], [{:@, [], [{:moduledoc, [], ["Router for admin pages.\n"]}]}, {:use, [], [{:__aliases__, [], [:BlockScoutWeb]}, :router]}, {:alias, [], [{:__aliases__, [], [:BlockScoutWeb, :Plug, :FetchUserFromSession]}]}, {:alias, [], [{{:., [line: 9, column: 33], [{:__aliases__, [line: 9, column: 9], [:BlockScoutWeb, :Plug, :Admin]}, :{}]}, [], [{:__aliases__, [], [:CheckOwnerRegistered]}, {:__aliases__, [], [:RequireAdminRole]}]}]}, {:pipeline, [], [:browser, [do: {:__block__, [], [{:plug, [], [:accepts, ["html"]]}, {:plug, [], [:fetch_session]}, {:plug, [], [:fetch_flash]}, {:plug, [], [:protect_from_forgery]}, {:plug, [], [{:__aliases__, [], [:BlockScoutWeb, :CSPHeader]}]}]}]]}, {:pipeline, [], [:check_configured, [do: {:plug, [], [{:__aliases__, [], [:CheckOwnerRegistered]}]}]]}, {:pipeline, [], [:ensure_admin, [do: {:__block__, [], [{:plug, [], [{:__aliases__, [], [:FetchUserFromSession]}]}, {:plug, [], [{:__aliases__, [], [:RequireAdminRole]}]}]}]]}, {:scope, [], ["/setup", {:__aliases__, [], [:BlockScoutWeb, :Admin]}, [do: {:__block__, [], [{:pipe_through, [], [[:browser]]}, {:get, [], ["/", {:__aliases__, [], [:SetupController]}, :configure]}, {:post, [], ["/", {:__aliases__, [], [:SetupController]}, :configure_admin]}]}]]}, {:scope, [], ["/login", {:__aliases__, [], [:BlockScoutWeb, :Admin]}, [do: {:__block__, [], [{:pipe_through, [], [[:browser, :check_configured]]}, {:get, [], ["/", {:__aliases__, [], [:SessionController]}, :new]}, {:post, [], ["/", {:__aliases__, [], [:SessionController]}, :create]}]}]]}, {:scope, [], ["/", {:__aliases__, [], [:BlockScoutWeb, :Admin]}, [do: {:__block__, [], [{:pipe_through, [], [[:browser, :check_configured, :ensure_admin]]}, {:get, [], ["/", {:__aliases__, [], [:DashboardController]}, :index]}, {:scope, [], ["/tasks", [do: {:get, [], ["/create_contract_methods", {:__aliases__, [], [:TaskController]}, :create_contract_methods, [as: :create_contract_methods]]}]]}]}]]}]}]]}, %{__struct__: Inspect.Opts, base: :decimal, binaries: :infer, char_lists: :infer, charlists: :infer, limit: 50, pretty: false, printable_limit: 4096, safe: true, structs: true, syntax_colors: [], width: 80})
    lib/credo/check/design/duplicated_code.ex:184: Credo.Check.Design.DuplicatedCode.to_hash/1
    lib/credo/check/design/duplicated_code.ex:170: Credo.Check.Design.DuplicatedCode.collect_hashes/4
    (elixir) lib/macro.ex:251: Macro.traverse/4
    lib/credo/code.ex:42: Credo.Code.prewalk/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/credo/check/design/duplicated_code.ex:80: Credo.Check.Design.DuplicatedCode.duplicate_nodes/2
    lib/credo/check/design/duplicated_code.ex:47: Credo.Check.Design.DuplicatedCode.run/3
Function: #Function<10.50379115/0 in Credo.Check.Runner.run/2>
    Args: []
** (EXIT from #PID<0.90.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Inspect.Algebra.to_doc/2
        (elixir) lib/inspect/algebra.ex:276: Inspect.Algebra.to_doc({:defmodule, [], [{:__aliases__, [], [:BlockScoutWeb, :AdminRouter]}, [do: {:__block__, [], [{:@, [], [{:moduledoc, [], ["Router for admin pages.\n"]}]}, {:use, [], [{:__aliases__, [], [:BlockScoutWeb]}, :router]}, {:alias, [], [{:__aliases__, [], [:BlockScoutWeb, :Plug, :FetchUserFromSession]}]}, {:alias, [], [{{:., [line: 9, column: 33], [{:__aliases__, [line: 9, column: 9], [:BlockScoutWeb, :Plug, :Admin]}, :{}]}, [], [{:__aliases__, [], [:CheckOwnerRegistered]}, {:__aliases__, [], [:RequireAdminRole]}]}]}, {:pipeline, [], [:browser, [do: {:__block__, [], [{:plug, [], [:accepts, ["html"]]}, {:plug, [], [:fetch_session]}, {:plug, [], [:fetch_flash]}, {:plug, [], [:protect_from_forgery]}, {:plug, [], [{:__aliases__, [], [:BlockScoutWeb, :CSPHeader]}]}]}]]}, {:pipeline, [], [:check_configured, [do: {:plug, [], [{:__aliases__, [], [:CheckOwnerRegistered]}]}]]}, {:pipeline, [], [:ensure_admin, [do: {:__block__, [], [{:plug, [], [{:__aliases__, [], [:FetchUserFromSession]}]}, {:plug, [], [{:__aliases__, [], [:RequireAdminRole]}]}]}]]}, {:scope, [], ["/setup", {:__aliases__, [], [:BlockScoutWeb, :Admin]}, [do: {:__block__, [], [{:pipe_through, [], [[:browser]]}, {:get, [], ["/", {:__aliases__, [], [:SetupController]}, :configure]}, {:post, [], ["/", {:__aliases__, [], [:SetupController]}, :configure_admin]}]}]]}, {:scope, [], ["/login", {:__aliases__, [], [:BlockScoutWeb, :Admin]}, [do: {:__block__, [], [{:pipe_through, [], [[:browser, :check_configured]]}, {:get, [], ["/", {:__aliases__, [], [:SessionController]}, :new]}, {:post, [], ["/", {:__aliases__, [], [:SessionController]}, :create]}]}]]}, {:scope, [], ["/", {:__aliases__, [], [:BlockScoutWeb, :Admin]}, [do: {:__block__, [], [{:pipe_through, [], [[:browser, :check_configured, :ensure_admin]]}, {:get, [], ["/", {:__aliases__, [], [:DashboardController]}, :index]}, {:scope, [], ["/tasks", [do: {:get, [], ["/create_contract_methods", {:__aliases__, [], [:TaskController]}, :create_contract_methods, [as: :create_contract_methods]]}]]}]}]]}]}]]}, %{__struct__: Inspect.Opts, base: :decimal, binaries: :infer, char_lists: :infer, charlists: :infer, limit: 50, pretty: false, printable_limit: 4096, safe: true, structs: true, syntax_colors: [], width: 80})
        lib/credo/check/design/duplicated_code.ex:184: Credo.Check.Design.DuplicatedCode.to_hash/1
        lib/credo/check/design/duplicated_code.ex:170: Credo.Check.Design.DuplicatedCode.collect_hashes/4
        (elixir) lib/macro.ex:251: Macro.traverse/4
        lib/credo/code.ex:42: Credo.Code.prewalk/3
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/credo/check/design/duplicated_code.ex:80: Credo.Check.Design.DuplicatedCode.duplicate_nodes/2
        lib/credo/check/design/duplicated_code.ex:47: Credo.Check.Design.DuplicatedCode.run/3

```

**Comment by ayrat555** [comment]
can you please try https://github.com/poanetwork/blockscout/pull/2432?
