### ISSUE TITLE
Contract verification stucked on private blockchain

### ISSUE THREAD

**Issue by zulhfreelancer** [poanetwork/blockscout#2580]
### Description

I have a [contract](https://blockscout.com/eth/goerli/address/0x05a876a39e677f2c81f957bde6ed2b5a49a4d2b8/contracts) on Goerli and it's successfully verified on Blockscout.

When I deployed the same contract using the same compiler, deployment workflow and tooling to my PoA private blockchain (running on Parity), the contract verification failed on my private blockchain's Blockscout. The submit button just showed 'Loading' and stucked there just like that.

Note 1: my private blockchain Blockscout is fully functioning except that verification part.

Note 2: the Blockscout server has Node installed (v10.16.2).

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe] Elixir 1.9.1 (compiled with Erlang/OTP 21)
* Operating System: Ubuntu 16.04.6 LTS
* Blockscout Version/branch: 27dff9b111d6b199c01a0e25eb093fb4e72a3e0c

### Steps to reproduce

1. Take the source code from the [Goerli contract](https://blockscout.com/eth/goerli/address/0x05a876a39e677f2c81f957bde6ed2b5a49a4d2b8/contracts)
2. Deploy it using Remix or Truffle to a PoA private network (preferably running on Parity)
3. Go to the private network's Blockscout contract page and verify the contract with the following details:

- Contract Name: FixedSupplyToken
- Compiler: v0.5.0+commit.1d4f565a
- EVM Version: default
- Optimization: No
- Optimization runs: 200
- Enter the Solidity Contract Code: copy and paste from Goerli
- ABI-encoded Constructor Arguments: leave empty
- Add Contract Libraries: leave untouched

### Expected behaviour

Able to verify the contract, just like in Goerli Blockscout explorer

### Actual behaviour

After submitting the form, it's stucked. The "Verify & publish" button turns to "Loading" and nothing happened even I've waited for long time.

### Blockscout logs

```
$ sudo journalctl -u blockscout --no-pager | tail -n 50
Aug 15 18:09:34 pb-poa-blockscout mix[5670]:   Parameters: %{}
Aug 15 18:09:35 pb-poa-blockscout mix[5670]: 2019-08-15T18:09:35.189 application=plug request_id=FbsrABdzb1ASQQAABDJh [info] Sent 200 in 354ms
Aug 15 18:09:36 pb-poa-blockscout mix[5670]: 2019-08-15T18:09:36.263 application=phoenix [info] CONNECTED TO BlockScoutWeb.UserSocket in 180µs
Aug 15 18:09:36 pb-poa-blockscout mix[5670]:   Transport: :websocket
Aug 15 18:09:36 pb-poa-blockscout mix[5670]:   Serializer: Phoenix.Socket.V2.JSONSerializer
Aug 15 18:09:36 pb-poa-blockscout mix[5670]:   Connect Info: %{}
Aug 15 18:09:36 pb-poa-blockscout mix[5670]:   Parameters: %{"locale" => "en", "vsn" => "2.0.0"}
Aug 15 18:09:36 pb-poa-blockscout mix[5670]: 2019-08-15T18:09:36.306 application=phoenix [info] JOINED exchange_rate:new_rate in 84µs
Aug 15 18:09:36 pb-poa-blockscout mix[5670]:   Parameters: %{}
Aug 15 18:09:36 pb-poa-blockscout mix[5670]: 2019-08-15T18:09:36.307 application=phoenix [info] JOINED addresses:0x0839ecd4291f73707215113df4fe7ec838d5e70f in 60µs
Aug 15 18:09:36 pb-poa-blockscout mix[5670]:   Parameters: %{}
Aug 15 18:09:36 pb-poa-blockscout mix[5670]: 2019-08-15T18:09:36.307 application=phoenix [info] JOINED blocks:indexing in 75µs
Aug 15 18:09:36 pb-poa-blockscout mix[5670]:   Parameters: %{}
Aug 15 18:09:49 pb-poa-blockscout mix[5670]: 2019-08-15T18:09:49.157 application=indexer fetcher=block_catchup first_block_number=7674 last_block_number=0 missing_block_count=0 shrunk=false [info] Index already caught up.
Aug 15 18:09:49 pb-poa-blockscout mix[5670]: 2019-08-15T18:09:49.157 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
Aug 15 18:10:14 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:14.197 application=indexer fetcher=block_catchup first_block_number=7679 last_block_number=0 missing_block_count=0 shrunk=false [info] Index already caught up.
Aug 15 18:10:14 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:14.198 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:19.220 application=plug request_id=FbsrCm0MDu1448EABDfx [info] POST /verify_smart_contract/contract_verifications
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:19.223 application=que [info] [Que] Queued new Job for Explorer.SmartContract.PublisherWorker
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:19.223 application=que [info] [Que] Starting Job # 5 with Explorer.SmartContract.PublisherWorker
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:19.223 application=plug request_id=FbsrCm0MDu1448EABDfx [info] Sent 204 in 3ms
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:19.226 [error] Task #PID<0.11142.1> started from #PID<0.2377.0> terminating
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: ** (stop) :enoent
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:     (elixir) lib/system.ex:791: System.cmd("node", ["/home/ubuntu/blockscout/_build/dev/lib/explorer/priv/compile_solc.js", "/home/ubuntu/blockscout/tmpbriefly-1565/briefly-892619-224360-2", "v0.5.0+commit.1d4f565a", "0", "200", "New.sol", "{}", "default", "/home/ubuntu/blockscout/_build/dev/lib/explorer/priv/solc_compilers/v0.5.0+commit.1d4f565a.js"], [])
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:     (explorer) lib/explorer/smart_contract/solidity/code_compiler.ex:90: Explorer.SmartContract.Solidity.CodeCompiler.run/1
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:     (explorer) lib/explorer/smart_contract/verifier.ex:46: Explorer.SmartContract.Verifier.verify/2
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:     (explorer) lib/explorer/smart_contract/publisher.ex:29: Explorer.SmartContract.Publisher.publish/3
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:     (explorer) lib/explorer/smart_contract/publisher_worker.ex:13: Explorer.SmartContract.PublisherWorker.perform/1
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:     (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: Function: #Function<3.104694414/0 in Que.Job.perform/1>
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:     Args: []
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:19.226 application=que [info] [Que] Failed Job # 5 with Explorer.SmartContract.PublisherWorker
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:19.299 application=phoenix [info] CONNECTED TO BlockScoutWeb.UserSocket in 244µs
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:   Transport: :websocket
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:   Serializer: Phoenix.Socket.V2.JSONSerializer
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:   Connect Info: %{}
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:   Parameters: %{"locale" => "en", "vsn" => "2.0.0"}
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:19.313 application=phoenix [info] JOINED exchange_rate:new_rate in 96µs
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:   Parameters: %{}
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:19.314 application=phoenix [info] JOINED addresses:0x0839ecd4291f73707215113df4fe7ec838d5e70f in 65µs
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:   Parameters: %{}
Aug 15 18:10:19 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:19.314 application=phoenix [info] JOINED blocks:indexing in 52µs
Aug 15 18:10:19 pb-poa-blockscout mix[5670]:   Parameters: %{}
Aug 15 18:10:39 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:39.210 application=indexer fetcher=block_catchup first_block_number=7684 last_block_number=0 missing_block_count=0 shrunk=false [info] Index already caught up.
Aug 15 18:10:39 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:39.210 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
Aug 15 18:10:57 pb-poa-blockscout mix[5670]: 2019-08-15T18:10:57.833 application=explorer [warn] Failed to fetch genesis data. Chain spec path is not set.
Aug 15 18:11:04 pb-poa-blockscout mix[5670]: 2019-08-15T18:11:04.246 application=indexer fetcher=block_catchup first_block_number=7689 last_block_number=0 missing_block_count=0 shrunk=false [info] Index already caught up.
Aug 15 18:11:04 pb-poa-blockscout mix[5670]: 2019-08-15T18:11:04.246 application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 25000ms.
```

### Blockscout environment variables

```
NETWORK=MyNetwork
SUBNETWORK=Core Network
NETWORK_ICON=_network_icon.html
LOGO=/images/blockscout_logo.svg
ETHEREUM_JSONRPC_VARIANT=parity
ETHEREUM_JSONRPC_HTTP_URL=http://xxx.xx.xx.xxx:8545
ETHEREUM_JSONRPC_TRACE_URL=http://xxx.xx.xx.xxx:8545
ETHEREUM_JSONRPC_WS_URL=ws://xxx.xx.xx.xxx:8546
SECRET_KEY_BASE=redacted
PORT=4000
COIN=ETH
BLOCKSCOUT_VERSION=2.0.4 (27dff9b)
SUPPORTED_CHAINS=[]
LANG=en_US.UTF-8
```

**Comment by zulhfreelancer** [comment]
**Update 16 Aug 2019**

I tried the following but **none worked**:

1. Install `solc` by using the following commands:

```
sudo add-apt-repository ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install solc -y
```

2. Install `solc` using npm (`npm install solc -g`)

3. Check and compare the contract byte code from my private blockchain's Blockscout vs the bytecode produced by Truffle. They are identical.

**Comment by zulhfreelancer** [comment]
Okay, I figured it out. This problem happened because I'm using systemd and NVM on my VPS. 

NVM only works in interactive shell. When I start Blockscout using systemd, node executable doesn't get load it. Since Blockscout is actually node in the background to verify contracts, it will fail silently in the background if node is not found.

So, I add it manually:

```
$ which node
/home/mybox/.nvm/versions/node/v10.16.2/bin/node

$ sudo cat /etc/environment | head -n 1
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/mybox/.nvm/versions/node/v10.16.2/bin"

$ sudo systemctl restart blockscout
```

I'm going to leave this issue open — just in case someone wants to work on something when Blockscout couldn't find node executable.
