### ISSUE TITLE
ERROR: role "postgres" does not exist

### ISSUE THREAD

**Issue by hadv** [poanetwork/blockscout#2773]
*Describe your issue here.*

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): bitwalker/alpine-elixir-phoenix:1.9.0
* Operating System: MacOS Catalina
* Blockscout Version/branch: 2.0.4-beta

### Steps to reproduce

Go to docker folder and run `make start`

### Expected behaviour

Blockscout will start and can be accessed at `localhost:4000`

### Actual behaviour

```
2019-10-11T14:41:19.110 application=db_connection [error] Postgrex.Protocol (#PID<0.494.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:19.110 application=db_connection [error] Postgrex.Protocol (#PID<0.491.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:19.110 application=db_connection [error] Postgrex.Protocol (#PID<0.493.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:19.110 application=db_connection [error] Postgrex.Protocol (#PID<0.487.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:19.110 application=db_connection [error] Postgrex.Protocol (#PID<0.495.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:19.110 application=db_connection [error] Postgrex.Protocol (#PID<0.488.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:19.110 application=db_connection [error] Postgrex.Protocol (#PID<0.492.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:19.110 application=db_connection [error] Postgrex.Protocol (#PID<0.490.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:19.110 application=db_connection [error] Postgrex.Protocol (#PID<0.486.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:19.115 application=db_connection [error] Postgrex.Protocol (#PID<0.489.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:20.075 application=tzdata [info] tzdata release in place is from a file last modified Tue, 26 Mar 2019 05:40:14 GMT. Release file on server was last modified Wed, 11 Sep 2019 19:35:17 GMT.
2019-10-11T14:41:20.164 application=db_connection [error] Postgrex.Protocol (#PID<0.486.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:20.294 application=db_connection [error] Postgrex.Protocol (#PID<0.488.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:20.322 application=db_connection [error] Postgrex.Protocol (#PID<0.493.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:20.494 application=db_connection [error] Postgrex.Protocol (#PID<0.490.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:20.891 application=db_connection [error] Postgrex.Protocol (#PID<0.491.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:21.115 application=db_connection [error] Postgrex.Protocol (#PID<0.492.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:21.222 application=db_connection [error] Postgrex.Protocol (#PID<0.495.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:21.235 application=db_connection [error] Postgrex.Protocol (#PID<0.487.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:21.618 application=db_connection [error] Postgrex.Protocol (#PID<0.493.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:21.624 application=db_connection [error] Postgrex.Protocol (#PID<0.489.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:21.670 application=tzdata [info] Tzdata has updated the release from 2019a to 2019c
2019-10-11T14:41:21.718 application=db_connection [error] Postgrex.Protocol (#PID<0.488.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:22.044 application=db_connection [error] Postgrex.Protocol (#PID<0.494.0>) failed to connect: ** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
2019-10-11T14:41:22.076 [info] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Counters.AverageBlockTime
    ** (EXIT) an exception was raised:
        ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2941ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
            (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.execute/5
            (ecto) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4
            (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
            (explorer) lib/explorer/counters/average_block_time.ex:84: Explorer.Counters.AverageBlockTime.refresh_timestamps/0
            (explorer) lib/explorer/counters/average_block_time.ex:46: Explorer.Counters.AverageBlockTime.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Counters.AverageBlockTime
    ** (EXIT) an exception was raised:
        ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2941ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
            (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.execute/5
            (ecto) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4
            (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
            (explorer) lib/explorer/counters/average_block_time.ex:84: Explorer.Counters.AverageBlockTime.refresh_timestamps/0
            (explorer) lib/explorer/counters/average_block_time.ex:46: Explorer.Counters.AverageBlockTime.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
make: *** [start] Error 1
```

**Comment by achempion** [comment]
It looks like you've installed `postgres` with `homebrew` which doesn't create "default" `postgres` user by default (it creates user with the same name as your OS name).

You can fix it by creating postgres user by yourself or specify existing user in database configuration.

```sql
CREATE USER postgres SUPERUSER;
CREATE DATABASE postgres WITH OWNER postgres;
```

**Comment by hadv** [comment]
Due to the postgres docker image conflict with local postgres on host

**Comment by jmudau** [comment]
I solved this by running: /usr/local/opt/postgres/bin/createuser -s postgres

**Comment by Shraddha2603** [comment]
I also find this error please help me for resolving...
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Counters.AverageBlockTime
    ** (EXIT) an exception was raised:
        ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2909ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Tracking down slow queries and making sure they are running fast enough
  2. Increasing the pool_size (albeit it increases resource consumption)
  3. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

            (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
            (ecto 3.5.5) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
            (ecto 3.5.5) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
            (explorer 0.0.1) lib/explorer/counters/average_block_time.ex:83: Explorer.Counters.AverageBlockTime.refresh_timestamps/0
            (explorer 0.0.1) lib/explorer/counters/average_block_time.ex:45: Explorer.Counters.AverageBlockTime.init/1
            (stdlib 3.14.2) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14.2) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
