### ISSUE TITLE
Explorer not syncing

### ISSUE THREAD

**Issue by fallengravity** [poanetwork/blockscout#2856]
Seems to not be pulling blocks from the instance on 127.0.0.1:8545 - if I do ```curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_blockNumber","id":1}' http://127.0.0.1:8545``` it returns the expected number. 

My geth flags are as follows: 

```
./geth --rpc --rpcaddr 127.0.0.1 --rpcport 8545 --rpcapi "debug,net,eth,shh,web3,txpool" --wsapi "eth,net,web3,network,debug,txpool" --ws --wsaddr 127.0.0.1 --wsport 8546 --wsorigins "*" --syncmode=full --gcmode=archive --rpcvhosts="*"
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 
```
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.2 (compiled with Erlang/OTP 20)
```
* Operating System: CentOS 7 
* Blockscout Version/branch: master

### Actual behaviour

Not quite sure what is going on here

```
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1870ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
    (db_connection) lib/db_connection.ex:836: DBConnection.transaction/3
    (ecto) lib/ecto/repo/transaction.ex:15: Ecto.Repo.Transaction.transaction/4
    (stdlib) timer.erl:197: :timer.tc/3
    (explorer) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer) lib/explorer/chain/import.ex:318: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
    (elixir) lib/enum.ex:3325: Enumerable.List.reduce/3
    (elixir) lib/enum.ex:1998: Enum.reduce_while/3
    (explorer) lib/explorer/chain/import.ex:317: Explorer.Chain.Import.import_transactions/2
    (explorer) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer) lib/explorer/chain/import.ex:127: Explorer.Chain.Import.all/1
    (indexer) lib/indexer/block/realtime/fetcher.ex:194: Indexer.Block.Realtime.Fetcher.import/2
    (indexer) lib/indexer/block/fetcher.ex:161: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:265: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:248: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [1362440, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://127.0.0.1:8545", http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 200, receipts_concurrency: 1}, false]
2019-11-13T17:31:22.837 [error] Task #PID<0.2956.3> started from Indexer.Block.Realtime.Fetcher terminating
```

Thanks in advance team!

**Comment by vbaranov** [comment]
@fallengravity I'd recommend restarting application again. If the error will repeat again, try to increase the connection pool size to Blockscout DB (`POOL_SIZE` env var) https://docs.blockscout.com/for-developers/information-and-settings/env-variables. It looks like the current pool size is not enough.

**Comment by fallengravity** [comment]
Cheers, Looks like that did the trick, much appreciated !
