### ISSUE TITLE
Internal server error in reading of smart-contract

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2907]
Blockscout version: `2.1.1`

https://blockscout.com/rsk/mainnet/address/0x7a79ba737dcc9cef615b4453dc0d98efec24b0d1/read_contract

![Screenshot 2019-12-03 at 17 32 16](https://user-images.githubusercontent.com/4341812/70060043-e0711e00-15f2-11ea-967c-d34224899d45.png)

Error in the log:
```
Request: GET /smart_contracts?hash=0x7a79ba737dcc9cef615b4453dc0d98efec24b0d1
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for "no match of right hand side value: nil" of type BitString. This protocol is implemented for the following type(s): Indexer.BoundQueue, Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Timex.Interval, Flow, HashSet, Range, Map, Function, List, Stream, Date.Range, HashDict, GenEvent.Stream, MapSet, File.Stream, IO.Stream
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:141: Enumerable.reduce/3
        (elixir) lib/enum.ex:3023: Enum.map/2
        (block_scout_web) lib/block_scout_web/views/smart_contract_view.ex:15: BlockScoutWeb.SmartContractView.values/2
        (block_scout_web) lib/block_scout_web/templates/smart_contract/_functions.html.eex:54: anonymous fn/3 in BlockScoutWeb.SmartContractView."_functions.html"/1
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
        (block_scout_web) lib/block_scout_web/templates/smart_contract/_functions.html.eex:37: anonymous fn/3 in BlockScoutWeb.SmartContractView."_functions.html"/1
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
```

**Comment by vbaranov** [comment]
Fixed
