### ISSUE TITLE
Correct set up and use of IPC transport?

### ISSUE THREAD

**Issue by ImrieA** [poanetwork/blockscout#2927]
Parity and Blockscout are on the same machine and the .ipc file is at `/mnt/volumes/parity/jsonrpc.ipc`

I try and run blockscout with:
` export ETHEREUM_JSONRPC_VARIANT=parity`
`export ETHEREUM_JSONRPC_JSON_RPC_TRANSPORT=ipc`
`export IPC_PATH=/mnt/volumes/parity/jsonrpc.ipc`
`mix phx.server`

I then get an ocean of errors in the console (multiple errors like this per second). Parity is now running with `ipc-apis=all` . When blockscout is running despite all the errors I can see the Parity console increase in `req/s` when blockscout starts so I think it is connecting okay and not a node issue.

Is IPC set up correctly using above ENV? 
Am i missing something?
`
2019-12-11T21:21:35.417 fetcher=block_reward count=10 [error] Task #PID<0.854.0> started from Indexer.Fetcher.BlockReward terminating
** (stop) exited in: GenServer.call(#PID<0.402.0>, {:request, "[{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB432\"]},{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB43A\"]},{\"id\":2,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB43B\"]},{\"id\":3,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB450\"]},{\"id\":4,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB451\"]},{\"id\":5,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB452\"]},{\"id\":6,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB453\"]},{\"id\":7,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB454\"]},{\"id\":8,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB455\"]},{\"id\":9,\"jsonrpc\":\"2.0\",\"method\":\"trace_block\",\"params\":[\"0x8AB458\"]}]"}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:1009: GenServer.call/3
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/ipc.ex:66: EthereumJSONRPC.IPC.request/2
    (poolboy) /ethUser/blockscout2/blockscout/deps/poolboy/src/poolboy.erl:84: :poolboy.transaction/3
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/parity.ex:24: EthereumJSONRPC.Parity.fetch_beneficiaries/2
    (indexer) lib/indexer/fetcher/block_reward.ex:94: Indexer.Fetcher.BlockReward.run/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
1`

`2019-12-11T21:31:08.166 fetcher=block_catchup [error] Task #PID<0.5705.1> started from Indexer.Block.Catchup.BoundIntervalSupervisor terminating
** (MatchError) no match of right hand side value: {:error, {:invalid_json, :closed}}
    (indexer) lib/indexer/block/catchup/fetcher.ex:349: Indexer.Block.Catchup.Fetcher.latest_block/1
    (indexer) lib/indexer/block/catchup/fetcher.ex:76: Indexer.Block.Catchup.Fetcher.task/1
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.IPC, else: EthereumJSONRPC.IPC, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "localhost:8545", method_to_url: [eth_getBalance: "http://localhost:8545", trace_block: "http://localhost:8545", trace_replayBlockTransactions: "http://localhost:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 10, memory_monitor: Indexer.Memory.Monitor}]
`

`2019-12-11T21:33:30.123 application=indexer fetcher=block_reward count=10 error_count=10 [error] failed to fetch: {:invalid_json, :enotconn}
`
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.9.4
* Operating System: Ubuntu 18
* Blockscout Version/branch:  2.1.1 Beta

### Steps to reproduce

` export ETHEREUM_JSONRPC_VARIANT=parity`
`export ETHEREUM_JSONRPC_JSON_RPC_TRANSPORT=ipc`
`export IPC_PATH=/mnt/volumes/parity/jsonrpc.ipc`
`mix phx.server`

### Expected behaviour

Blockscout should index without error

### Actual behaviour

Blockscout fails to get the JSON from Parity via IPC

**Comment by vbaranov** [comment]
@ImrieA is the same error when using Elixir 1.9.1? Because this version is tested and recommended to use with `2.1.1 Beta` version.

**Comment by vbaranov** [comment]
What is the version of Parity do you use? And did you configure it properly? ref https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache#parity-client

**Comment by ImrieA** [comment]
For the purposes of trying to get IPC to work I am using :
` parity --cache-size 40000 --base-path /mnt/volumes/parity --jsonrpc-interface all --jsonrpc-apis web3,eth,net,parity,pubsub,traces --ws-interface all --fat-db=on --pruning=archive --ws-apis all --ws-origins all --ws-hosts all --ipc-apis all --jsonrpc-server-threads 6 --jsonrpc-max-payload 5000 --mode-timeout 5000 --no-ipc disable --ipc-path /mnt/volumes/parity/jsonrpc.ipc --unsafe-expose `

I am running parity `v2.6.6-beta`

I have not tried yet Elixer 1.9.1

Thanks

**Comment by ImrieA** [comment]
@vbaranov exact same errors when using Elixir 1.9.1
