### ISSUE TITLE
the method eth_getBlockByNumber does not exist/is not available

### ISSUE THREAD

**Issue by qianjin** [poanetwork/blockscout#3164]
*Describe your issue here.*

### Environment

docker3.2.0

### Expected behaviour

WARN [06-28|14:11:53.382|rpc/handler.go:306]               Served eth_getBalance                    conn=127.0.0.1:48635 reqid=340   t=892ns       err="the method eth_getBalance does not exist/is not available"
WARN [06-28|14:11:53.337|rpc/handler.go:306]               Served debug_traceTransaction            conn=127.0.0.1:45743 reqid=0     t="8.948µs"   err="the method debug_traceTransaction does not exist/is not available"
WARN [06-28|14:11:53.374|rpc/handler.go:306]               Served eth_getBlockByNumber              conn=127.0.0.1:45743 reqid=0     t="16.973µs"  err="the method eth_getBlockByNumber does not exist/is not available"

geth node start by cmd :

nohup geth --datadir synode/data --networkid 18099 --http --http.api --ws --debug --port 2005 >> syn.log &

**Comment by qianjin** [comment]
2020-06-28T06:11:49.813 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({{:badmatch, {:error, %{code: -32601, message: "the method eth_getBlockByNumber does not exist/is not available"}}}, [{Indexer.Block.Catchup.Fetcher, :task, 1, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 76]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}). Restarting
2020-06-28T06:11:49.839 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: [%{code: -32601, data: %{block_number: 413, transaction_hash: "0x680655da14a650a51cc422f00e12f99acb9baa4924b8b0e8e08bb4cf68bef6bd", transaction_index: 0}, message: "the method debug_traceTransaction does not exist/is not available"}]
2020-06-28T06:11:49.839 fetcher=block_catchup [error] Task Indexer.Block.Catchup.BoundIntervalSupervisor started from #PID<0.1005.0> terminating
** (MatchError) no match of right hand side value: {:error, %{code: -32601, message: "the method eth_getBlockByNumber does not exist/is not available"}}
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:76: Indexer.Block.Catchup.Fetcher.task/1
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "127.0.0.1:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 10, memory_monitor: Indexer.Memory.Monitor}]
2020-06-28T06:11:49.842 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({{:badmatch, {:error, %{code: -32601, message: "the method eth_getBlockByNumber does not exist/is not available"}}}, [{Indexer.Block.Catchup.Fetcher, :task, 1, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 76]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}). Restarting
2020-06-28T06:11:49.867 fetcher=block_catchup [error] Task Indexer.Block.Catchup.BoundIntervalSupervisor started from #PID<0.1015.0> terminating
** (MatchError) no match of right hand side value: {:error, %{code: -32601, message: "the method eth_getBlockByNumber does not exist/is not available"}}
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:76: Indexer.Block.Catchup.Fetcher.task/1
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Catchup.Fetcher.task/1
    Args: [%Indexer.Block.Catchup.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :catchup, callback_module: Indexer.Block.Catchup.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "127.0.0.1:8545", http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 250, receipts_concurrency: 10}, blocks_batch_size: 10, blocks_concurrency: 10, memory_monitor: Indexer.Memory.Monitor}]
2020-06-28T06:11:49.869 application=indexer fetcher=coin_balance count=500 error_count=500 [error] failed to fetch: 0x0000000000000000000000000000000000000000@㱞: (-32601) the method eth_getBalance does not exist/is not available
0x0000000000000000000000000000000000000000@㼳: (-32601) the method eth_getBalance does not exist/is not available

**Comment by vbaranov** [comment]
@qianjin here https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache you will find Ethereum clients configuration settings in order to run it with Blockscout
> sudo /usr/bin/geth --rpc --rpcaddr 0.0.0.0 --port 30303 --rpcport 8545 --rpcapi debug,net,eth,shh,web3,txpool --wsapi "eth,net,web3,network,debug,txpool" --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --rinkeby --datadir=/rinkeby --syncmode=full --gcmode=archive --rpcvhosts=*
