### ISSUE TITLE
[error] ** (MatchError) no match of right hand side value

### ISSUE THREAD

**Issue by hadv** [poanetwork/blockscout#3345]
below error logs are output repeatedly 

```
2020-10-12T04:27:02.722 application=indexer fetcher=block_catchup first_block_number=9049495 last_block_number=9049486 [error] ** (MatchError) no match of right hand side value: {:error, {:more, {:hparser, :response, 4096, 10, 0, :on_trailers, "\r", {1, 1}, "", [], :undefined, "chunked", "", "application/json", "", :done}}}
    (indexer 0.1.0) lib/indexer/transform/address_coin_balances_daily.ex:67: anonymous fn/3 in Indexer.Transform.AddressCoinBalancesDaily.reducer/2
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (indexer 0.1.0) lib/indexer/transform/address_coin_balances_daily.ex:66: Indexer.Transform.AddressCoinBalancesDaily.reducer/2
    (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
    (indexer 0.1.0) lib/indexer/block/fetcher.ex:165: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer 0.1.0) lib/indexer/block/catchup/fetcher.ex:194: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
```
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): 1.10.3
* Operating System: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-42-generic x86_64)
* Blockscout Version/branch: 3.3.2-beta

**Comment by vbaranov** [comment]
@hadv Please use [3.3.3](https://github.com/poanetwork/blockscout/releases/tag/v3.3.3-beta). It has been fixed there https://github.com/poanetwork/blockscout/commit/d9304c03f8573aebd4286c86f6a461515ef2d578#diff-dff0f3cd421195df6810c9e9508fc5048c1cf32389a1dff5fa95baf0942cd17bR67-R74
