### ISSUE TITLE
(RuntimeError) aborting due to nil port

### ISSUE THREAD

**Issue by unqjohnny** [poanetwork/blockscout#3695]
I followed this guide: https://docs.blockscout.com/for-developers/manual-deployment

but when mix phx.server get below:

```
2021-03-10T14:55:01.021 application=que [info] [Que] Booting Que
2021-03-10T14:55:01.022 application=que [info] [Que] Booting Server Supervisor for Workers
** (Mix) Could not start application block_scout_web: BlockScoutWeb.Application.start(:normal, []) returned an error: shutdown: failed to start child: BlockScoutWeb.Endpoint
    ** (EXIT) an exception was raised:
        ** (RuntimeError) aborting due to nil port
            (phoenix 1.5.6) lib/phoenix/endpoint/cowboy2_adapter.ex:60: anonymous fn/5 in Phoenix.Endpoint.Cowboy2Adapter.child_specs/2
            (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
            (phoenix 1.5.6) lib/phoenix/endpoint/cowboy2_adapter.ex:55: Phoenix.Endpoint.Cowboy2Adapter.child_specs/2
            (phoenix 1.5.6) lib/phoenix/endpoint/supervisor.ex:106: Phoenix.Endpoint.Supervisor.init/1
            (stdlib 3.14) supervisor.erl:301: :supervisor.init/1
            (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2021-03-10T14:55:01.190 application=phoenix [error] :port for http config is nil, cannot start server
2021-03-10T14:55:01.204 [info] Application block_scout_web exited: BlockScoutWeb.Application.start(:normal, []) returned an error: shutdown: failed to start child: BlockScoutWeb.Endpoint
    ** (EXIT) an exception was raised:
        ** (RuntimeError) aborting due to nil port
            (phoenix 1.5.6) lib/phoenix/endpoint/cowboy2_adapter.ex:60: anonymous fn/5 in Phoenix.Endpoint.Cowboy2Adapter.child_specs/2
            (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
            (phoenix 1.5.6) lib/phoenix/endpoint/cowboy2_adapter.ex:55: Phoenix.Endpoint.Cowboy2Adapter.child_specs/2
            (phoenix 1.5.6) lib/phoenix/endpoint/supervisor.ex:106: Phoenix.Endpoint.Supervisor.init/1
            (stdlib 3.14) supervisor.erl:301: :supervisor.init/1
            (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by vbaranov** [comment]
@unqjohnny what is your set of environment variables for the application? Which version of explorer do you use?

**Comment by unqjohnny** [comment]
@vbaranov  thanks a lot .

 solved when i  set env: export PORT=4000.

but then get this: 

```
2021-03-10T15:24:18.895 application=que [info] [Que] Booting Que
2021-03-10T15:24:18.896 application=que [info] [Que] Booting Server Supervisor for Workers
2021-03-10T15:24:19.036 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4000 (http)
2021-03-10T15:24:19.062 application=phoenix [info] Access BlockScoutWeb.Endpoint at https://localhost:4000
2021-03-10T15:24:19.675 [info] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:1889 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}
2021-03-10T15:24:19.675 application=explorer [warn] Failed to get exchange rates with reason 'Source URL is nil'.
2021-03-10T15:24:19.694 [info] TLS :client: In state :certify at ssl_handshake.erl:1889 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}
2021-03-10T15:24:19.696 [error] GenServer Explorer.KnownTokens terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:tls_alert, {:handshake_failure, 'TLS client: In state certify at ssl_handshake.erl:1889 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}} of type Tuple. This protocol is implemented for the following type(s): Explorer.Chain.Address, Explorer.Chain.Data, Explorer.Chain.Hash, Cldr.Unit, Postgrex.Copy, Postgrex.Query, Que.Job, ExJsonSchema.Validator.Error.AllOf, ExJsonSchema.Validator.Error.MultipleOf, ExJsonSchema.Validator.Error.Dependencies, ExJsonSchema.Validator.Error.Type, ExJsonSchema.Validator.Error.MinProperties, ExJsonSchema.Validator.Error.MinItems, ExJsonSchema.Validator.Error.OneOf, ExJsonSchema.Validator.Error.Not, ExJsonSchema.Validator.Error.MaxLength, ExJsonSchema.Validator.Error.UniqueItems, ExJsonSchema.Validator.Error.MaxProperties, ExJsonSchema.Validator.Error.AdditionalItems, ExJsonSchema.Validator.Error.Enum, ExJsonSchema.Validator.Error.Format, ExJsonSchema.Validator.Error.Maximum, ExJsonSchema.Validator.Error.AdditionalProperties, ExJsonSchema.Validator.Error.Minimum, ExJsonSchema.Validator.Error.MaxItems, ExJsonSchema.Validator.Error.MinLength, ExJsonSchema.Validator.Error.Pattern, ExJsonSchema.Validator.Error.AnyOf, ExJsonSchema.Validator.Error.Required, Decimal, Float, DateTime, Time, List, Version.Requirement, Atom, Integer, Version, Date, BitString, NaiveDateTime, URI
    (elixir 1.11.3) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.11.3) lib/string/chars.ex:22: String.Chars.to_string/1
    (explorer 0.0.1) lib/explorer/known_tokens/known_tokens.ex:43: anonymous fn/1 in Explorer.KnownTokens.handle_info/2
    (logger 1.11.3) lib/logger.ex:886: Logger.__do_log__/4
    (explorer 0.0.1) lib/explorer/known_tokens/known_tokens.ex:43: Explorer.KnownTokens.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {#Reference<0.480755968.3675258882.254243>, {:error, {:tls_alert, {:handshake_failure, 'TLS client: In state certify at ssl_handshake.erl:1889 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}}}}
State: %{}
2021-03-10T15:24:19.974 [info] TLS :client: In state :certify at ssl_handshake.erl:1889 generated CLIENT ALERT: Fatal - Handshake Failure
....
2021-03-10T15:24:21.926 application=db_connection [info] Postgrex.Protocol (#PID<0.542.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1023.0> exited
2021-03-10T15:24:21.932 application=indexer fetcher=block_catchup [error] Catchup index stream exited with reason ({:shutdown, {GenServer, :call, [#PID<0.626.0>, {:lock, "block_numbers", #Reference<0.480755968.3675258883.257833>}, 5000]}}). Restarting
2021-03-10T15:24:21.949 [info] Application explorer exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,explorer,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,explorer,shutdown})
```

**Comment by vbaranov** [comment]
What is your Erlang, Elixir versions? Do they follow prerequisites?
Did you set `DATABASE_URL` env var?

**Comment by unqjohnny** [comment]
@vbaranov 

version: 
```
 erl -version:
 Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 11.1.8

 elixir -v:
 Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.11.3 (compiled with Erlang/OTP 23)
```

yes, DATABASE_URL exists.
```
echo $DATABASE_URL
postgresql://user:@localhost:5432/blockscout?ssl=false
```

and ```mix do ecto.create, ecto.migrate```. success prvious.

**Comment by vbaranov** [comment]
Which archive node do you use? What did you set for `ETHEREUM_JSONRPC_` env vars family?

**Comment by unqjohnny** [comment]
@vbaranov 

```
echo $ETHEREUM_JSONRPC_VARIANT
geth


echo $ETHEREUM_JSONRPC_HTTP_URL
http://172.18.2.128:8545

echo $MIX_ENV
prod
```

not set other ETHEREUM_JSONRPC_ env

**Comment by unqjohnny** [comment]
@vbaranov 

previous  when i  ```cd apps/explorer && npm install;```
get this :
```
npm install

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: undefined,
npm WARN EBADENGINE   required: { node: '14.x', npm: '6.x' },
npm WARN EBADENGINE   current: { node: 'v15.11.0', npm: '7.6.0' }
npm WARN EBADENGINE }

up to date, audited 27 packages in 3s

found 0 vulnerabilities
```

Is this normal ？？

**Comment by vbaranov** [comment]
>echo $ETHEREUM_JSONRPC_HTTP_URL

You should set `ETHEREUM_JSONRPC_TRACE_URL` as well

>npm WARN EBADENGINE   required: { node: '14.x', npm: '6.x' },
npm WARN EBADENGINE   current: { node: 'v15.11.0', npm: '7.6.0' }

You should downgrade to { node: '14.x', npm: '6.x' }

**Comment by unqjohnny** [comment]
Thanks, i will try

**Comment by unqjohnny** [comment]
> > echo $ETHEREUM_JSONRPC_HTTP_URL
> 
> You should set `ETHEREUM_JSONRPC_TRACE_URL` as well
> 
> > npm WARN EBADENGINE   required: { node: '14.x', npm: '6.x' },
> > npm WARN EBADENGINE   current: { node: 'v15.11.0', npm: '7.6.0' }
> 
> You should downgrade to { node: '14.x', npm: '6.x' }

After downgrade to { node: '14.x', npm: '6.x' }
```
cd apps/explorer && npm install
```
got:
```
npm install
audited 26 packages in 2.315s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

and mix phx.server got:
```
2021-03-10T16:53:38.794 application=que [info] [Que] Booting Que
2021-03-10T16:53:38.795 application=que [info] [Que] Booting Server Supervisor for Workers
2021-03-10T16:53:39.042 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4000 (http)
2021-03-10T16:53:39.049 application=phoenix [info] Running BlockScoutWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4001 (https)
2021-03-10T16:53:39.071 application=phoenix [info] Access BlockScoutWeb.Endpoint at https://localhost:4000


2021-03-10T16:53:39.599 [info] TLS :client: In state :certify at ssl_handshake.erl:1889 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}

2021-03-10T16:53:41.864 [error] GenServer Explorer.KnownTokens terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:tls_alert, {:handshake_failure, 'TLS client: In state certify at ssl_handshake.erl:1889 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}} of type Tuple. This protocol is implemented for the following type(s): Explorer.Chain.Address, Explorer.Chain.Data, Explorer.Chain.Hash, Cldr.Unit, Postgrex.Copy, Postgrex.Query, Que.Job, ExJsonSchema.Validator.Error.AllOf, ExJsonSchema.Validator.Error.MultipleOf, ExJsonSchema.Validator.Error.Dependencies, ExJsonSchema.Validator.Error.Type, ExJsonSchema.Validator.Error.MinProperties, ExJsonSchema.Validator.Error.MinItems, ExJsonSchema.Validator.Error.OneOf, ExJsonSchema.Validator.Error.Not, ExJsonSchema.Validator.Error.MaxLength, ExJsonSchema.Validator.Error.UniqueItems, ExJsonSchema.Validator.Error.MaxProperties, ExJsonSchema.Validator.Error.AdditionalItems, ExJsonSchema.Validator.Error.Enum, ExJsonSchema.Validator.Error.Format, ExJsonSchema.Validator.Error.Maximum, ExJsonSchema.Validator.Error.AdditionalProperties, ExJsonSchema.Validator.Error.Minimum, ExJsonSchema.Validator.Error.MaxItems, ExJsonSchema.Validator.Error.MinLength, ExJsonSchema.Validator.Error.Pattern, ExJsonSchema.Validator.Error.AnyOf, ExJsonSchema.Validator.Error.Required, Decimal, Float, DateTime, Time, List, Version.Requirement, Atom, Integer, Version, Date, BitString, NaiveDateTime, URI
    (elixir 1.11.3) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.11.3) lib/string/chars.ex:22: String.Chars.to_string/1
    (explorer 0.0.1) lib/explorer/known_tokens/known_tokens.ex:43: anonymous fn/1 in Explorer.KnownTokens.handle_info/2
    (logger 1.11.3) lib/logger.ex:886: Logger.__do_log__/4
    (explorer 0.0.1) lib/explorer/known_tokens/known_tokens.ex:43: Explorer.KnownTokens.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {#Reference<0.356057048.3152281602.257368>, {:error, {:tls_alert, {:handshake_failure, 'TLS client: In state certify at ssl_handshake.erl:1889 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}}}}
State: %{}
2021-03-10T16:53:41.891 application=indexer fetcher=block_catchup first_block_number=230276 last_block_number=230267 [error] ** (RuntimeError) could not lookup Ecto repo Explorer.Repo because it was not started or it does not exist
    (ecto 3.5.5) lib/ecto/repo/registry.ex:19: Ecto.Repo.Registry.lookup/1
    (ecto 3.5.5) lib/ecto/repo/transaction.ex:16: Ecto.Repo.Transaction.transaction/4
    (stdlib 3.14) timer.erl:197: :timer.tc/3
    (explorer 0.0.1) lib/explorer/repo.ex:21: anonymous fn/2 in Explorer.Repo.logged_transaction/2
    (explorer 0.0.1) lib/explorer/logger.ex:14: Explorer.Logger.metadata/2
    (explorer 0.0.1) lib/explorer/chain/import.ex:330: anonymous fn/3 in Explorer.Chain.Import.import_transactions/2
    (elixir 1.11.3) lib/enum.ex:3776: Enumerable.List.reduce/3
    (elixir 1.11.3) lib/enum.ex:2243: Enum.reduce_while/3


Retrying.
2021-03-10T16:53:41.891 application=indexer fetcher=block_catchup first_block_number=230286 last_block_number=230277 [error] ** (RuntimeError) could not lookup Ecto repo Explorer.Repo because it was not started or it does not exist
    (ecto 3.5.5) lib/ecto/repo/registry.ex:19: Ecto.Repo.Registry.lookup/1
    (ecto 3.5.5) lib/ecto/repo/queryable.ex:210: Ecto.Repo.Queryable.execute/4
    (explorer 0.0.1) lib/explorer/chain/import/runner/blocks.ex:293: Explorer.Chain.Import.Runner.Blocks.lose_consensus/5
    (ecto 3.5.5) lib/ecto/multi.ex:646: Ecto.Multi.apply_operation/5
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.5.5) lib/ecto/multi.ex:630: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:1027: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.3.1) lib/db_connection.ex:1444: DBConnection.run_transaction/4

```

**Comment by unqjohnny** [comment]
solved after:
```
mix deps.update hackney
```
referer: https://elixirforum.com/t/erlang-v-23-0-and-httpoison-error/31615/8

thanks a lot @vbaranov

**Comment by hhq365** [comment]
thank you .that's useful
