### ISSUE TITLE
EthereumJSONRPC.handle_get_block does not handle error responses in batched results.

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/blockscout#465]
From https://github.com/poanetwork/poa-explorer/pull/459#issuecomment-407663054

https://github.com/poanetwork/poa-explorer/blob/aeb1cc37682add9b8ffa2e007b97058685685e1c/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex#L416-L421

does not handle errors in the batch results.

```
Jul 25 06:55:34 docker[13055]: 06:55:34.846 [error] Task #PID<0.746.0> started from #PID<0.743.0> terminating
Jul 25 06:55:34 docker[13055]: ** (FunctionClauseError) no function clause matching in anonymous fn/2 in EthereumJSONRPC.handle_get_blocks/1
Jul 25 06:55:34 docker[13055]:     (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:418: anonymous fn(%{error: %{code: -32000, message: "No trusted canonical hash trie"}, id: 5871299, jsonrpc: "2.0"}, {[%{"difficulty" => "0x2", "extraData" => "0xd783010703846765746887676f312e392e32856c696e75780000000000000000045b9351f2fc55ae6478b8bcd01ecb3e8e7c2bc23e1ecf674fdd24371473ba29601a0d430cb6d06a4671e0cd4182c603397d536005cbcb5a7018c8777e54f52b00", "gasLimit" => "0x989680", "gasUsed" => "0x0", "hash" => "0x8797954cc3eae6a983ae0f48b148d2d490d4a0f67bb0507c9d46a6b63db21e6a", "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner" => "0x0000000000000000000000000000000000000000", "mixHash" => "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce" => "0x0000000000000000", "number" => "0x5996c2", "parentHash" => "0x5cb7915808ed8bff82237aa7cfcabdd5856833ca9e248337d0fd9f3a8bb4d4c1", "receiptsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size" => "0x261", "stateRoot" => "0x36f805b9816525aa63bc50e020de89f498bf5658bb15d4a3deb247b4a452316d", "timestamp" => "0x5b56518a", "totalDifficulty" => "0xae1a7e", "transactions" => [], "transactionsRoot" => "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421", "uncles" => []}], :more}) in EthereumJSONRPC.handle_get_blocks/1
Jul 25 06:55:34 docker[13055]:     (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
Jul 25 06:55:34 docker[13055]:     (ethereum_jsonrpc) lib/ethereum_jsonrpc.ex:418: EthereumJSONRPC.handle_get_blocks/1
Jul 25 06:55:34 docker[13055]:     (indexer) lib/indexer/block_fetcher.ex:266: Indexer.BlockFetcher.import_range/3
Jul 25 06:55:34 docker[13055]:     (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
Jul 25 06:55:34 docker[13055]:     (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
Jul 25 06:55:34 docker[13055]:     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Jul 25 06:55:34 docker[13055]: Function: &:erlang.apply/2
Jul 25 06:55:34 docker[13055]:     Args: [#Function<19.90564126/1 in Indexer.BlockFetcher.stream_import/3>, [5871298..5871299]]
```

**Comment by saneery** [comment]
@KronicDeth, I think the issue solved by this commit https://github.com/poanetwork/blockscout/commit/3499155cdba64241f6a8c72b16f4cd06d81afe0a

Errors are handled here:
https://github.com/poanetwork/blockscout/blob/master/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex#L83

**Comment by vbaranov** [comment]
@saneery indeed, it has been already handled. Thanks.
