### ISSUE TITLE
Indexer Internal Transaction Fetcher Terminating

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#540]
While indexing `sokol` on my local machine I started noticing these errors around the 1m block range:

```
[debug] fetching internal transactions for 10 transactions
[error] Task #PID<0.18988.16> started from Indexer.InternalTransactionFetcher terminating
** (stop) exited in: GenServer.call(Indexer.BalanceFetcher, {:buffer, [%{block_quantity: "0x2AF05A", hash_data: "0x3ff4abd2efc1b0cec3e18610190fd9830ed3fcd1"}, %{block_quantity: "0x2AF04B", hash_data: "0x4e20226355b4464cf8f3b67fc318b753a7c125b3"}, %{block_quantity: "0x2AF04B", hash_data: "0xa2e4bf83974ebfb788c1dca562ca9eba001f0382"}, %{block_quantity: "0x2AF05A", hash_data: "0xc366429967251f8b0dffe8ade96201d13f9d0de3"}]}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:834: GenServer.call/3
    (indexer) lib/indexer/buffered_task.ex:367: anonymous fn/3 in Indexer.BufferedTask.spawn_next_batch/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<4.79188749/0 in Indexer.BufferedTask.spawn_next_batch/1>
    Args: []
```

### Environment

* Operating System: Mac

### Steps to reproduce

1. Index `sokol` on mac
2. Reach the 1m block range
3. Start noticing errors

**Comment by acravenho** [comment]
I'm no longer seeing these errors on `sokol`.
