### ISSUE TITLE
ERROR 21000 (cardinality_violation): more than one row returned by a subquery used as an expression

### ISSUE THREAD

**Issue by KronicDeth** [poanetwork/blockscout#593]
```
[error] Task #PID<0.31926.0> started from Indexer.InternalTransactionFetcher terminating
** (Postgrex.Error) ERROR 21000 (cardinality_violation): more than one row returned by a subquery used as an expression
    (ecto) lib/ecto/adapters/sql.ex:440: Ecto.Adapters.SQL.execute_or_reset/7
    (explorer) lib/explorer/chain/import.ex:783: Explorer.Chain.Import.update_transactions/2
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/chain/import.ex:198: Explorer.Chain.Import.all/1
    (indexer) lib/indexer/internal_transaction_fetcher.ex:103: Indexer.InternalTransactionFetcher.run/3
    (indexer) lib/indexer/buffered_task.ex:367: anonymous fn/3 in Indexer.BufferedTask.spawn_next_batch/1
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<4.71023014/0 in Indexer.BufferedTask.spawn_next_batch/1>
    Args: []
```

**Comment by KronicDeth** [comment]
From 

https://github.com/poanetwork/blockscout/blob/57b6f7487e93543c432f8cbb73db6f36fe8136ae/apps/explorer/lib/explorer/chain/import.ex#L764-L783

it is likely this

https://github.com/poanetwork/blockscout/blob/57b6f7487e93543c432f8cbb73db6f36fe8136ae/apps/explorer/lib/explorer/chain/import.ex#L773

`SELECT` that is returning too many rows.

**Comment by KronicDeth** [comment]
@acravenho this would seem to indicate that a transaction is able to create more than one contract.  I thought we had determined that wasn't possible or do you think this is due to the deeping nested transaction creates as you did in your test ase showing up as direct internal transactions?  What is the transaction/block with the create tests you made on Sokol?

**Comment by acravenho** [comment]
Here was a test for contract that creates multiple contracts: `0x4c298c5dc1033fe0d104269abcca22858e87eed952d701f573f8222712d6c574`

**Comment by KronicDeth** [comment]
```
curl --data '{"method":"eth_getTransactionByHash","params":
["0x4c298c5dc1033fe0d104269abcca22858e87eed952d701f573f8222712d6c574"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST "https://sokol-trace.poa.network" | jq
```

```json
{
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0x58b5cfda825315afc47f425b4f9375a24c0b7227e5df097c2f78e79774927fa1",
    "blockNumber": "0x38a360",
    "chainId": "0x4d",
    "condition": null,
    "creates": null,
    "from": "0x59e2e9ecf133649b1a7efc731162ff09d29ca5a5",
    "gas": "0xde827",
    "gasPrice": "0x3b9aca00",
    "hash": "0x4c298c5dc1033fe0d104269abcca22858e87eed952d701f573f8222712d6c574",
    "input": "0x",
    "nonce": "0x47",
    "publicKey": "0x404c2bc85e27be5099aa28102fb7ed0b7bfb0b68f5a81fe72e5624971563490f281f79a2e718ed3c2ce4aba8055f25fd67ae2caa51d09cae4530024353582384",
    "r": "0x2d5a9ee78e59a0db29520ca933c30bf7c8991e40bc493589cab03d9398336959",
    "raw": "0xf86447843b9aca00830de827940ebbd28505d4c0623aedb56e5f49bdc0b8ca006d808081bda02d5a9ee78e59a0db29520ca933c30bf7c8991e40bc493589cab03d93983369599f1b789dd2e422896ae0cb5f7d4a8220a2c8178b6b7fbce69cb569f63e49af5d",
    "s": "0x1b789dd2e422896ae0cb5f7d4a8220a2c8178b6b7fbce69cb569f63e49af5d",
    "standardV": "0x0",
    "to": "0x0ebbd28505d4c0623aedb56e5f49bdc0b8ca006d",
    "transactionIndex": "0x0",
    "v": "0xbd",
    "value": "0x0"
  },
  "id": 1
}
```

So, I'll test on block number `0x38a360`. which is `3711840`.

**Comment by KronicDeth** [comment]
No, 3_711_839..3_711_841 imports fine, so it is not that test block.

**Comment by acravenho** [comment]
@KronicDeth 

Here is the error I'm receiving while indexing `sokol`

```
10:11:15.052 application=indexer [debug] got blocks 3911629 - 3911620
10:11:15.060 application=indexer [debug] fetching internal transactions for 10 transactions
10:11:15.107 application=indexer [error] Catchup index stream exited with reason ({%Postgrex.Error{connection_id: 66409, message: nil, postgres: %{code: :cardinality_violation, file: "nodeModifyTable.c", hint: "Ensure that no rows proposed for insertion within the same command have duplicate constrained values.", line: "1259", message: "ON CONFLICT DO UPDATE command cannot affect row a second time", pg_code: "21000", routine: "ExecOnConflictUpdate", severity: "ERROR", unknown: "ERROR"}}, [{Explorer.Repo, :"-safe_insert_all/3-fun-1-", 5, [file: 'lib/explorer/repo.ex', line: 58]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1925]}, {Explorer.Chain.Import, :insert_changes_list, 2, [file: 'lib/explorer/chain/import.ex', line: 799]}, {Explorer.Chain.Import, :insert_token_balances, 2, [file: 'lib/explorer/chain/import.ex', line: 758]}, {Ecto.Multi, :apply_operation, 5, [file: 'lib/ecto/multi.ex', line: 421]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1925]}, {Ecto.Multi, :"-apply_operations/5-fun-1-", 5, [file: 'lib/ecto/multi.ex', line: 411]}, {Ecto.Adapters.SQL, :"-do_transaction/3-fun-1-", 3, [file: 'lib/ecto/adapters/sql.ex', line: 576]}, {DBConnection, :transaction_run, 4, [file: 'lib/db_connection.ex', line: 1283]}, {DBConnection, :run_begin, 3, [file: 'lib/db_connection.ex', line: 1207]}, {DBConnection, :transaction, 3, [file: 'lib/db_connection.ex', line: 798]}, {Ecto.Repo.Queryable, :transaction, 4, [file: 'lib/ecto/repo/queryable.ex', line: 23]}, {Explorer.Chain.Import, :all, 1, [file: 'lib/explorer/chain/import.ex', line: 206]}, {Indexer.BlockFetcher.Catchup, :import, 2, [file: 'lib/indexer/block_fetcher/catchup.ex', line: 105]}, {Indexer.BlockFetcher, :fetch_and_import_range, 2, [file: 'lib/indexer/block_fetcher.ex', line: 113]}, {Indexer.BlockFetcher.Catchup, :fetch_and_import_range_from_sequence, 3, [file: 'lib/indexer/block_fetcher/catchup.ex', line: 159]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}). Restarting
```
The Genesis Indexer attempts to restart but this error occurs over and over after this point.

**Comment by KronicDeth** [comment]
@acravenho is there a part of the log after the `[error]` you posted?  There should be a section in `explorer.log` that shows the inputs to the `import` function,  `ecto.log` that shows the actual SQL query, and `error.log` might have addition details too.

**Comment by acravenho** [comment]
@KronicDeth I created #638 which I think includes the query you're looking for. I can add it here and close that issue if it makes more sense. Please let me know if there is more info that I missed.

**Comment by KronicDeth** [comment]
Closed in favor of #638, which has more details.

**Comment by KronicDeth** [comment]
#638 appears to be about receipts

**Comment by acravenho** [comment]
@KronicDeth I'm sorry, I had the issues mixed up. I will need to let `sokol` run with the better error reporting. I should have sufficient data with an hour.
