### ISSUE TITLE
foreign_key_violation, constraint: "transactions_block_hash_fkey"

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#601]
```
Last message: {:EXIT, #PID<0.1407.0>, {%Postgrex.Error{connection_id: 67707, message: nil, postgres: %{code: :foreign_key_violation, constraint: "transactions_block_hash_fkey", detail: "Key (hash)=(\\xc28b5ca63d7806238f9f38cc33197d7717ee5c30b782e9e7a6c50f5958cf724c) is still referenced from table \"transactions\".", file: "ri_triggers.c", line: "3335", message: "updateor delete on table \"blocks\" violates foreign key constraint \"transactions_block_hash_fkey\" on table \"transactions\"", pg_code: "23503", routine: "ri_ReportViolation", schema: "public", severity: "ERROR", table: "transactions", unknown: "ERROR"}}, [{Explorer.Repo, :"-safe_insert_all/3-fun-1-", 5, [file: 'lib/explorer/repo.ex', line: 58]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1899]}, {Explorer.Chain.Import, :insert_changes_list, 2, [file: 'lib/explorer/chain/import.ex', line: 745]}, {Explorer.Chain.Import, :insert_blocks, 2, [file: 'lib/explorer/chain/import.ex', line: 612]}, {Ecto.Multi, :apply_operation, 5, [file: 'lib/ecto/multi.ex', line: 421]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1899]}, {Ecto.Multi, :"-apply_operations/5-fun-1-", 5, [file: 'lib/ecto/multi.ex', line: 411]}, {Ecto.Adapters.SQL, :"-do_transaction/3-fun-1-", 3, [file: 'lib/ecto/adapters/sql.ex', line: 576]}, {DBConnection, :transaction_run, 4, [file: 'lib/db_connection.ex', line: 1283]}, {DBConnection, :run_begin, 3, [file: 'lib/db_connection.ex', line: 1207]}, {DBConnection, :transaction, 3, [file: 'lib/db_connection.ex', line: 798]}, {Ecto.Repo.Queryable, :transaction, 4, [file: 'lib/ecto/repo/queryable.ex', line: 23]}, {Explorer.Chain.Import,:all, 1, [file: 'lib/explorer/chain/import.ex', line: 198]}, {Indexer.BlockFetcher.Realtime, :import, 2, [file: 'lib/indexer/block_fetcher/realtime.ex', line: 88]}, {Indexer.BlockFetcher, :insert, 2, [file: 'lib/indexer/block_fetcher.ex', line: 137]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 88]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
State: %Indexer.Sequence{current: nil, queue: {[], []}, step: 2}
[error] Task #PID<0.15079.0> started from Indexer.InternalTransactionFetcher terminating
** (Postgrex.Error) ERROR 21000 (cardinality_violation): more than one row returned by a subquery used as an expression
    (ecto) lib/ecto/adapters/sql.ex:440: Ecto.Adapters.SQL.execute_or_reset/7
    (explorer) lib/explorer/chain/import.ex:783: Explorer.Chain.Import.update_transactions/2
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/chain/import.ex:198: Explorer.Chain.Import.all/1
    (indexer) lib/indexer/internal_transaction_fetcher.ex:103: Indexer.InternalTransactionFetcher.run/3
    (indexer) lib/indexer/buffered_task.ex:367: anonymous fn/3 in Indexer.BufferedTask.spawn_next_batch/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<4.79188749/0 in Indexer.BufferedTask.spawn_next_batch/1>
    Args: []
```

### Environment

* Operating System: Mac

### Steps to reproduce

1. Index `sokol`
2. This error seems to be popping up every 100 blocks or so.

**Comment by acravenho** [comment]
I'm not sure if this is the same issue:

```
Last message: {:EXIT, #PID<0.20548.0>, {%Postgrex.Error{connection_id: 89815, message: nil, postgres: %{code: :cardinality_violation, file: "nodeModifyTable.c", hint: "Ensure that no rows proposed for insertion within the same command have duplicate constrained values.", line: "1259", message: "ON CONFLICT DO UPDATE command cannot affect row a second time", pg_code: "21000", routine: "ExecOnConflictUpdate", severity: "ERROR", unknown: "ERROR"}}, [{Explorer.Repo, :"-safe_insert_all/3-fun-1-", 5, [file: 'lib/explorer/repo.ex', line: 58]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1925]}, {Explorer.Chain.Import, :insert_changes_list, 2, [file: 'lib/explorer/chain/import.ex', line: 799]}, {Explorer.Chain.Import, :insert_token_balances, 2, [file: 'lib/explorer/chain/import.ex', line: 758]}, {Ecto.Multi, :apply_operation, 5, [file: 'lib/ecto/multi.ex', line: 421]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1925]}, {Ecto.Multi, :"-apply_operations/5-fun-1-", 5, [file: 'lib/ecto/multi.ex', line: 411]}, {Ecto.Adapters.SQL, :"-do_transaction/3-fun-1-", 3,[file: 'lib/ecto/adapters/sql.ex', line: 576]}, {DBConnection, :transaction_run, 4, [file: 'lib/db_connection.ex', line: 1283]}, {DBConnection, :run_begin, 3, [file: 'lib/db_connection.ex', line: 1207]}, {DBConnection, :transaction, 3, [file: 'lib/db_connection.ex', line: 798]}, {Ecto.Repo.Queryable, :transaction, 4, [file: 'lib/ecto/repo/queryable.ex', line: 23]}, {Explorer.Chain.Import, :all, 1, [file: 'lib/explorer/chain/import.ex', line: 206]}, {Indexer.BlockFetcher.Catchup, :import, 2, [file: 'lib/indexer/block_fetcher/catchup.ex', line: 104]}, {Indexer.BlockFetcher, :fetch_and_import_range, 2, [file: 'lib/indexer/block_fetcher.ex', line: 113]}, {Indexer.BlockFetcher.Catchup, :fetch_and_import_range_from_sequence, 3, [file: 'lib/indexer/block_fetcher/catchup.ex', line: 158]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
State: %Indexer.Sequence{current: nil, queue: {[8..0, 18..9, 28..19, 38..29, 48..39, 58..49, 68..59, 78..69, 88..79, 98..89, 108..99, 118..109, 128..119, 138..129, 148..139, 158..149, 168..159, 178..169, 188..179, 198..189, 208..199, 218..209, 228..219, 238..229, 248..239, 258..249, 268..259, 278..269, 288..279, 298..289, 308..299, 318..309, 328..319, 338..329, 348..339, 358..349, 368..359, 378..369, 388..379, 398..389, 408..399, 418..409, 428..419, 438..429, 448..439, 458..449, 468..459, ...], [3911258..3911249, 3911248..3911239, 3911238..3911229, 3911228..3911219, 3911218..3911209, 3911208..3911199, 3911198..3911189, 3911188..3911179, 3911178..3911169, 3911168..3911159, 3911158..3911149, 3911148..3911139, 3911138..3911129, 3911128..3911119, 3911118..3911109, 3911108..3911099, 3911098..3911089, 3911088..3911079, 3911078..3911069, 3911068..3911059, 3911058..3911049, 3911048..3911039, 3911038..3911029, 3911028..3911019, 3911018..3911009, 3911008..3910999, 3910998..3910989, 3910988..3910979, 3910978..3910969, 3910968..3910959, 3910958..3910949, 3910948..3910939, 3910938..3910929, 3910928..3910919, 3910918..3910909, 3910908..3910899, 3910898..3910889, 3910888..3910879, 3910878..3910869, 3910868..3910859, 3910858..3910849, 3910848..3910839, 3910838..3910829, 3910828..3910819, 3910818..3910809, 3910808..3910799, ...]}, step: -10}
[error] Could not insert all of chunk into Elixir.Explorer.Chain.Address.TokenBalance using options because of error.

Chunk:

[%{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<27, 66, 144, 168, 113, 9, 37, 80, 170, 106, 99, 91, 125, 180, 245, 178, 155, 117, 190, 13>>}, block_number: 3911634, inserted_at: #DateTime<2018-08-24 18:53:11.358012Z>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<106, 132, 171, 234, 88, 101, 206, 194, 44, 156, 111, 112, 201, 183, 223, 143, 89, 19, 106, 46>>}, updated_at: #DateTime<2018-08-24 18:53:11.358012Z>}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<27, 66, 144, 168, 113, 9, 37, 80, 170, 106, 99, 91, 125, 180, 245, 178, 155, 117, 190, 13>>}, block_number: 3911634, inserted_at: #DateTime<2018-08-24 18:53:11.358012Z>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<227, 69, 20, 64, 14, 202, 62, 86, 131, 254, 185, 160, 107, 201, 100, 138, 136, 39, 150, 89>>}, updated_at: #DateTime<2018-08-24 18:53:11.358012Z>}, %{address_hash:%Explorer.Chain.Hash{byte_count: 20, bytes: <<81, 8, 64, 71, 53, 105, 125, 220, 245, 188, 220, 131, 199, 220, 39, 104, 235, 95, 181, 112>>}, block_number: 3911634, inserted_at: #DateTime<2018-08-24 18:53:11.358012Z>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<106, 132, 171, 234, 88, 101, 206, 194, 44, 156, 111, 112, 201, 183, 223, 143, 89, 19, 106, 46>>}, updated_at: #DateTime<2018-08-24 18:53:11.358012Z>}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<81, 8, 64, 71, 53, 105, 125, 220, 245, 188, 220, 131, 199, 220, 39, 104, 235, 95, 181, 112>>}, block_number: 3911634, inserted_at: #DateTime<2018-08-24 18:53:11.358012Z>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<227, 69, 20, 64, 14, 202, 62, 86, 131, 254, 185, 160, 107, 201, 100, 138, 136, 39, 150, 89>>}, updated_at: #DateTime<2018-08-24 18:53:11.358012Z>}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<106, 132, 171, 234, 88, 101, 206, 194, 44, 156, 111, 112, 201, 183, 223, 143, 89, 19, 106, 46>>}, block_number: 3911634, inserted_at: #DateTime<2018-08-2418:53:11.358012Z>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<106, 132, 171, 234, 88, 101, 206, 194, 44, 156, 111, 112, 201, 183, 223, 143, 89, 19, 106, 46>>}, updated_at: #DateTime<2018-08-24 18:53:11.358012Z>}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<146, 26, 42, 36, 252, 9, 34, 197, 73, 145, 124, 210, 255, 23, 3,11, 86, 126, 50, 40>>}, block_number: 3911634, inserted_at: #DateTime<2018-08-24 18:53:11.358012Z>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<106, 132, 171, 234, 88, 101, 206, 194, 44, 156, 111, 112, 201, 183, 223, 143, 89, 19, 106, 46>>}, updated_at: #DateTime<2018-08-24 18:53:11.358012Z>}, %{address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<227, 69, 20, 64, 14, 202, 62, 86, 131, 254, 185, 160, 107, 201, 100, 138, 136, 39, 150, 89>>}, block_number: 3911634, inserted_at: #DateTime<2018-08-24 18:53:11.358012Z>, token_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<227, 69, 20, 64, 14, 202, 62, 86, 131, 254, 185, 160, 107, 201, 100, 138, 136, 39, 150, 89>>}, updated_at: #DateTime<2018-08-24 18:53:11.358012Z>}]

Options:

[conflict_target: [:address_hash, :block_number], on_conflict: :replace_all, returning: true, timeout: 60000, timestamps: %{inserted_at: #DateTime<2018-08-24 18:53:11.358012Z>, updated_at: #DateTime<2018-08-24 18:53:11.358012Z>}]
```

**Comment by alexandrule** [comment]
The same issue for me.

    ** (Postgrex.Error) ERROR 21000 (cardinality_violation): ON CONFLICT DO UPDATE command cannot affect row a second time
        (explorer) lib/explorer/repo.ex:58: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (explorer) lib/explorer/chain/import.ex:799: Explorer.Chain.Import.insert_changes_list/2
        (explorer) lib/explorer/chain/import.ex:758: Explorer.Chain.Import.insert_token_balances/2
        (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
        (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3

**Comment by KronicDeth** [comment]
@alexandrule please open a separate issue.  Your stacktrace is different, so it is a different issue.
