### ISSUE TITLE
Could not insert all of chunk into Elixir.Explorer.Chain.Block using options because of error.

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#620]
While testing #619, a fix for #614, I ran into this error. I don't believe they are related.

```
13:31:11.195 application=explorer [error] Could not insert all of chunk into Elixir.Explorer.Chain.Block using options because of error.

Chunk:

[%{difficulty: #Decimal<340282366920938463463374607431768211454>, gas_limit: 8000000, gas_used: 21000, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<48, 212, 255, 255, 55, 136, 240, 102, 212, 134, 149, 184, 224, 45, 79, 110, 128, 215, 15, 145, 126, 201, 162, 253, 16, 135, 154, 70, 31, 106, 147, 45>>}, inserted_at: #DateTime<2018-08-28 17:31:11.124661Z>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<112, 107, 133, 234, 148, 34, 28, 95, 9, 17, 165, 26, 208, 41, 62, 75, 191, 129, 28, 78>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<0, 0, 0, 0, 0, 0, 0, 0>>}, number: 4259623, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<157, 102, 74, 208, 121, 251, 70, 66, 71, 51, 69, 107, 153, 234, 73, 96, 253, 73, 103, 195, 30, 245, 26, 77, 166, 13, 160, 239, 182, 192, 37, 75>>}, size: 693, timestamp: #DateTime<2018-08-28 17:31:05Z>, total_difficulty: #Decimal<1449474596630868660553250135432330803875617044>, updated_at: #DateTime<2018-08-28 17:31:11.124661Z>}]

Options:

[conflict_target: :number, on_conflict: :replace_all, returning: true, timeout: 60000, timestamps: %{inserted_at: #DateTime<2018-08-28 17:31:11.124661Z>, updated_at: #DateTime<2018-08-28 17:31:11.124661Z>}]

Exception:

** (Postgrex.Error) ERROR 23503 (foreign_key_violation): update or delete on table "blocks" violates foreign key constraint "transactions_block_hash_fkey" on table "transactions"

    table: transactions
    constraint: transactions_block_hash_fkey

Key (hash)=(\x8a5b07675e9f39a67d94f682155c220ab1e2acbc8bca14eb4ef2e1a4af123037) is still referenced from table "transactions".
13:31:11.250 [error] GenServer Indexer.BlockFetcher.Realtime terminating
** (Postgrex.Error) ERROR 23503 (foreign_key_violation): update or delete on table "blocks" violates foreign key constraint "transactions_block_hash_fkey" on table "transactions"

    table: transactions
    constraint: transactions_block_hash_fkey

Key (hash)=(\x8a5b07675e9f39a67d94f682155c220ab1e2acbc8bca14eb4ef2e1a4af123037) is still referenced from table "transactions".
    (explorer) lib/explorer/repo.ex:58: anonymous fn/5 in Explorer.Repo.safe_insert_all/3
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer) lib/explorer/chain/import.ex:834: Explorer.Chain.Import.insert_changes_list/2
    (explorer) lib/explorer/chain/import.ex:643: Explorer.Chain.Import.insert_blocks/2
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/chain/import.ex:206: Explorer.Chain.Import.all/1
    (indexer) lib/indexer/block_fetcher/realtime.ex:145: Indexer.BlockFetcher.Realtime.import/2
    (indexer) lib/indexer/block_fetcher.ex:114: Indexer.BlockFetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block_fetcher/realtime.ex:65: Indexer.BlockFetcher.Realtime.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {%EthereumJSONRPC.Subscription{id: "0xb6717775d9a2e88c", subscriber_pid: #PID<0.569.0>, transport: EthereumJSONRPC.WebSocket, transport_options: [web_socket: EthereumJSONRPC.WebSocket.WebSocketClient, web_socket_options: %{web_socket: #PID<0.568.0>}, url: "wss://sokol-ws.poa.network/ws"]}, {:ok, %{"author" => "0x706b85ea94221c5f0911a51ad0293e4bbf811c4e", "difficulty" => "0xfffffffffffffffffffffffffffffffe", "extraData" => "0xd583010b088650617269747986312e32372e32826c69", "gasLimit" => "0x7a1200", "gasUsed" => "0x5208", "hash" => "0x30d4ffff3788f066d48695b8e02d4f6e80d70f917ec9a2fd10879a461f6a932d", "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner" => "0x706b85ea94221c5f0911a51ad0293e4bbf811c4e", "number" => "0x40ff27", "parentHash" => "0x9d664ad079fb46424733456b99ea4960fd4967c31ef51a4da60da0efb6c0254b", "receiptsRoot" => "0x056b23fbba480696b65fe5a59b8f2148a1299103c4f57df839233af2cf4ca2d2", "sealFields" => ["0x124de7c5", "0xdd5bddef69c3ca1b7d6a3f33092e26220276f66e66877ebc201d213c01cb94cb5443098bc611837b9447e66a062a21e9f303a49cb32886c5ce8bb25c3706e19a00"], "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "signature" => "dd5bddef69c3ca1b7d6a3f33092e26220276f66e66877ebc201d213c01cb94cb5443098bc611837b9447e66a062a21e9f303a49cb32886c5ce8bb25c3706e19a00", "size" => "0x240", "stateRoot" => "0x725c7bbfdd4bd88b73fa34809a407e2adadf23667c237338bd8e058eaa077f7e", "step" => "307095493", "timestamp" => "0x5b8586d9", "transactionsRoot" => "0xfcaca785ed8f1394e0c6af5ede9e0d89bf4607da270732c37793f6d91cbd3c21"}}}
State: %Indexer.BlockFetcher.Realtime{block_fetcher: %Indexer.BlockFetcher{broadcast: true, callback_module: Indexer.BlockFetcher.Realtime, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "https://sokol.poa.network", method_to_url: [eth_getBalance: "https://sokol-trace.poa.network", trace_replayTransaction: "https://sokol-trace.poa.network"], http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, subscription: %EthereumJSONRPC.Subscription{id: "0xb6717775d9a2e88c", subscriber_pid: #PID<0.569.0>, transport: EthereumJSONRPC.WebSocket, transport_options: [web_socket: EthereumJSONRPC.WebSocket.WebSocketClient, web_socket_options: %{web_socket: #PID<0.568.0>}, url: "wss://sokol-ws.poa.network/ws"]}}
```

### Environment

* Operating System: Mac

### Steps to reproduce

1. Index `sokol`

### Expected behaviour

Index block

### Actual behaviour

-

**Comment by KronicDeth** [comment]
I think I've seen this error before.  It has led to some of the flaky tests on CircleCI when the Realtime indexer tests rain, so it was pre-existing.

**Comment by acravenho** [comment]
Fixed by reorg support
