### ISSUE TITLE
Could not convert receipt to elixir - ETC Chain

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#638]
While attempting to index Ethereum Classic I received the following error reported in the `logs/dev/error.log` file.

```
** (ArgumentError) Could not convert receipt to elixir

Receipt:
  %{"blockHash" => "0xfcd0a1e2ad493c89118bb92118c05476f2f0ee79dd649dac3eaef7eab217ba38", "blockNumber" => "0x629801", "contractAddress" => nil, "cumulativeGasUsed" => "0x2add7", "gas" => 42000, "gasUsed" => "0x5258", "logs" => [], "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "root" => "0x72b9c1b5f069e5c941ff835d5d22266cf1a820852a661400d8be84e1624a58e1", "status" => nil, "transactionHash" => "0xd693f3aa840ea8aa61299702ec0f25db4beee4885c1330d6ea75c45d4e5fc863", "transactionIndex" => "0x6"}

Errors:
  {:unknown_value, %{key: "status", value: nil}}

    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipt.ex:275: EthereumJSONRPC.Receipt.ok!/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc) lib/ethereum_jsonrpc/receipts.ex:139: EthereumJSONRPC.Receipts.fetch/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.735.0>, {%ArgumentError{message: "Could not convert receipt to elixir\n\nReceipt:\n  %{\"blockHash\" => \"0xfcd0a1e2ad493c89118bb92118c05476f2f0ee79dd649dac3eaef7eab217ba38\", \"blockNumber\" => \"0x629801\", \"contractAddress\" => nil, \"cumulativeGasUsed\" => \"0x2add7\", \"gas\" => 42000, \"gasUsed\" => \"0x5258\", \"logs\" => [], \"logsBloom\" => \"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\", \"root\" => \"0x72b9c1b5f069e5c941ff835d5d22266cf1a820852a661400d8be84e1624a58e1\", \"status\" => nil, \"transactionHash\" => \"0xd693f3aa840ea8aa61299702ec0f25db4beee4885c1330d6ea75c45d4e5fc863\", \"transactionIndex\" => \"0x6\"}\n\nErrors:\n  {:unknown_value, %{key: \"status\", value: nil}}\n"}, [{EthereumJSONRPC.Receipt, :ok!, 2, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 275]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1314]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 139]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
State: %Indexer.Sequence{current: nil, queue: {[1..0, 11..2, 21..12, 31..22, 41..32, 51..42, 61..52, 71..62, 81..72, 91..82, 101..92, 111..102, 121..112, 131..122, 141..132, 151..142, 161..152, 171..162, 181..172, 191..182, 201..192, 211..202, 221..212, 231..222, 241..232, 251..242, 261..252, 271..262, 281..272, 291..282, 301..292, 311..302, 321..312, 331..322, 341..332, 351..342, 361..352, 371..362, 381..372, 391..382, 401..392, 411..402, 421..412, 431..422, 441..432, 451..442, 461..452, ...], [6461341..6461332, 6461331..6461322, 6461321..6461312, 6461311..6461302, 6461301..6461292, 6461291..6461282, 6461281..6461272, 6461271..6461262, 6461261..6461252, 6461251..6461242, 6461241..6461232, 6461231..6461222, 6461221..6461212, 6461211..6461202, 6461201..6461192, 6461191..6461182, 6461181..6461172, 6461171..6461162, 6461161..6461152, 6461151..6461142, 6461141..6461132, 6461131..6461122, 6461121..6461112, 6461111..6461102, 6461101..6461092, 6461091..6461082, 6461081..6461072, 6461071..6461062, 6461061..6461052, 6461051..6461042, 6461041..6461032, 6461031..6461022, 6461021..6461012, 6461011..6461002, 6461001..6460992, 6460991..6460982, 6460981..6460972, 6460971..6460962, 6460961..6460952, 6460951..6460942, 6460941..6460932, 6460931..6460922, 6460921..6460912, 6460911..6460902, 6460901..6460892, 6460891..6460882, ...]}, step: -10}
16:19:11.926 application=indexer [error] Catchup index stream exited with reason ({%ArgumentError{message: "Could not convert receipt to elixir\n\nReceipt:\n  %{\"blockHash\" => \"0xfcd0a1e2ad493c89118bb92118c05476f2f0ee79dd649dac3eaef7eab217ba38\", \"blockNumber\" => \"0x629801\", \"contractAddress\" => nil, \"cumulativeGasUsed\" => \"0x2add7\", \"gas\" => 42000, \"gasUsed\" => \"0x5258\", \"logs\" => [], \"logsBloom\" => \"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\", \"root\" => \"0x72b9c1b5f069e5c941ff835d5d22266cf1a820852a661400d8be84e1624a58e1\", \"status\" => nil, \"transactionHash\" => \"0xd693f3aa840ea8aa61299702ec0f25db4beee4885c1330d6ea75c45d4e5fc863\", \"transactionIndex\" => \"0x6\"}\n\nErrors:\n  {:unknown_value, %{key: \"status\", value: nil}}\n"}, [{EthereumJSONRPC.Receipt, :ok!, 2, [file: 'lib/ethereum_jsonrpc/receipt.ex', line: 275]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1314]}, {EthereumJSONRPC.Receipts, :fetch, 2, [file: 'lib/ethereum_jsonrpc/receipts.ex', line: 139]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}). Restarting
```

## Receipt from Web3 JS
```
{ blockHash: '0xfcd0a1e2ad493c89118bb92118c05476f2f0ee79dd649dac3eaef7eab217ba38',
  blockNumber: 6461441,
  contractAddress: null,
  cumulativeGasUsed: 175575,
  gasUsed: 21080,
  logs: [],
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  root: '0x72b9c1b5f069e5c941ff835d5d22266cf1a820852a661400d8be84e1624a58e1',
  status: false,
  transactionHash: '0xd693f3aa840ea8aa61299702ec0f25db4beee4885c1330d6ea75c45d4e5fc863',
  transactionIndex: 6 }
```

An interesting note here is that every transaction on Ethereum Classic seems to return `status: false`. 

### Environment

* Operating System: MAC

### Steps to reproduce

1. Start indexer on Ethereum Classic

### Expected behaviour

Index the blocks and transactions

### Actual behaviour

Transaction receipt error.

**Comment by KronicDeth** [comment]
Does Ethereum Classic act like pre-Byzantium Ethereum?  So, if we see `"status": null` we need to treat it the same as not having the `"status"` key at all, which is how we detect pre-Byzantium now.

**Comment by acravenho** [comment]
Yes, that makes sense. The fork between `Ethereum` and `Classic` occurred in mid-2016, pre-Byzantium is before October of 2017. Most likely Classic never received this upgrade.
