### ISSUE TITLE
Indexer exits when connecting to local parity

### ISSUE THREAD

**Issue by phahulin** [poanetwork/blockscout#681]
When trying to setup everything locally (running both explorer and parity), it seems that indexer fails to connect to parity via websockets:
```
$ mix phx.server
14:10:26.359 application=file_system [error] `inotify-tools` is needed to run `file_system` for your system, check https://github.com/rvoicilas/inotify-tools/wiki for more information about how to install it. If it's already installed but not be found, appoint executable file with `config.exs` or `FILESYSTEM_FSINOTIFY_EXECUTABLE_FILE` env.
14:10:26.360 application=phoenix_live_reload [warn] Could not start Phoenix live-reload because we cannot listen to the file system.
You don't need to worry! This is an optional feature used during development to
refresh your browser when you save files and it does not affect production.

14:10:26.460 application=phoenix [info] Running BlockScoutWeb.Endpoint with Cowboy using http://0.0.0.0:4000
14:10:26.594 [info] Application indexer exited: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.BlockFetcher.Supervisor
    ** (EXIT) shutdown: failed to start child: Indexer.BlockFetcher.Realtime.Supervisor
        ** (EXIT) shutdown: failed to start child: EthereumJSONRPC.WebSocket.WebSocketClient
            ** (EXIT) an exception was raised:
                ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.WebSocket.WebSocketClient.start_link/1
                    (ethereum_jsonrpc) lib/ethereum_jsonrpc/web_socket/web_socket_client.ex:30: EthereumJSONRPC.WebSocket.WebSocketClient.start_link(["ws://localhost:8546", [name: Indexer.BlockFetcher.Realtime.WebSocket]])
                    (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
                    (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
                    (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
                    (stdlib) supervisor.erl:1157: :supervisor.children_map/4
                    (stdlib) supervisor.erl:315: :supervisor.init_children/2
                    (stdlib) gen_server.erl:374: :gen_server.init_it/2
                    (stdlib) gen_server.erl:342: :gen_server.init_it/6
                    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application indexer: Indexer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Indexer.BlockFetcher.Supervisor
    ** (EXIT) shutdown: failed to start child: Indexer.BlockFetcher.Realtime.Supervisor
        ** (EXIT) shutdown: failed to start child: EthereumJSONRPC.WebSocket.WebSocketClient
            ** (EXIT) an exception was raised:
                ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.WebSocket.WebSocketClient.start_link/1
                    (ethereum_jsonrpc) lib/ethereum_jsonrpc/web_socket/web_socket_client.ex:30: EthereumJSONRPC.WebSocket.WebSocketClient.start_link(["ws://localhost:8546", [name: Indexer.BlockFetcher.Realtime.WebSocket]])
                    (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
                    (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
                    (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
                    (stdlib) supervisor.erl:1157: :supervisor.children_map/4
                    (stdlib) supervisor.erl:315: :supervisor.init_children/2
                    (stdlib) gen_server.erl:374: :gen_server.init_it/2
                    (stdlib) gen_server.erl:342: :gen_server.init_it/6
                    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
although I can check with a web3js script that websockets work

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
```
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.7.3 (compiled with Erlang/OTP 21)
```

* Operating System: `Ubuntu 16.04`

### Steps to reproduce

Let me know if you need details on how to setup parity locally and reproduce this in-full

### Expected behaviour

Indexer starts

### Actual behaviour

Indexer doesn't start

**Comment by acravenho** [comment]
Phoenix requires `inotify` on Linux. `apt-get install inotify-tools` should do the trick. I will test soon to make sure it works and update the README.

**Comment by natlg** [comment]
I checked it with `inotify`, WebSocket error still appears. Seems it's because of SSL certificate checking [here](https://github.com/poanetwork/blockscout/blob/master/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex#L30)
If change `wss` to `ws` here, no errors will be printed, but new blocks will not be received.

**Comment by shisoft** [comment]
I got the same problem from the docker image you provided. Using wss for websocket address

**Comment by acravenho** [comment]
@shisoft I don't see `ETHEREUM_JSONRPC_TRACE_URL` defined. If you're using a Parity node, you have to define the trace node endpoint.

**Comment by acravenho** [comment]
@shisoft That's correct if you have tracing enabled on the same node the RPC endpoint will be the same. Place make sure you have `tracing` and `pruning` enabled. Pruning keeps the state of old blocks which we fetch the state for.

**Comment by shisoft** [comment]
@acravenho Thanks for the heads up

**Comment by vbaranov** [comment]
@phahulin WebSockets should work with `inotify-tools` installed on Ubuntu. Please check requirements for installation https://docs.blockscout.com/for-developers/information-and-settings/requirements. In addition, if to remove `ETHEREUM_JSONRPC_WS_URL` ENV var, which manage node Websockets URL ([a reference to the full list of ENV vars](https://app.gitbook.com/@poa/s/blockscout/for-developers/information-and-settings/env-variables)), Blockscout will poll the node with JSON RPC requests for a live reload new blocks, txs on the pages. I am closing this. Please, let us know if you will experience this issue again.
