### ISSUE TITLE
Failed contract creation breaks tx details page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#712]
While creating a failed transaction which has `gas_limit = gas_used` I encountered this bug which completely breaks the page. I believe we're trying to display the contract address and link which doesn't exist (`nil`)

```
12:52:55.912 [error] #PID<0.2413.0> running BlockScoutWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /tx/0xab349efbe1ddc6d85d84a993aa52bdaadce66e8ee166dd10013ce3f2a94ca724/internal_transactions
** (exit) an exception was raised:
    ** (ArgumentError) cannot convert nil to param
        (phoenix) lib/phoenix/param.ex:67: Phoenix.Param.Atom.to_param/1
        (block_scout_web) lib/block_scout_web/router.ex:1: BlockScoutWeb.Router.Helpers.address_path/4
        (block_scout_web) lib/block_scout_web/templates/address/_link.html.eex:1: BlockScoutWeb.AddressView."_link.html"/1
        (block_scout_web) lib/block_scout_web/templates/transaction_internal_transaction/_internal_transaction.html.eex:11: BlockScoutWeb.TransactionInternalTransactionView."_internal_transaction.html"/1
        (block_scout_web) lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex:67: anonymous fn/2 in BlockScoutWeb.TransactionInternalTransactionView."index.html"/1
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (block_scout_web) lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex:66: BlockScoutWeb.TransactionInternalTransactionView."index.html"/1
        (block_scout_web) lib/block_scout_web/templates/layout/app.html.eex:17: BlockScoutWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
        (block_scout_web) lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex:1: BlockScoutWeb.TransactionInternalTransactionController.action/2
        (block_scout_web) lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex:1: BlockScoutWeb.TransactionInternalTransactionController.phoenix_controller_pipeline/2
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
        (block_scout_web) lib/plug/debugger.ex:99: BlockScoutWeb.Endpoint."call (overridable 3)"/2
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/andrewcravenho/Documents/GitHub/poanetwork/blockscout/production/classic/blockscout/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```
### Environment

* Operating System: Mac

### Steps to reproduce

1. Deploy a contract that fails
2. View the tx hash.

### Expected behaviour

Show the tx details page.

### Actual behaviour

💥

**Comment by vbaranov** [comment]
Cannot be reproduced anymore
