### ISSUE TITLE
no function clause matching in BlockScoutWeb.AddressView.matching_address_check

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#739]
```
17:07:21.958 [error] GenServer #PID<0.4051.1> terminating
** (FunctionClauseError) no function clause matching in BlockScoutWeb.AddressView.matching_address_check/4
    (block_scout_web) lib/block_scout_web/views/address_view.ex:120: BlockScoutWeb.AddressView.matching_address_check(nil, #Ecto.Association.NotLoaded<association :created_contract_address is not loaded>, true, false)
    (block_scout_web) lib/block_scout_web/templates/transaction/_tile.html.eex:16: BlockScoutWeb.TransactionView."_tile.html"/1
    (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
    (phoenix) lib/phoenix/view.ex:339: Phoenix.View.render_to_string/3
    (block_scout_web) lib/block_scout_web/channels/transaction_channel.ex:20: BlockScoutWeb.TransactionChannel.handle_out/3
    (phoenix) lib/phoenix/channel/server.ex:252: Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Broadcast{event: "new_transaction", payload: %{transaction: %Explorer.Chain.Transaction{__meta__: #Ecto.Schema.Metadata<:loaded, "transactions">, block: %Explorer.Chain.Block{__meta__: #Ecto.Schema.Metadata<:loaded, "blocks">, difficulty: #Decimal<3274273089548051>, gas_limit: 8000029, gas_used: 7990217, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<110, 212, 164, 244, 166, 99, 242, 235, 58, 43, 213, 214, 91, 66, 19, 132, 128, 16, 97, 125, 144, 75, 47, 21, 237, 170, 99, 4, 117, 249, 105, 74>>}, inserted_at: #DateTime<2018-09-16 21:07:08.721382Z>, miner: #Ecto.Association.NotLoaded<association :miner is notloaded>, miner_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<234, 103, 79, 221, 231, 20, 253, 151, 157, 227, 237, 240, 245,106, 169, 113, 107, 137, 142, 200>>}, nonce: %Explorer.Chain.Hash{byte_count: 8, bytes: <<75, 10, 178, 20, 78, 161, 164, 196>>}, number: 6344493, parent: #Ecto.Association.NotLoaded<association :parent is not loaded>, parent_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<182, 204, 128, 21, 193, 32, 229, 64, 243, 6, 28, 177, 146, 107, 29, 141, 110, 193, 185, 83, 28, 17, 8, 41, 104, 83, 21, 25, 194, 10, 48, ...>>}, size: 39010, timestamp: #DateTime<2018-09-16 21:05:08.000000Z>, total_difficulty: #Decimal<6670008414949255670276>, transactions: #Ecto.Association.NotLoaded<association :transactions is not loaded>, updated_at: #DateTime<2018-09-16 21:07:08.721382Z>}, block_hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<110, 212, 164, 244, 166, 99, 242, 235, 58, 43,213, 214, 91, 66, 19, 132, 128, 16, 97, 125, 144, 75, 47, 21, 237, 170, 99, 4, 117, 249, 105, 74>>}, block_number: 6344493, created_contract_address: #Ecto.Association.NotLoaded<association :created_contract_address is not loaded>, created_contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<78, 218, 50, 173, 136, 237, 38, 47, 31, 223, 0, 58, 173, 23, 36, 60, 97, 78, 59,68>>}, cumulative_gas_used: #Decimal<889572>, from_address: %Explorer.Chain.Address{__meta__: #Ecto.Schema.Metadata<:loaded, "addresses">, contract_code: nil, contracts_creation_internal_transaction: #Ecto.Association.NotLoaded<association :contracts_creation_internal_transaction is not loaded>, fetched_coin_balance: #Explorer.Chain.Wei<112712610187500000>, fetched_coin_balance_block_number: 6344493, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<165, 14, 8, 223, 195, 2, 9, 69, 98, 43, 190, 15, 94, 255, 161, 78, 241, 184, 32, 71>>}, inserted_at: #DateTime<2018-09-16 21:02:30.997967Z>, names: [], smart_contract: #Ecto.Association.NotLoaded<association :smart_contract is not loaded>, token: #Ecto.Association.NotLoaded<association :token is not loaded>, updated_at: #DateTime<2018-09-16 21:02:30.997967Z>}, from_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<165, 14, 8, 223, 195, 2, 9, 69, 98, 43, 190, 15, 94, 255, 161, 78, 241, 184, 32, 71>>}, gas: #Decimal<6721975>, gas_price: #Explorer.Chain.Wei<4000000000>,gas_used: #Decimal<277462>, hash: %Explorer.Chain.Hash{byte_count: 32, bytes: <<113, 249, 247, 229, 160, 126, 44, 29, 183, 207, 77, 65, 52, 81, 64, 116, 170, 160, 89, 179, 196, 192, 95, 162, 107, 139, 128, 18, 216, 99, 18, 9>>}, index: 22, input: %Explorer.Chain.Data{bytes: <<96, 128, 96, 64, 82, 52, 128, 21, 97, 0, 16, 87, 96, 0, 128, 253, 91, 80, 51, 96, 0, 128, 97, 1, 0, 10, 129, 84,129, 115, 255, ...>>}, inserted_at: #DateTime<2018-09-16 21:07:08.721382Z>, internal_transactions: #Ecto.Association.NotLoaded<association :internal_transactions is not loaded>, internal_transactions_indexed_at: #DateTime<2018-09-16 21:07:08.721382Z>, logs: #Ecto.Association.NotLoaded<association :logs is not loaded>, nonce: 0, r: #Decimal<114642120558569177348214444570404709134685160317091152580246312987207114871135>, s: #Decimal<27900300502419881696743348874241754304983216040462006844839625768155277362880>, status: :ok, to_address: nil, to_address_hash: nil, token_transfers: [], updated_at: #DateTime<2018-09-16 21:07:08.721382Z>, v: 38, value: #Explorer.Chain.Wei<0>}}, topic: "transactions:new_transaction"}
State: %Phoenix.Socket{assigns: %{locale: "en"}, channel: BlockScoutWeb.TransactionChannel, channel_pid: #PID<0.4051.1>, endpoint: BlockScoutWeb.Endpoint, handler: BlockScoutWeb.UserSocket, id: nil, join_ref: "4", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: BlockScoutWeb.PubSub, ref: nil, serializer: Phoenix.Transports.V2.WebSocketSerializer, topic: "transactions:new_transaction", transport: Phoenix.Transports.WebSocket, transport_name: :websocket, transport_pid: #PID<0.4025.1>, vsn: "2.0.0"}
```

### Environment

* Operating System: Ubuntu 18.04
* Chain: Ethereum

### Steps to reproduce

1. Index Ethereum Mainnet
2. I'm not sure what happened next. I was reviewing the error logs when I noticed this.

### Expected behaviour

n/a

**Comment by alexgaribay** [comment]
This looks most likely related to my address names PR. I’ll take a look on
Monday. I likely missed a spot in the channels portion.



From: Andrew Cravenho <notifications@github.com> <notifications@github.com>
Reply: poanetwork/blockscout
<reply@reply.github.com>
<reply@reply.github.com>
Date: September 16, 2018 at 4:42:50 PM
To: poanetwork/blockscout <blockscout@noreply.github.com>
<blockscout@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  [poanetwork/blockscout] no function clause matching in
BlockScoutWeb.AddressView.matching_address_check (#739)

17:07:21.958 [error] GenServer #PID<0.4051.1> terminating

**Comment by acravenho** [comment]
Thanks Alex. Yeah, I figured
