### ISSUE TITLE
Indexer.Block.Realtime.Fetcher terminating no with clause matching

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#763]
I've noticed this popping up on ETH mainnet every 300-500 blocks.

```
16:36:36.716 [error] GenServer Indexer.Block.Realtime.Fetcher terminating
** (WithClauseError) no with clause matching: {:error, :timeout}
    (indexer) lib/indexer/block/fetcher.ex:92: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:65: Indexer.Block.Realtime.Fetcher.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {%EthereumJSONRPC.Subscription{id: "0x0f1a1a0f234c5ca7", subscriber_pid: #PID<0.578.0>, transport: EthereumJSONRPC.WebSocket, transport_options: [web_socket: EthereumJSONRPC.WebSocket.WebSocketClient, web_socket_options: %{web_socket: #PID<0.577.0>}, url: "**redacted**"]}, {:ok, %{"author" => "0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5", "difficulty" => "0xb52e7d8b9c894", "extraData" => "0x6e616e6f706f6f6c2e6f7267", "gasLimit" => "0x79e26b", "gasUsed" => "0x7993ac", "hash" => "0x878b8b2dccd54acb5ec239c46e0f99bc6209119954b6602a504705a159217a34", "logsBloom" => "0x040a7003006000088102d00003003002000002082082003224541008900000000010200000048019211040428000101040000004018110118808080100000018000400801605000004401208000000000208000000000120800121144060043101820000040000000590024001800582000012000080094200200110208000480c0802000025c800805410848290040a00110900028000000018004200001140200010610000100808c04101000007204028000000180000400800481c0000010008802240001000c1020014850004020800010000080800220018c00102104020002000000401008000000000402c010010000060d800442005480000800010", "miner" => "0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5", "mixHash" => "0x4d755b185e588d32bf34201046bb9da74a686f94afba4ec1d427016108189388", "nonce" => "0x3cf881ee021653f9", "number" => "0x611586", "parentHash" => "0x260618493c97de32e6f4fd8a5609567312a136445397a9f7bdd1e35ccfffbdcf", "receiptsRoot" => "0x8c928a77f87c0afaa7890424739ae0f59b3dca1c075c28634d03d2e5c19dcd60", "sealFields" => ["0x4d755b185e588d32bf34201046bb9da74a686f94afba4ec1d427016108189388", "0x3cf881ee021653f9"], "sha3Uncles" => "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size" => "0x210", "stateRoot" => "0xd0ffc0fa8406b30e1b0a1a88bb6172e6e3991103abefc9e415f44b755d2ed800", "timestamp" => "0x5ba2b281", "transactionsRoot" => "0xc577e730c754511458a1ec40cffd9eec82ec88fa34c71f8b16b2735178868b04"}}}
State: %Indexer.Block.Realtime.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: true, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "**redacted**", method_to_url: [eth_getBalance: "**redacted**", trace_replayTransaction: "**redacted**"], http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, subscription: %EthereumJSONRPC.Subscription{id: "0x0f1a1a0f234c5ca7", subscriber_pid: #PID<0.578.0>, transport: EthereumJSONRPC.WebSocket, transport_options: [web_socket: EthereumJSONRPC.WebSocket.WebSocketClient, web_socket_options: %{web_socket: #PID<0.577.0>}, url: "**redacted**"]}}
```

**Comment by sabondano** [comment]
Looks like this is an http request timeout from: https://github.com/poanetwork/blockscout/blob/master/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http/httpoison.ex#L17

and we're not handling it gracefully in the else branch here: https://github.com/poanetwork/blockscout/blob/3a2c6f93ede0aa63ebdefb4100e74ccddef7c572/apps/indexer/lib/indexer/block/fetcher.ex#L92

We could make the necessary changes to have it log a message when this happens instead of it terminating as in the error above, this seems reasonable to me. Thoughts?

**Comment by acravenho** [comment]
This has been resolved by the reorg PR.
