### ISSUE TITLE
Server crashes when exchange rates are disabled

### ISSUE THREAD

**Issue by prestonvanloon** [poanetwork/blockscout#788]
To reproduce:

Set `config :explorer, Explorer.ExchangeRates, enabled: false` in apps/explorer/config.exs and run the prod server.

```
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.lookup(:exchange_rates, "POA")
        (explorer) lib/explorer/exchange_rates/exchange_rates.ex:97: Explorer.ExchangeRates.lookup/1
        (block_scout_web) lib/block_scout_web/controllers/chain_controller.ex:28: BlockScoutWeb.ChainController.show/2
        (block_scout_web) lib/block_scout_web/controllers/chain_controller.ex:1: BlockScoutWeb.ChainController.action/2
        (block_scout_web) lib/block_scout_web/controllers/chain_controller.ex:1: BlockScoutWeb.ChainController.phoenix_controller_pipeline/2
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
11:39:14.516 application=indexer [info] Index already caught up in 2485-0
11:39:14.516 application=indexer [info] Checking if index needs to catch up in 5000ms
11:39:15.728 application=indexer [info] Index already caught up in 2485-0
11:39:15.728 application=indexer [info] Checking if index needs to catch up in 5000ms
11:39:16.223 application=indexer [info] Index already caught up in 2485-0
11:39:16.223 application=indexer [info] Checking if index needs to catch up in 5000ms
11:39:17.323 [info] Application indexer exited: shutdown
{"Kernel pid terminated",application_controller,"{application_terminated,indexer,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,indexer,shutdown})
```

**Comment by prestonvanloon** [comment]
Actually, I think this is my environment killing the server for using more than the allocated memory.

**Comment by prestonvanloon** [comment]
Nope, it's not that. It's crashing for some reason, but i'm not sure how to debug this.

**Comment by KronicDeth** [comment]
Those `enabled` flags are only there so we can disable them during testing.  They're not meant for you to opt-out of getting market data.

**Comment by KronicDeth** [comment]
Do you want disabling getting market data in production a feature @acravenho?

**Comment by acravenho** [comment]
@KronicDeth #811 will add the option to remove the USD values and also update the graph on the homepage to a transaction-based graph instead of the price based graph.
