### ISSUE TITLE
(MatchError) no match of right hand side value:

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#850]
```
16:39:10.074 [error] Task #PID<0.1708.0> started from #PID<0.609.0> terminating
** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: 32172, message: nil, postgres:%{code: :not_null_violation, column: "index", detail: "Failing row contains (\\x0035cab9b3e5a314b3e2d03c1278e925ce689dab67a27fe6363825613eee07..., null, null, 2018-10-02 20:39:10.070572, 2018-10-02 20:39:10.070572).", file: "execMain.c", line:"2008", message: "null value in column \"index\" violates not-null constraint", pg_code: "23502", routine: "ExecConstraints", schema: "public", severity: "ERROR", table: "transaction_forks", unknown: "ERROR"}}}
    (explorer) lib/explorer/chain/import.ex:1052: Explorer.Chain.Import.derive_transaction_forks/1
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/chain/import.ex:236: Explorer.Chain.Import.all/1
    (indexer) lib/indexer/block/catchup/fetcher.ex:114: Indexer.Block.Catchup.Fetcher.import/2
    (indexer) lib/indexer/block/fetcher.ex:119: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:180: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<10.77091675/1 in Indexer.Block.Catchup.Fetcher.stream_fetch_and_import/2>, [4849970..4849961]]
16:39:10.074 [error] Task #PID<0.1706.0> started from #PID<0.609.0> terminating
** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: 32174, message: nil, postgres:%{code: :not_null_violation, column: "index", detail: "Failing row contains (\\x0035cab9b3e5a314b3e2d03c1278e925ce689dab67a27fe6363825613eee07..., null, null, 2018-10-02 20:39:10.06851, 2018-10-02 20:39:10.06851).", file: "execMain.c", line: "2008", message: "null value in column \"index\" violates not-null constraint", pg_code: "23502", routine: "ExecConstraints", schema: "public", severity: "ERROR", table: "transaction_forks", unknown: "ERROR"}}}
    (explorer) lib/explorer/chain/import.ex:1052: Explorer.Chain.Import.derive_transaction_forks/1
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (explorer) lib/explorer/chain/import.ex:236: Explorer.Chain.Import.all/1
    (indexer) lib/indexer/block/catchup/fetcher.ex:114: Indexer.Block.Catchup.Fetcher.import/2
    (indexer) lib/indexer/block/fetcher.ex:119: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:180: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: **&:erlang.apply/2**
```

### Environment

* Operating System: Ubuntu

### Steps to reproduce

1. Start indexing
2. Error happens while trying to fetch the first catchup blocks

### Expected behaviour

index blocks

### Actual behaviour

n/a

**Comment by acravenho** [comment]
This error only occurs on `sokol` when a non-tracing node is in place.

**Comment by KronicDeth** [comment]
There's a bug with `where_forked`, where if there are no blocks it will select **ALL** transactions because no `WHERE` conditions are added to the `SELECT ... FROM transactions`.  The error you're seeing is that `WHERE`-less select trying to fork a pending transaction.  I have a regression test reproducing this.  I will

1. Fix the error reporting so it doesn't error at this point, but return an `:error` tuple from `Import.all`
2. Fix `where_forked` so it selects nothing if there are no blocks
3. Audit the `run_*` functions in general, so that they do nothing when the param set is empty instead of doing a useless query.
