### ISSUE TITLE
TokenFetcher character_not_in_repertoir

### ISSUE THREAD

**Issue by APshenkin** [poanetwork/blockscout#956]
*Describe your issue here.*
This error is occurring in tokenFetcher when syncing kovan network

```
Function: &Indexer.Token.Fetcher.run/3
    Args: [[%Explorer.Chain.Hash{byte_count: 20, bytes: <<145, 168, 53, 109, 109, 248, 142, 210, 55, 74, 173, 31, 34, 251, 151, 13, 143, 166, 122, 183>>}], 1108, [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://ethereum-node.qa.boople.co", method_to_url: [eth_getBalance: "http://ethereum-node.qa.boople.co", trace_replayTransaction: "http://ethereum-node.qa.boople.co"], http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity]]
iex(1)> 10:16:55.697 [error] Task #PID<0.16249.1> started from Indexer.Token.Fetcher terminating
** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire): invalid byte sequence for encoding "UTF8": 0x00
    (ecto) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.struct/8
    (ecto) lib/ecto/repo/schema.ex:547: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:213: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:774: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
    (db_connection) lib/db_connection.ex:1374: DBConnection.transaction_nested/2
    (db_connection) lib/db_connection.ex:1234: DBConnection.transaction_meter/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
* Operating System: Debian GNU/Linux 9 (stretch)

### Steps to reproduce

Try to index kovan testnet

### Expected behaviour

No errors with token fetcher

**Comment by APshenkin** [comment]
Found contract, that causes this issue:
```
0x91a8356d6df88ed2374aad1f22fb970d8fa67ab7
```
